/**
 * 
 */
package org.eclipsescout.contacts.shared.ui.desktop.outline.pages;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.pagedata.PageDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PersonTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  public PersonTablePageData() {
  }

  @Override
  public PersonTableRowData addRow() {
    return (PersonTableRowData) super.addRow();
  }

  @Override
  public PersonTableRowData addRow(int rowState) {
    return (PersonTableRowData) super.addRow(rowState);
  }

  @Override
  public PersonTableRowData createRow() {
    return new PersonTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return PersonTableRowData.class;
  }

  @Override
  public PersonTableRowData[] getRows() {
    return (PersonTableRowData[]) super.getRows();
  }

  @Override
  public PersonTableRowData rowAt(int index) {
    return (PersonTableRowData) super.rowAt(index);
  }

  public void setRows(PersonTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class PersonTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String personId = "personId";
    public static final String firstName = "firstName";
    public static final String lastName = "lastName";
    public static final String headline = "headline";
    private String m_personId;
    private String m_firstName;
    private String m_lastName;
    private String m_headline;

    public PersonTableRowData() {
    }

    /**
     * @return the PersonId
     */
    public String getPersonId() {
      return m_personId;
    }

    /**
     * @param personId
     *          the PersonId to set
     */
    public void setPersonId(String personId) {
      m_personId = personId;
    }

    /**
     * @return the FirstName
     */
    public String getFirstName() {
      return m_firstName;
    }

    /**
     * @param firstName
     *          the FirstName to set
     */
    public void setFirstName(String firstName) {
      m_firstName = firstName;
    }

    /**
     * @return the LastName
     */
    public String getLastName() {
      return m_lastName;
    }

    /**
     * @param lastName
     *          the LastName to set
     */
    public void setLastName(String lastName) {
      m_lastName = lastName;
    }

    /**
     * @return the Headline
     */
    public String getHeadline() {
      return m_headline;
    }

    /**
     * @param headline
     *          the Headline to set
     */
    public void setHeadline(String headline) {
      m_headline = headline;
    }
  }
}
