/**
 * 
 */
package org.eclipsescout.contacts.shared.ui.desktop.outlines;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.pagedata.PageDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class CompanyTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  public CompanyTablePageData() {
  }

  @Override
  public CompanyTableRowData addRow() {
    return (CompanyTableRowData) super.addRow();
  }

  @Override
  public CompanyTableRowData addRow(int rowState) {
    return (CompanyTableRowData) super.addRow(rowState);
  }

  @Override
  public CompanyTableRowData createRow() {
    return new CompanyTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return CompanyTableRowData.class;
  }

  @Override
  public CompanyTableRowData[] getRows() {
    return (CompanyTableRowData[]) super.getRows();
  }

  @Override
  public CompanyTableRowData rowAt(int index) {
    return (CompanyTableRowData) super.rowAt(index);
  }

  public void setRows(CompanyTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class CompanyTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String companyId = "companyId";
    public static final String name = "name";
    public static final String city = "city";
    public static final String country = "country";
    public static final String homepage = "homepage";
    private String m_companyId;
    private String m_name;
    private String m_city;
    private String m_country;
    private String m_homepage;

    public CompanyTableRowData() {
    }

    /**
     * @return the CompanyId
     */
    public String getCompanyId() {
      return m_companyId;
    }

    /**
     * @param companyId
     *          the CompanyId to set
     */
    public void setCompanyId(String companyId) {
      m_companyId = companyId;
    }

    /**
     * @return the Name
     */
    public String getName() {
      return m_name;
    }

    /**
     * @param name
     *          the Name to set
     */
    public void setName(String name) {
      m_name = name;
    }

    /**
     * @return the City
     */
    public String getCity() {
      return m_city;
    }

    /**
     * @param city
     *          the City to set
     */
    public void setCity(String city) {
      m_city = city;
    }

    /**
     * @return the Country
     */
    public String getCountry() {
      return m_country;
    }

    /**
     * @param country
     *          the Country to set
     */
    public void setCountry(String country) {
      m_country = country;
    }

    /**
     * @return the Homepage
     */
    public String getHomepage() {
      return m_homepage;
    }

    /**
     * @param homepage
     *          the Homepage to set
     */
    public void setHomepage(String homepage) {
      m_homepage = homepage;
    }
  }
}