
ifndef::finaldoc[]
include::../_initDoc.adoc[]
endif::finaldoc[]

//fallback for safe mode == secure:
:imgsdir: ../../imgs
:codedir: ../../../code
ifndef::mdledir[:mdledir: .]
:experimental:

== Scout JS

=== Widget

==== What is a widget?

==== How to create a custom widget

=== Table

==== How to add a row

==== How to change the column title

=== Extensibility

==== How to extend Scout objects

The extension feature in Scout JS works by wrapping functions on the prototype of a Scout object
with a wrapper function which is provided by an extension. The extension feature doesn't rely on
subclassing, instead we simply register one or more extensions for a single Scout class. When a
function is called on an extended object, the functions are called on the registered extensions
first. Since a Scout class can have multiple extensions, we speak of an extension chain, where the
last element of the chain is the original (extended) object.

The base class for all extensions is `scout.Extension`. This class is used to extend an existing
Scout object. In order to use the extension feature you must subclass +scout.Extension+ and
implement an `init` function, where you register the functions you want to extend. Example:

[source,javascript]
----
scout.MyExtension.prototype.init = function() {
  this.extend(scout.MyStringField.prototype, '_init');
  this.extend(scout.MyStringField.prototype, '_renderProperties');
};
----

Then you implement functions with the same name and signature on the extension class. Example:

[source,javascript]
----
scout.MyExtension.prototype._init = function(model) {
  this.next(model);
  this.extended.setProperty('bar', 'foo');
};
----

The extension feature sets two properties on the extension instance before the extended method
is called. These two properties are described below. The function scope (this) is set to the extension
instance when the extended function is called.

next:: is a reference to the next extended function or the original function of the extended object,
  in case the current extension is the last extension in the extension chain.
extended:: is the extended or original object.

All extensions must be registered in the `installExtensions` function of your `scout.App`.
Example:

[source,javascript]
----
scout.MyApp.prototype.installExtensions = function() {
  scout.Extension.install([
    'scout.FooExtension',
    'scout.BarExtension',
    // ...
  ]);
};
----

==== How to extend JSON model

TODO: Cyrill Wyss?

==== Export Scout model from a Scout classic (online) application

With the steps described here you can export model-data (e.g. forms, tables, etc.) from an existing classic, online Scout application into JSON format which
can be used in a Scout JS application. This is a fast and convenient method to re-use an existing form in a Scout JS application, because you don't have to
build the model manually. Here's how to use the export feature:

* Activate the `TextKeyTextProviderService` in your Scout classic application. You can do this either by calling the static `register` Method at
  runtime (using the Debugger) or by setting the config property _scout.text.providers.show.keys_. Once the TextProvider is active, it returns text keys instead
  of localized texts. The format of the returned string is `${textKey:[text-key]}`. Strings in this format are interpreted browser side by Scout JS and
  are resolved and localized in _texts.js_.
* Call the Scout classic web application with the URL parameter `?adapterExportEnabled=true`. This parameter is checked by Scout JS and the effect of it is that
  Scout JS keeps adapter-data loaded from the server, so we can use it for a later export operation. Usually Scout JS deletes adapter-data right after it has
  been used to create an adapter instance.
* Start your browsers developer tools (F12) from your running Scout classic app, inspect the form or another adapter you'd like to export, and search for
  the ID of that adapter by looking at the `data-id` attribute in the DOM. Then call the following JavaScript function from the console: `JSON.stringify(scout.exportAdapter([id]))`.
  The console will now output the JSON code for that adapter. Copy/paste that string from the console and tidy it up with a tool of your choice (for instance http://www.jsoneditoronline.org[jsoneditoronline.org]).
* Now the formatted JSON code is ready to be used in your Scout JS project. Simply store the JSON to a .json File and load it in the `_jsonModel` function of
  your widget by calling `scout.models.getModel('[ID of json model]')`. Most likely you must edit the JSON file and apply some changes manually.
  For instance:
  ** Replace numeric adapter IDs by human-readable, semantic string IDs. You will need these IDs to reference a model element from the JSON model in your
    JavaScript code, e.g. to register a listener on a Menu.
  ** Maybe you'll have to adjust objectType and namespace of some widgets in the JSON. This needs to be done for widgets
     that do not belong to the default _scout_ namespace.
  ** Remove form fields and menus which are never used in your Scout JS app
  ** Remove unused menu types from the menuTypes property of a scout.Menu

Note: The function exportAdapter can be used not only for forms, but for any other widget/adapter too.


