
ifndef::finaldoc[]
include::../_initDoc.adoc[]
endif::finaldoc[]

//fallback for safe mode == secure:
:imgsdir: ../../imgs
:codedir: ../../../code
ifndef::mdledir[:mdledir: .]
:experimental:

== Scout JS

=== Widget

==== What is a widget?

==== How to create a custom widget

=== Table

==== How to add a row

==== How to change the column title

=== Extensibility

==== How to extend Scout objects

The extension feature in Scout JS works by wrapping functions on the prototype of a Scout object
with a wrapper function which is provided by an extension. The extension feature doesn't rely on
subclassing, instead we simply register one or more extensions for a single Scout class. When a
function is called on an extended object, the functions are called on the registered extensions
first. Since a Scout class can have multiple extensions, we speak of an extension chain, where the
last element of the chain is the original (extended) object.

The base class for all extensions is +scout.Extension+. This class is used to extend an existing
Scout object. In order to use the extension feature you must subclass +scout.Extension+ and
implement an +init+ function, where you register the functions you want to extend. Example:

[source,javascript]
----
scout.MyExtension.prototype.init = function() {
  this.extend(scout.MyStringField.prototype, '_init');
  this.extend(scout.MyStringField.prototype, '_renderProperties');
};
----

Then you implement functions with the same name and signature on the extension class. Example:

[source,javascript]
----
scout.MyExtension.prototype._init = function(model) {
  this.next(model);
  this.extended.setProperty('bar', 'foo');
};
----

The extension feature sets two properties on the extension instance before the extended method
is called. These two properties are described below. The function scope (this) is set to the extension
instance when the extended function is called.

next:: is a reference to the next extended function or the original function of the extended object,
  in case the current extension is the last extension in the extension chain.
extended:: is the extended or original object.

All extensions must be registered in the +installExtensions+ function of your +scout.App+.
Example:

[source,javascript]
----
scout.MyApp.prototype.installExtensions = function() {
  scout.Extension.install([
    'scout.FooExtension',
    'scout.BarExtension',
    // ...
  ]);
};
----


==== How to extend JSON model

TODO
