:license_cc: https://creativecommons.org/licenses/by/3.0/
:license_edl: https://www.eclipse.org/org/documents/edl-v10.php

= Eclipse Scout - Docs

This repository is part of the link:https://github.com/eclipse-scout/scout.rt[Eclipse Scout] project.
It contains the source of the documentation items and some demo applications created with the framework.
The documentation is published on link:https://eclipsescout.github.io/[GitHub pages] and you can also find the _Eclipse Scout User Guide_ in the link:https://help.eclipse.org[Eclipse Help Center].


== Organisation of this Repository

* `docs` folder: contains the documentation source, link:docs/[read more],
* `code` folder: contains demo applications (code snippets in the documentation items are extracted from this code base during the build)

== Build

The documentation items are built with maven: check the link:docs/README.adoc[README of the docs folder].

The demo applications are built with maven: check the link:code/README.adoc[README of the code folder].


== License

* The example source code is licensed under link:{license_edl}[Eclipse Distribution License (EDL)]
* The documentation text is licensed under link:{license_cc}[Creative Commons Attribution 3.0 (Unported) License]


