= Eclipse Scout - Docs

This repository is part of the link:https://github.com/eclipse-scout/scout.rt[Eclipse Scout] project.
It contains the source of the documentation and some demo applications created with the framework.
The documentation is published on link:https://eclipsescout.github.io/[GitHub pages].

== Organisation of this Repository

* `docs/modules`: contains the documentation source.
* `docs/playbooks`: contains the playbooks and user interface bundles for the Antora build.
* `code`: contains demo applications and code snippets for the documentation.

== Demo Applications

The demo applications are built with maven.

== Documentation

The documentation is built using https://antora.org/[Antora].

To build and open the documentation locally, do the following steps:

. On Windows, open the `cmd` shell _as administrator_ and run the script `docs\create_symlinks.cmd` (see <<Windows and Symbolic Links>>).
. Open a terminal as regular user in the project root where the `package.json` is and run `npm run build`.

=== Windows and Symbolic Links

By default, Windows does not enable the creation of symbolic links.
Because of that, git creates little text files for the symbolic links containing the path to the link target.
So before building the documentation, these files need to be replaced with real symbolic links.

=== Playbooks

The Eclipse Scout playbook builds the site for link:https://eclipsescout.github.io/[GitHub pages].
It uses the https://gitlab.com/antora/antora-lunr-extension[Antora Lunr Extension] to provide a client-side search.

`eclipse-scout-ui-bundle.zip` :: the special user interface bundle for the site
`local-eclipse-scout-playbook.yml` :: the playbook that uses the files in the working directory
