:license_cc: https://creativecommons.org/licenses/by/4.0/
:license_edl: https://www.eclipse.org/org/documents/edl-v10.php

= Eclipse Scout - Docs

This repository is part of the link:https://github.com/eclipse-scout/scout.rt[Eclipse Scout] project.
It contains the source of the documentation items and some demo applications created with the framework.
The documentation is published on link:https://eclipsescout.github.io/[GitHub pages] and you can also find the _Eclipse Scout User Guide_ in the link:https://help.eclipse.org[Eclipse Help Center].


== Organisation of this Repository

`modules` contains the documentation sources in a format suitable for an [https://antora.org/ Antora] playbook.

The only tricky part is that _Hello Scout JS_ uses a git subtree to include the xref:https://github.com/bsi-software/helloscoutjs/[helloscoutjs] project as a source of examples.
See xref:modules/helloscout_js/README.adoc[].

== Build

The documentation items are built with Antora. In your Antora playbook:

[listing]
site:
  title: Eclipse Scout Documentation
  start_page: index.adoc 
content:
  sources: 
  - url: https://github.com/bsi-software/org.eclipse.scout.docs.git
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

The demo applications are built with maven: check the link:code/README.adoc[README of the code folder].


== License

* The example source code is licensed under link:{license_edl}[Eclipse Distribution License (EDL)]
* The documentation text is licensed under link:{license_cc}[Creative Commons Attribution 4.0 (Unported) License]


