:scout_home: http://eclipse.org/scout/
:scout_wiki: http://wiki.eclipse.org/Scout/
:scout_forum: http://eclipse.org/forums/eclipse.scout
:scout_ml: http://dev.eclipse.org/mailman/listinfo/scout-dev
:scout_contrib: http://wiki.eclipse.org/Scout/Contribution
:scout_branch: https://wiki.eclipse.org/Scout/Contribution_Guidelines#Git_Branching_Policy
:bugzilla: http://bugs.eclipse.org/bugs/
:bugzilla_query: http://bugs.eclipse.org/bugs/enter_bug.cgi?product=Scout&component=Scout%20Docs
:bugzilla_new: http://bugs.eclipse.org/bugs/enter_bug.cgi?product=Scout&component=Scout%20Docs
:eclipse_cla: http://www.eclipse.org/legal/CLA.php
:eclipse_account: https://dev.eclipse.org/site_login/createaccount.php
:eclipse_sso: https://projects.eclipse.org/user/login/sso
:github_pr: https://help.github.com/categories/collaborating/
:license_cc: http://creativecommons.org/licenses/by/3.0/
:license_edl: https://www.eclipse.org/org/documents/edl-v10.php

= Eclipse Scout - Docs

This Repository is part of the *Eclipse Scout* project.
It contains the source of the documentation items (Eclipse Help, Scout Books, HTML pages...) and some demo applications created with the framework.

link:{scout_home}[Eclipse Scout] is a mature and open framework for modern, service oriented business applications.
It substantially boosts developer productivity and is simple to learn.



== Documentation & Links

* link:{scout_home}[Project homepage]
* link:{scout_wiki}[Eclipse Scout Wiki]
* link:{scout_forum}[Eclipse Scout Forum]
* link:{bugzilla}[Eclipse Bugzilla]
** link:{bugzilla_query}[Existing bug reports]
** link:{bugzilla_new}[Create a new bug]


== Organisation of this Repository

* `docs` folder: contains the documentation source, link:docs/[read more],
* `code` folder: contains demo applications (code snippets in the documentation items are extracted from this code base during the build)

This repository follows the same link:{scout_branch}[git branching policy] as the other eclipse scout repositories.
The *develop* branch contains the latest version.


== Build

The documentation items are built with maven: check the link:docs/README.adoc[README of the docs folder].

The demo applications are built with maven: check the link:code/README.adoc[README of the code folder].


== Issue tracker

This project do not use the GitHub issue tracker but the link:{bugzilla}[Bugzilla] instance hosted by the Eclipse Fundation.

* link:{bugzilla_query}[Existing bug reports] for the "Eclipse Scout - Docs" project.
* link:{bugzilla_new}[Create a new bug] for the "Eclipse Scout - Docs" project.

== How to contribute

We welcome any kind of contributions (Bug report, contribution, pull request...).
Please read the link:{scout_contrib}[Eclipse Scout Contribution page] to know more about it.

The "Eclipse Scout Docs" project accepts normal link:{github_pr}[GitHub pull requests].
Before your contribution can be accepted by the project, you need to create and electronically sign the link:{eclipse_cla}[Eclipse Foundation Contributor License Agreement (CLA)].

1. Log in at link:{eclipse_account}[dev.eclipse.org] and enter your GitHub user name in the account settings.
2. Submit the CLA at link:{eclipse_sso}[projects.eclipse.org].
3. Sign off all commits of your contribution (`git commit -s`).

All pull requests are subject to two automated checks: *ip-validation* verifies the CLA and sign-off status.


== Get in Touch

To get in touch with the Eclipse Scout community, please open a thread in the link:{scout_forum}[Eclipse Scout Forum] or send a mail to link:{scout_ml}[our mailing list]: scout-dev@eclipse.org


== License

* The example source code is licensed under link:{license_edl}[Eclipse Distribution License (EDL)]
* The documentation text is licensed under link:{license_cc}[Creative Commons Attribution 3.0 (Unported) License]


