services:
  otel_collector:
    networks:
      - backend
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - "./otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml"
    command: --config /etc/otelcol/otel-collector-config.yml
    ports:
      - "4318:4318"
    depends_on:
      - prometheus
  prometheus:
    networks:
      - backend
    image: prom/prometheus:latest
    command:
      - "--storage.tsdb.retention.time=15d"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  grafana:
    networks:
      - backend
    image: grafana/grafana-oss:10.0.3
    volumes:
      - "./grafana-datasources:/etc/grafana/provisioning/datasources"
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
volumes:
  grafana-data: { }
networks:
  backend: { }
