/**
 * 
 */
package org.eclipsescout.contacts.shared.ui.template.formfield;

import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractLocationBoxData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  public AbstractLocationBoxData() {
  }

  public City getCity() {
    return getFieldByClass(City.class);
  }

  public Country getCountry() {
    return getFieldByClass(Country.class);
  }

  public static class City extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public City() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class Country extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Country() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);/**
                                          * XXX not processed ValidationRule(lookupCall)
                                          * 'CountryLookupCall.class' is not accessible from here.
                                          * at
                                          * org.eclipsescout.contacts.client.ui.template.formfield.AbstractLocationBox.
                                          * CountryField#getConfiguredLookupCall
                                          */
      ruleMap.put(ValidationRule.ZERO_NULL_EQUALITY, true);
    }
  }
}