/**
 * 
 */
package org.eclipsescout.contacts.shared.ui.template.formfield;

import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractPictureBoxData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  public AbstractPictureBoxData() {
  }

  public PictureUrl getPictureUrl() {
    return getFieldByClass(PictureUrl.class);
  }

  public static class PictureUrl extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public PictureUrl() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }
}