package org.eclipse.scout.contacts.shared.template;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "org.eclipse.scout.contacts.client.template.AbstractEmailField", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractEmailFieldData extends AbstractValueFieldData<String> {

  private static final long serialVersionUID = 1L;
}
