/*******************************************************************************
 * Copyright (c) 2015 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 ******************************************************************************/
package org.eclipse.scout.contacts.shared.template;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "org.eclipse.scout.contacts.client.template.AbstractPictureBox", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractPictureBoxData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  public AbstractPictureBoxData() {
  }

  /**
   * access method for property PictureUrl.
   */
  public String getPictureUrl() {
    return getPictureUrlProperty().getValue();
  }

  /**
   * access method for property PictureUrl.
   */
  public void setPictureUrl(String pictureUrl) {
    getPictureUrlProperty().setValue(pictureUrl);
  }

  public PictureUrlProperty getPictureUrlProperty() {
    return getPropertyByClass(PictureUrlProperty.class);
  }

  public static class PictureUrlProperty extends AbstractPropertyData<String> {

    private static final long serialVersionUID = 1L;

    public PictureUrlProperty() {
    }
  }
}
