////
Howto:
- Write this document such that it helps people to discover new features and other important changes of this release.
- Chronological order is not necessary.
- Describe necessary migration steps in the MigrationGuide document.
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////
== About This Release

The latest version of this release is: {maven-version}.

You can see the {github-changelog-link} on GitHub.

Coming from an older Scout version? Check out the xref:migration:migration-guide.adoc[Migration Guide] for instructions on how to obtain the new version and upgrade existing applications.

//The following enhancements were made after the initial {scout-version} release.
//
//==== 26.2.0
//
// The initial release of this version was *26.2.xyz*.
//
//(Section intentionally left blank for possible future release)
//
// * <<New Feature (since 26.2.xyz)>>
//
// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// * <<New Feature (since 26.2.xyz)>>

== Stateless Backend Server

The Scout backend server was migrated into a stateless architecture without requiring an HTTP- and Scout server session any longer.
In a cloud environment a backend server now supports dynamic horizontal scaling which increases fault tolerance, improves overall
reliability and adds flexibility for updates and deployments in a high availability setup.

During a transition period, session support will be provided in separate modules for legacy purposes, see migration guide for details.

[#tree-scout-js-findnode-added-and-visitnodes-improved]
== Tree: FindNode Added and VisitNodes Improved (Scout JS)

Finding tree nodes may be helpful especially for outlines to find a specific page.
This can now be done using the new function `Tree.findNode()` that either takes a predicate or a subclass of `TreeNode` as argument.

The function uses the existing `visitNodes` function to search for the tree node.
Unfortunately, that function does not have the possibility to abort the traversal at any point.
To support this, it now uses the `TreeVisitResult`, so you can now either skip visiting a subtree or stop visiting completely.
To make it consistent with other visitor functions like `Widget.visitChildren`, returning `true` now stops visiting completely instead of just skipping the subtree.

This means you need to check your visitors according to the xref:migration-guide.adoc#tree-scout-js-api-of-visitnodes-changed[Migration Guide].

== Table: Column Formatter Added (Scout JS)

The `Column` now has a formatter property similar to the one of the `ValueField`.

This makes it possible to change the format function without having to subclass the column.

== Value Field: Async Validator Support Added (Scout JS)

A validator can now be asynchronous by returning a promise.
This can for example be used to call a rest resource that validates the user input.

Please see the xref:technical-guide:user-interface/value-field.adoc#async-validator[Technical Guide] for details.

== HybridManager API improvements (Scout JS)

The `HybridManager` provides API to dispose formerly created widgets. The widgets passed to `HybridManager.disposeWidgets` are collected and disposed in a single hybrid action.

[source,typescript,opts=novalidate]
----
HybridManager.get().disposeWidgets(widgets);
----

== Tab Box: Mark Strategy Added (Scout JS)

The Scout JS `TabBox` now supports marking the tab items that have content or need to be saved, like the Scout Classic `TabBox` already does.
A marked tab item has a slightly darker line below its tab.

You can choose between two strategies:

. `NOT_EMPTY`: Marks a tab item if it is not empty.
. `SAVE_NEEDED`: Marks a tab item if it needs to be saved.

The default strategy is `NOT_EMPTY`.
For tab boxes inside a Search Form it is `SAVE_NEEDED`.

== FormField: Empty Property now Reflects the State of its Children (Scout JS)

`FormField.empty` is now computed based on the empty state of its child fields and not only considers the empty state of the field itself.
This is useful for composite fields that don't have its own empty state like `GroupBox`.

`ValueField` s are not affected because they still only consider their own empty state, so they are empty if they don't have a value.

To influence or disable the computation of the `empty` property, you can set the property `checkEmpty` or override the method `_computeEmpty()`.
Please see the JsDoc of the `FormFieldModel.checkEmpty` for details.

== Locking of Transitive Node Dependencies

To mitigate supply chain attacks and ensure reproducible builds, Scout now provides support to lock the Node.js dependencies.

See the xref:technical-guide:user-interface/build-stack.adoc#node-dependency-resolution[Technical Guide] for details and the xref:migration-guide.adoc#locking-of-transitive-node-dependencies[Migration Guide] for instructions how to enable the feature.
