////
Howto:
- Write this document such that it helps people to discover new features and other important changes of this release.
- Chronological order is not necessary.
- Describe necessary migration steps in the MigrationGuide document.
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////
== About This Release

The latest version of this release is: {maven-version}.

You can see the {github-changelog-link} on GitHub.

Coming from an older Scout version? Check out the xref:migration:migration-guide.adoc[Migration Guide] for instructions on how to obtain the new version and upgrade existing applications.

//The following enhancements were made after the initial {scout-version} release.
//
//==== 26.2.0
//
// The initial release of this version was *26.2.xyz*.
//
//(Section intentionally left blank for possible future release)
//
// * <<New Feature (since 26.2.xyz)>>
//
// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// * <<New Feature (since 26.2.xyz)>>

[#tree-scout-js-findnode-added-and-visitnodes-improved]
== Tree (Scout JS): FindNode Added and VisitNodes Improved

Finding tree nodes may be helpful especially for outlines to find a specific page.
This can now be done using the new function `Tree.findNode()` that either takes a predicate or a subclass of `TreeNode` as argument.

The function uses the existing `visitNodes` function to search for the tree node.
Unfortunately, that function does not have the possibility to abort the traversal at any point.
To support this, it now uses the `TreeVisitResult`, so you can now either skip visiting a subtree or stop visiting completely.
To make it consistent with other visitor functions like `Widget.visitChildren`, returning `true` now stops visiting completely instead of just skipping the subtree.

This means you need to check your visitors according to the xref:migration-guide.adoc#tree-scout-js-api-of-visitnodes-changed[Migration Guide].
