////
Howto:
- Write this document such that it helps people to discover new features and other important changes of this release.
- Chronological order is not necessary.
- Describe necessary migration steps in the MigrationGuide document.
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////
== About This Release

The latest version of this release is: {maven-version}.

You can see the {github-changelog-link} on GitHub.

Coming from an older Scout version? Check out the xref:migration:migration-guide.adoc[Migration Guide] for instructions on how to obtain the new version and upgrade existing applications.

WARNING: {NotReleasedWarning}

//The following enhancements were made after the initial {scout-version} release.
//
//==== 23.2.1
//
// The initial release of this version was *23.2.xyz*.
//
//WARNING: {NotReleasedWarning}
//
//(Section intentionally left blank for possible future release)
//
// * <<New Feature (since 23.2.xyz)>>
//
// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// WARNING: {NotReleasedWarning}
//
// * <<New Feature (since 23.2.xyz)>>

== Demo Applications

The demo applications for this version can be found on the {scout-docs-link} branch of our docs repository on GitHub.

If you just want to play around with them without looking at the source code, you can always use the deployed versions:

* https://scout.bsi-software.com/contacts/
* https://scout.bsi-software.com/widgets/
* https://scout.bsi-software.com/jswidgets/

// ----------------------------------------------------------------------------

== Scout JS

=== Form

[#modal-optional-for-views]
==== Modal Optional for Views

Until now, the default value for `modal` was true.
This has been changed so that the default now depends on the `displayStyle`:
It is still true for `Form.DisplayStyle.Dialog`, but false for `Form.DisplayStyle.View`.

This means if you require your view to be `modal`, set it to true. Otherwise, you can remove the setting.

The reason why this was changed is, because it is less common to have modal views, which also aligns it with the behavior of Scout Classic.

==== SaveNeeded State Updated Automatically

The property `saveNeededVisible` now correctly visualizes if the form needs to be saved.
The default for this property is true for Scout JS forms.
For Scout Classic forms the default has not been changed and is still false.

For this, the form now has a property called `saveNeeded` that will be updated automatically if the `saveNeeded` state on any child field changes (please note that the property on the form field was renamed from `requiresSave` to `saveNeeded`, see xref:migration:migration-guide.adoc#rename-requiressave-to-saveneeded[Migration Guide]).

==== New Property 'checkSaveNeeded' on Form Fields

Sometimes the `saveNeeded` state is not of interest and should not affect the `saveNeeded` state of the form.
This may be the case for fields that contain data that doesn't need to be saved. For this kind of fields, the `saveNeeded` computation can now be disabled by setting `checkSaveNeeded` to false.

[#visitfields-across-field-trees]
==== VisitFields Across Field Trees

The method `FormField.visitFields` now also visits form fields that are not directly connected to a parent form field.
Example: a form field inside a menu. This was necessary to properly detect `saveNeeded` changes of such fields and validate them when a form is stored. If you need the old behavior, consult the xref:migration:migration-guide.adoc#formfield-visitfields-now-visits-deeper[Migration Guide]).

=== MenuTypes

==== Default menuTypes

Default menuTypes have been added to several widgets.
This means that e.g. the `Table` treats a menu without a menuType as if it had set `Table.MenuTypes.EmptySpace`.
For more information about the default menuTypes see xref:technical-guide:user-interface/widget-reference.adoc#menu-types[MenuTypes].


=== SmartFields: Error-Handling for Key-Lookups

Before this change: If a key-lookup inside a SmartField didn't return a result, the SmartField was presented to the user like no value has been chosen.
Internally, however, the (most likely invalid) value was still set on the SmartField.
Hence, the user couldn't see that the current value is invalid and a new value should be set.

This change puts a warning status on the SmartField if a key-lookup doesn't return a value.

Because of the potential consequences, this change was implemented for ScoutJS only (not for Scout Classic).


// ----------------------------------------------------------------------------

== Changes in Scout Classic

=== Health Check Servlet

The logic of executing health checks was extracted from `org.eclipse.scout.rt.server.commons.healthcheck.AbstractHealthCheckServlet` and moved to an own `org.eclipse.scout.rt.server.commons.healthcheck.HealthCheckService`.

The `AbstractHealthCheckServlet` is no longer abstract, was renamed to `HealthCheckServlet` and may be used without further individualization.

To update to the new servlet, the following changes in your `web.xml` are necessary:

* UI Server: Replace `org.eclipse.scout.rt.ui.html.admin.healthcheck.UiHealthCheckServlet` with `org.eclipse.scout.rt.server.commons.healthcheck.HealthCheckServlet` in your `web.xml`
* Backend Server: Replace `org.eclipse.scout.rt.server.admin.healthcheck.ServerHealthCheckServlet` with `org.eclipse.scout.rt.server.commons.healthcheck.HealthCheckServlet` in your `web.xml`
