////
Howto:
- Write this document such that it helps people to discover new features and other important changes of this release.
- Chronological order is not necessary.
- Describe necessary migration steps in the MigrationGuide document.
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////
== About This Release

The latest version of this release is: {maven-version}.

You can see the {github-changelog-link} on GitHub.

Coming from an older Scout version? Check out the xref:migration:migration-guide.adoc[Migration Guide] for instructions on how to obtain the new version and upgrade existing applications.

WARNING: {NotReleasedWarning}

//The following enhancements were made after the initial {scout-version} release.
//
//==== 25.2.1
//
// The initial release of this version was *25.2.xyz*.
//
//WARNING: {NotReleasedWarning}
//
//(Section intentionally left blank for possible future release)
//
// * <<New Feature (since 25.2.xyz)>>
//
// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// WARNING: {NotReleasedWarning}
//
// * <<New Feature (since 25.2.xyz)>>
