////
Howto:
- Write this document such that it helps people to discover new features and other important changes of this release.
- Chronological order is not necessary.
- Describe necessary migration steps in the MigrationGuide document.
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////
== About This Release

The latest version of this release is: {maven-version}.

You can see the {github-changelog-link} on GitHub.

Coming from an older Scout version? Check out the xref:migration:migration-guide.adoc[Migration Guide] for instructions on how to obtain the new version and upgrade existing applications.

WARNING: {NotReleasedWarning}

//The following enhancements were made after the initial {scout-version} release.
//
//==== 24.1.1
//
// The initial release of this version was *24.1.xyz*.
//
//WARNING: {NotReleasedWarning}
//
//(Section intentionally left blank for possible future release)
//
// * <<New Feature (since 24.1.xyz)>>
//
// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// WARNING: {NotReleasedWarning}
//
// * <<New Feature (since 24.1.xyz)>>

== Demo Applications

The demo applications for this version can be found on the {scout-docs-link} branch of our docs repository on GitHub.

If you just want to play around with them without looking at the source code, you can always use the deployed versions:

* https://scout.bsi-software.com/contacts/
* https://scout.bsi-software.com/widgets/
* https://scout.bsi-software.com/jswidgets/

// ----------------------------------------------------------------------------

== New Build & Runtime Requirements

Scout 24.1 requires at least the following:

* The Java 11 support has been dropped. Build and runtime therefore require Java 17 now. Java 21 Support is planned for a future release.
* Furthermore, the build requires
** Maven >= 3.9.2
** Node 20 >= 20.10.0
** pnpm 8 >= 8.11.0

== HTTP/2 Support

Starting with release 24.1 the Scout https://eclipse.dev/jetty/[Jetty] server supports `HTTP/2` together with the already existing `HTTP/1.1`. It is enabled for `http` and `https` (https://en.wikipedia.org/wiki/Transport_Layer_Security[TLS]) access.
Please note that Browsers only use `HTTP/2` when using `https`.

When using `https` also https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation[ALPN] is supported which can upgrade an `HTTP/1.1` request to an `HTTP/2` request if the client supports it.

For Scout 24 and newer enabling `HTTP/2` for your application is recommended. Please refer to the xref:technical-guide:user-interface/browser-support.adoc[documentation] on how to enable `HTTP/2`.


== UI Notifications

It is now possible to push notifications from the backend directly to the UI running in the browser.
With JavaScript, you'll just subscribe for one or more topics and add a handler that should be called when a notification for that topic is published.
To publish a notification, just add any xref:technical-guide:working-with-data/data-object.adoc[Data Object] to the notification registry for a topic.

Learn more about the usage and functionality in the chapter xref:technical-guide:working-with-data/ui-notifications.adoc[UI Notifications].

== Accessibility

We are excited to announce the introduction of enhanced accessibility features in Scout.
This improves the overall user experience for individuals with diverse abilities, ensuring Scout applications are more inclusive and user-friendly.
Scout now includes comprehensive WAI-ARIA support to provide additional information to assistive technologies.
ARIA roles, properties, and states have been implemented to convey the purpose and state of most of Scout's widgets.
Very few complex widgets still lack a comprehensive WAI-ARIA support as these widgets require new concepts of interaction to be completely accessible.

To get familiar with Scouts new accessibility features we recommend using `aria.ts` as a starting point.

== Login form: Add support for second-factor (form-based)

For the form-based login box a basic second-factor support was added.
To verify the second factor a second credential verifier must be registered via `FormBasedAuthConfig#withSecondFactorVerifier`.

== Scout App as embedded Jetty Server to run in a productive environment

The former `org.eclipse.scout.dev.jetty.JettyServer` (now `Application`) was so far only used for development environments.
With this release it was improved so that it can be used in a productive environment too.
The Scout Application class (`org.eclipse.scout.rt.app.Application`) contains a main-method which may be started directly and itself starts an embedded Jetty server.
Therefore, an application server isn't required anymore.
See the migration guide for further information.
