////
Howto:
- Write this document such that it helps people to discover new features and other important changes of this release.
- Chronological order is not necessary.
- Describe necessary migration steps in the MigrationGuide document.
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////
== About This Release

The latest version of this release is: {maven-version}.

You can see the {github-changelog-link} on GitHub.

Coming from an older Scout version? Check out the xref:migration:migration-guide.adoc[Migration Guide] for instructions on how to obtain the new version and upgrade existing applications.

WARNING: {NotReleasedWarning}

//The following enhancements were made after the initial {scout-version} release.
//
//==== 25.1.1
//
// The initial release of this version was *25.1.xyz*.
//
//WARNING: {NotReleasedWarning}
//
//(Section intentionally left blank for possible future release)
//
// * <<New Feature (since 25.1.xyz)>>
//
// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// WARNING: {NotReleasedWarning}
//
// * <<New Feature (since 25.1.xyz)>>

== Demo Applications

The demo applications for this version can be found on the {scout-docs-link} branch of our docs repository on GitHub.

If you just want to play around with them without looking at the source code, you can always use the deployed versions:

* https://scout.bsi-software.com/contacts/
* https://scout.bsi-software.com/widgets/
* https://scout.bsi-software.com/jswidgets/

// ----------------------------------------------------------------------------

== New Build & Runtime Requirements

Scout 25.1 requires at least the following:

* Build and runtime of Scout 25.1 require Java 21 (Java 17 support has been dropped).
