////
Howto:
- Write this document such that it helps people to discover new features and other important changes of this release.
- Chronological order is not necessary.
- Describe necessary migration steps in the MigrationGuide document.
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////
== About This Release

The latest version of this release is: {maven-version}.

You can see the {github-changelog-link} on GitHub.

Coming from an older Scout version? Check out the xref:migration:migration-guide.adoc[Migration Guide] for instructions on how to obtain the new version and upgrade existing applications.

WARNING: {NotReleasedWarning}

//The following enhancements were made after the initial {scout-version} release.
//
//==== 25.2.1
//
// The initial release of this version was *25.2.xyz*.
//
//WARNING: {NotReleasedWarning}
//
//(Section intentionally left blank for possible future release)
//
// * <<New Feature (since 25.2.xyz)>>
//
// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// WARNING: {NotReleasedWarning}
//
// * <<New Feature (since 25.2.xyz)>>

== Behavior Change of Scout JS Utilities objects.valueCopy, objects.equals And objects.equalsRecursive

In order to support the new class-based Data Objects, these functions had to be improved as follows:

* `Date`: is compared by its value (rather than the reference `===` as before) and copied by value (new instance is created).
* `Map`: is deeply compared by its content (rather than the reference `===` as before) and deeply copied.
* `Set`: is deeply compared by its content (rather than the reference `===` as before) and deeply copied.
* The function `objects.valueCopy` uses the function `clone` if existing to create deep clones (except for `Widgets`).
* The function `objects.equalsRecursive` uses the same equals logic as `objects.equals` which includes equality for empty arrays and the use of the `equals` functions of the objects, if available.
