////
Howto:
- Write this document such that it helps people to discover new features and other important changes of this release.
- Chronological order is not necessary.
- Describe necessary migration steps in the MigrationGuide document.
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////
== About This Release

The latest version of this release is: {maven-version}.

You can see the {github-changelog-link} on GitHub.

Coming from an older Scout version? Check out the xref:migration:migration-guide.adoc[Migration Guide] for instructions on how to obtain the new version and upgrade existing applications.

//The following enhancements were made after the initial {scout-version} release.
//
//==== 26.1.1
//
// The initial release of this version was *26.1.xyz*.
//
//(Section intentionally left blank for possible future release)
//
// * <<New Feature (since 26.1.xyz)>>
//
// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// * <<New Feature (since 26.1.xyz)>>

[[styles-css-class]]
== Utility to Modify CSS Classes (Scout JS)

The `styles` utility was extended with new methods to modify the `cssClass`-string of objects or check whether a css class is set or not.
These methods are:

* `addCssClass`: adds one or more css classes
* `removeCssClass`: removes one or more css classes
* `toggleCssClass`: toggles, i.e. adds or removes, one or more css classes depending on a condition
* `hasCssClass`: checks whether one or more css classes are set
* `cssClassAsArray`: splits a `cssClass`-string into an array of css classes

In addition, similar methods have been added to the `Cell` class to easier query and modify the `cssClass` property: `addCssClass`, `removeCssClass`, `toggleCssClass`, `hasCssClass`.

== Session API changes

As part of the move toward a stateless backend server, the API of the session has been changed. More info can be found in the xref:migration:migration-guide.adoc[Migration Guide].

== Adding Scout Classic Child Pages to a JsPage

The JsPage enables the use of pages implemented in Scout JS in a Scout Classic outline.
It can now use Scout Classic pages as its child pages.
The child pages are created by the Java implementation of the JsPage and triggered by its equivalent in Scout JS.
For more information see xref:howtos:scout-classic/js-page-how-to.adoc#how-to-js-page[How-To].

== User preferences moved from Shared to Client

As part of the move toward a stateless server session, `IPreferences`, `IUserPreferencesService`, `IUserPreferencesStorageService`, `IPreferenceChangeListener` and their corresponding implementations have been moved from shared to client.

== Simple tab box with vertical tabs

The `SimpleTabBox` has been improved.
The tabs can now be placed on all four sides of the box by adjusting the attribute `position` on the `SimpleTabArea` accordingly.
In particular, this allows the tabs to be aligned vertically.

[source,typescript,opts=novalidate]
----
scout.create(SimpleTabBox<SimpleTabView>, {
  parent: this,
  tabArea: {
    objectType: SimpleTabArea,
    position: SimpleTabArea.Position.LEFT
  }
});
----

== Widget: New Properties to Control Focus Behavior (Scout JS)

The following properties have been added to the Widget class and are therefore available for every widget.

- tabbable: controls whether the widget should be focusable using keyboard.
- preventClickFocus: set to true if the widget must not be focused when it is clicked.
- preventInitialFocus: set to true if the widget must not be considered as initial focus candidate, e.g. when opening a form.

[[search-outline]]
== SearchOutline (Scout JS and Scout Classic)

The `SearchOutline` now works for both Scout Classic and Scout JS pages.
Executing a search in Scout Classic is still done by overwriting `execSearch(String)`. In addition `execResetSearch()` may be overwritten to perform an action when the search is reset.

[source,java,opts=novalidate]
.Implementation of an `ISearchOutline`
----
public class SearchOutline extends AbstractSearchOutline {

  private MySearchPageWithTable m_mySearchPageWithTable;

  @Override
  protected void execCreateChildPages(List<IPage<?>> pageList) {
    m_mySearchPageWithTable = new MySearchPageWithTable();
    pageList.add(m_mySearchPageWithTable);
  }

  @Override
  public void execSearch(String query) {
    execResetSearch();
    super.execSearch(query);
    m_mySearchPageWithTable.search(query);
  }

  @Override
  protected void execResetSearch() {
    super.execResetSearch();
    m_mySearchPageWithTable.resetSearch();
  }
}
----

In order to update the search status of the outline automatically, the page needs to implement the interface `ISearchPage` and update its `ISearchState` whenever the result changes.

[source,java,opts=novalidate]
.Implementation of `ISearchPage`.
----
public class MySearchPageWithTable extends MyPageWithTable implements ISearchPage<Table> {

  private final LazyValue<ISearchState> m_searchState = new LazyValue<>(this::createSearchState);

  @Override
  public ISearchState getSearchState() {
    return m_searchState.get();
  }

  public void search(String query) {
    // execute search and update rows
    // ...

    getSearchState().setResultCount(getTable().getRowCount());
    getSearchState().setLimited(isLimitedResult());
    getSearchState().setPending(false);
  }

  public void resetSearch() {
    getTable().deleteAllRows();

    getSearchState().setResultCount(0);
    getSearchState().setLimited(false);
    getSearchState().setPending(false);
  }
}
----

Scout JS pages and xref:howtos:scout-classic/js-page-how-to.adoc#how-to-js-page[hybrid pages] simply create a `SearchState` and listen on the events `search` and `resetSearch` of the `SearchOutline`.

[source,typescript,opts=novalidate]
----
export class MySearchPageWithTable extends MyPageWithTable implements SearchPage {

  searchState: SearchState;

  protected _outlineSearchHandler = this._onOutlineSearch.bind(this);
  protected _outlineResetSearchHandler = this._onOutlineResetSearch.bind(this);

  protected override _init(model: InitModelOf<this>) {
    super._init(model);

    this.searchState = scout.create(SearchState, {parent: this.outline});

    this.outline.on('search', this._outlineSearchHandler);
    this.outline.on('resetSearch', this._outlineResetSearchHandler);
  }

  protected override _destroy() {
    this.outline.off('search', this._outlineSearchHandler);
    this.outline.off('resetSearch', this._outlineResetSearchHandler);

    this.searchState.destroy();
    this.searchState = null;

    super._destroy();
  }

  protected _onOutlineSearch(event: Event<SearchOutline>) {
    // execute search and update rows
    // ...

    this.searchState.setResultCount(this.detailTable.rows.length);
    this.searchState.setPending(false);
  }

  protected _onOutlineResetSearch(event: Event<SearchOutline>) {
    this.detailTable?.deleteAllRows();

    this.searchState.setResultCount(this.detailTable.rows.length);
    this.searchState.setPending(false);
  }

  protected _updateResultCount() {
    const resultCount = this.detailTable.rows.length;
    this.searchState.setResultCount(this.detailTable.rows.length);
  }
}
----
