////
Howto:
- Write this document such that it helps people to discover new features and other important changes of this release.
- Chronological order is not necessary.
- Describe necessary migration steps in the MigrationGuide document.
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////
== About This Release

The latest version of this release is: {maven-version}.

You can see the {github-changelog-link} on GitHub.

Coming from an older Scout version? Check out the xref:migration:migration-guide.adoc[Migration Guide] for instructions on how to obtain the new version and upgrade existing applications.

WARNING: {NotReleasedWarning}

//The following enhancements were made after the initial {scout-version} release.
//
//==== 24.2.1
//
// The initial release of this version was *24.2.xyz*.
//
//WARNING: {NotReleasedWarning}
//
//(Section intentionally left blank for possible future release)
//
// * <<New Feature (since 24.2.xyz)>>
//
// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// WARNING: {NotReleasedWarning}
//
// * <<New Feature (since 24.2.xyz)>>

== Demo Applications

The demo applications for this version can be found on the {scout-docs-link} branch of our docs repository on GitHub.

If you just want to play around with them without looking at the source code, you can always use the deployed versions:

* https://scout.bsi-software.com/contacts/
* https://scout.bsi-software.com/widgets/
* https://scout.bsi-software.com/jswidgets/

// ----------------------------------------------------------------------------

[[iid-signature]]
== IId signature

This release introduces a mechanism to add signatures to `IId` that are e.g. sent to the browser or provided by a REST endpoint.
For more information see xref:technical-guide:common-concepts/security.adoc#iid-signature[IId signature].

[[multiple-calendars]]
== Calendar Widget: Support for Multiple Calendars

The calendar widget is now capable of handling multiple calendar resources. In the left sidebar of the calendar appears a widget, which allows choosing the current visible resources.

By using a `CalendarResourceDo` object, new resources can be defined and added to the widget. These are the most important properties of the DataObject:

[%header,cols="1,1,3"]
|===
|Property name
|Type
|Description

|resourceId
|UUID (String)
|The unique identifier of a resource

|name
|String
|The display name of the resource

|parentId
|UUID (String)
|A resource can be a member of a resource group. If so, this property references the UUID of the resource group. A resource group is a normal `CalendarResourceDo` object.

|visible
|Boolean
|Indicates, if the resource is currently visible. This property changes when the user shows/hides the resource in the sidebar.

|selectable
|Boolean
|Indicates, if a range selection on this resource can be performed in the day view.
|===

A `CalendarResourceDo` can be added to the calendar by using `ICalendar#setResources` or `AbstractCalendar#getConfiguredResources`.

A calendar item can be assigned to a resource by referencing the resource by its ID using `ICalendarItem#setResourceId`.

When a CalendarItemProvider only produces items for one specific calendar, the method `AbstractCalendarItemProvider#getConfiguredAssociatedResource` can be overridden. All items produced by it are automatically assigned to the specified resource.

== Max Row Count and Limited Result for Scout JS Pages

Pages written in TypeScript now support a maximum row count and inform the user if there would be more data than allowed to fetch (limited result).
If you want to use this feature for your Scout JS pages as well, follow these instructions in the xref:migration:migration-guide.adoc#limitedResult[Migration Guide].

== Access Config Properties from Scout JS

Selected config properties can now be accessed from Scout JS.
See the xref:technical-guide:common-concepts/platform.adoc#access-config-ts[Configuration documentation] on how to expose more properties to the browser and how to access them from TypeScript.

