////
Howto:
- Write this document such that it helps people to discover new features and other important changes of this release.
- Chronological order is not necessary.
- Describe necessary migration steps in the MigrationGuide document.
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////
== About This Release

The latest version of this release is: {maven-version}.

You can see the {github-changelog-link} on GitHub.

Coming from an older Scout version? Check out the xref:migration:migration-guide.adoc[Migration Guide] for instructions on how to obtain the new version and upgrade existing applications.

WARNING: {NotReleasedWarning}

//The following enhancements were made after the initial {scout-version} release.
//
//==== 23.2.1
//
// The initial release of this version was *23.2.xyz*.
//
//WARNING: {NotReleasedWarning}
//
//(Section intentionally left blank for possible future release)
//
// * <<New Feature (since 23.2.xyz)>>
//
// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// WARNING: {NotReleasedWarning}
//
// * <<New Feature (since 23.2.xyz)>>

== Demo Applications

The demo applications for this version can be found on the {scout-docs-link} branch of our docs repository on GitHub.

If you just want to play around with them without looking at the source code, you can always use the deployed versions:

* https://scout.bsi-software.com/contacts/
* https://scout.bsi-software.com/widgets/
* https://scout.bsi-software.com/jswidgets/

// ----------------------------------------------------------------------------

== Group: CollapseStyle for CustomHeader

The `Group.CollapseStyle` property is now applied even if a custom header is used.
This means the collapse icon is rendered and can be used, but it is invisible by default, so it does not show up by accident on existing custom headers.
Just use CSS to make it visible if you need it.

== Scout JS

=== MenuTypes

==== Default menuTypes

Default menuTypes have been added to several widgets.
This means that e.g. the `Table` treats a menu without a menuType as if it had set `Table.MenuTypes.EmptySpace`.
For more information about the default menuTypes see xref:technical-guide:user-interface/widget-reference.adoc#menu-types[MenuTypes].


// ----------------------------------------------------------------------------

== Changes in Scout Classic

=== Health Check Servlet

The logic of executing health checks was extracted from `org.eclipse.scout.rt.server.commons.healthcheck.AbstractHealthCheckServlet` and moved to an own `org.eclipse.scout.rt.server.commons.healthcheck.HealthCheckService`.

The `AbstractHealthCheckServlet` is no longer abstract, was renamed to `HealthCheckServlet` and may be used without further individualization.

To update to the new servlet, the following changes in your `web.xml` are necessary:

* UI Server: Replace `org.eclipse.scout.rt.ui.html.admin.healthcheck.UiHealthCheckServlet` with `org.eclipse.scout.rt.server.commons.healthcheck.HealthCheckServlet` in your `web.xml`
* Backend Server: Replace `org.eclipse.scout.rt.server.admin.healthcheck.ServerHealthCheckServlet` with `org.eclipse.scout.rt.server.commons.healthcheck.HealthCheckServlet` in your `web.xml`
