////
Howto:
- Write this document such that it helps people to discover new features and other important changes of this release.
- Chronological order is not necessary.
- Describe necessary migration steps in the MigrationGuide document.
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////
== About This Release

The latest version of this release is: {maven-version}.

You can see the {github-changelog-link} on GitHub.

Coming from an older Scout version? Check out the xref:migration:migration-guide.adoc[Migration Guide] for instructions on how to obtain the new version and upgrade existing applications.

//The following enhancements were made after the initial {scout-version} release.
//
//==== 27.1.0
//
// The initial release of this version was *27.1.xyz*.
//
//(Section intentionally left blank for possible future release)
//
// * <<New Feature (since 27.1.xyz)>>
//
// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// * <<New Feature (since 27.1.xyz)>>

== Application-Scoped REST Resources

REST resources implementing `IRestResource` are now registered as application-scoped singletons and reused by Jersey/HK2 across requests instead of creating a new resource instance for every request.

This reduces object creation overhead and aligns the lifecycle of REST resources with other application-scoped Scout components. As resource instances are shared, REST resources should be implemented as stateless components.

[[batch-support]]
== Batch Support for Scout JS Columns

The support for batched value formatting for Columns has been improved.
Each subclass of `Column` can assign the new `_batchFormat` property to format values in a single batch call.
This improves performance on large tables.

For this a new `BatchCall` helper class has been added to collect the keys of the batch en perform the asynchronous calls.
Refer to the JsDoc of the class for details and a usage example.

The new batch support is used by default by the `SmartColumn` and the `LookupColumn`.
Furthermore, `StaticLookupCall` is batched now.
