////
Howto:
- Write this document such that it helps people to discover new features and other important changes of this release.
- Chronological order is not necessary.
- Describe necessary migration steps in the MigrationGuide document.
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////
== About This Release

The latest version of this release is: {maven-version}.

You can see the {github-changelog-link} on GitHub.

Coming from an older Scout version? Check out the xref:migration:migration-guide.adoc[Migration Guide] for instructions on how to obtain the new version and upgrade existing applications.

WARNING: {NotReleasedWarning}

//The following enhancements were made after the initial {scout-version} release.
//
//==== 26.1.1
//
// The initial release of this version was *26.1.xyz*.
//
//WARNING: {NotReleasedWarning}
//
//(Section intentionally left blank for possible future release)
//
// * <<New Feature (since 26.1.xyz)>>
//
// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// WARNING: {NotReleasedWarning}
//
// * <<New Feature (since 26.1.xyz)>>

[[styles-css-class]]
== Utility to Modify CSS Classes (Scout JS)

The `styles` utility was extended with new methods to modify the `cssClass`-string of objects or check whether a css class is set or not.
These methods are:

* `addCssClass`: adds one or more css classes
* `removeCssClass`: removes one or more css classes
* `toggleCssClass`: toggles, i.e. adds or removes, one or more css classes depending on a condition
* `hasCssClass`: checks whether one or more css classes are set
* `cssClassAsArray`: splits a `cssClass`-string into an array of css classes

In addition, similar methods have been added to the `Cell` class to easier query and modify the `cssClass` property: `addCssClass`, `removeCssClass`, `toggleCssClass`, `hasCssClass`.
