////
Howto:
- Write this document such that it helps people to discover new features and other important changes of this release.
- Chronological order is not necessary.
- Describe necessary migration steps in the MigrationGuide document.
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////
== About This Release

The latest version of this release is: {maven-version}.

You can see the {github-changelog-link} on GitHub.

Coming from an older Scout version? Check out the xref:migration:migration-guide.adoc[Migration Guide] for instructions on how to obtain the new version and upgrade existing applications.

WARNING: {NotReleasedWarning}

//The following enhancements were made after the initial {scout-version} release.
//
//==== 25.2.1
//
// The initial release of this version was *25.2.xyz*.
//
//WARNING: {NotReleasedWarning}
//
//(Section intentionally left blank for possible future release)
//
// * <<New Feature (since 25.2.xyz)>>
//
// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// WARNING: {NotReleasedWarning}
//
// * <<New Feature (since 25.2.xyz)>>

== New Build & Runtime Requirements

Scout 25.2 requires at least the following:

* Build and runtime of Scout 25.2 require Java 24 (Java 21 support has been dropped). We plan to update to Java 25 LTS as soon as it is available.

== New Data Object API for Scout JS

Scout JS now supports DataObjects to be written as classes in TypeScript.
A new serialization mechanisms takes care of recursively (de)serializing such DataObjects in a way compatible with the Scout Java backends.
It supports base types like `number`, `string`, `boolean`, but also more complex types like `Array`, `Date`, `Map`, `Set` or nested Data Objects.
Also, TypeScript specific types like `Record` or https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#literal-types[string literal types] are supported.

Please read the xref:technical-guide:working-with-data/data-object.adoc#DO-scoutjs[DO documentation for Scout JS] for more details and the advantages of the new API.
It is recommended to switch to the new API where ever possible by following the steps from the xref:migration:migration-guide.adoc#new-DO-api[migration guide].
An example implementation can be found in the xref:howtos:scout-js/rest-service-how-to.adoc[REST HowTo] which might be helpful to understand the new concepts.

== Behavior Change of Scout JS Utilities objects.valueCopy, objects.equals And objects.equalsRecursive

In order to support the new class-based Data Objects, these functions had to be improved as follows:

* `Date`: is compared by its value (rather than the reference `===` as before) and copied by value (new instance is created).
* `Map`: is deeply compared by its content (rather than the reference `===` as before) and deeply copied.
* `Set`: is deeply compared by its content (rather than the reference `===` as before) and deeply copied.
* The function `objects.valueCopy` uses the function `clone` if existing to create deep clones (except for `Widgets`).
* The function `objects.equalsRecursive` uses the same equals logic as `objects.equals` which includes equality for empty arrays and the use of the `equals` functions of the objects, if available.

[[iid-signature-tunnel-to-server]]
== IId signature

The mechanism that adds signatures to `IId` is now available for the service tunnel.
For more information see xref:technical-guide:common-concepts/security.adoc#id-signature-service-tunnel[IId signatures in service tunnel].

== Migration handler for deletion of data object contributions

The new `AbstractRemoveDoEntityContributionValueMigrationHandler` can be used when a data object contribution class is completely deleted. +
This migration handler will remove the contribution with the given type name and type version from the data objects.

== Table (Scout JS)

[[table-default-row-action]]
=== Default Row Action

The Scout JS `Table` has a new property `defaultRowAction` of type `Action`.
If set, this action is executed when a row is double-clicked.
Prior to the execution, a `rowAction` event is triggered.
When default is prevented on this event, the `defaultRowAction` is not executed.
The `defaultRowAction` can be used to execute a particular `Menu` of the `Table` on a row action.
It can be specified in the `TableModel` by referencing the id of the `Menu`.

[source,typescript,opts=novalidate]
----
defaultRowAction: 'MyMenu',
menus: [{
  id: 'MyMenu',
  objectType: Menu
}]
----

=== Column: Improved API

Some new methods have been added to easier get the cells and their values:
`cells()`, `cellValues()`, `selectedCells()`, `selectedCellValue()`, `selectedCellValues()`, `checkedCellValue()`, `checkedCellValues()`.

=== Move Table Row Menu Helper

If you need menus that move rows of a table up or down, you can use the new `MoveTableRowMenuHelper`.
The helper implements actions for the move menus and updates their states (enabled, visible) accordingly.

To use it, just create the helper and install it for your menus:

[source,typescript,opts=novalidate]
----
const moveRowHelper = scout.create(MoveTableRowMenuHelper);
moveRowHelper.install({table, moveRowUpMenu, moveRowDownMenu});
----

=== Search Form Table Control

The Scout JS table control `SearchFormTableControl` was added in order to add search forms to a `PageWithTable`.
The `PageWithTable` uses the data of the search form as its search filter each time the data is loaded
(see xref:howtos:scout-js/rest-service-how-to.adoc#page-with-table-search-form[Search Form] for more details).

== Slider

The `Slider` widget is now rendered using multiple `<div>` instead of the browser-native `<input type="range">`.
This allows for a more precise adjustment of the appearance.

The `SliderField` now also allows entering the desired value by hand.
It has two new properties:

* `valueEditable`: Whether there is a label or a number field to the right of the slider.
* `tabbable`: Makes this slider tabbable.
