////
Howto:
- Write this document such that it helps people to discover new features and other important changes of this release.
- Chronological order is not necessary.
- Describe necessary migration steps in the MigrationGuide document.
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////
== About This Release

The latest version of this release is: {maven-version}.

You can see the {github-changelog-link} on GitHub.

Coming from an older Scout version? Check out the xref:migration:migration-guide.adoc[Migration Guide] for instructions on how to obtain the new version and upgrade existing applications.

WARNING: {NotReleasedWarning}

//The following enhancements were made after the initial {scout-version} release.
//
//==== 24.1.1
//
// The initial release of this version was *24.1.xyz*.
//
//WARNING: {NotReleasedWarning}
//
//(Section intentionally left blank for possible future release)
//
// * <<New Feature (since 24.1.xyz)>>
//
// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// WARNING: {NotReleasedWarning}
//
// * <<New Feature (since 24.1.xyz)>>

== Demo Applications

The demo applications for this version can be found on the {scout-docs-link} branch of our docs repository on GitHub.

If you just want to play around with them without looking at the source code, you can always use the deployed versions:

* https://scout.bsi-software.com/contacts/
* https://scout.bsi-software.com/widgets/
* https://scout.bsi-software.com/jswidgets/

// ----------------------------------------------------------------------------

== New Build & Runtime Requirements

Scout 24.1 requires at least the following:

* The Java 11 support has been dropped. Build and runtime therefore require Java 17 now. Java 21 Support is planned for a future release.
* Furthermore, the build requires
** Maven >= 3.9.2
** Node 20 >= 20.10.0
** pnpm 8 >= 8.11.0

== HTTP/2 Support

Starting with release 24.1 the Scout https://eclipse.dev/jetty/[Jetty] server supports `HTTP/2` together with the already existing `HTTP/1.1`. It is enabled for `http` and `https` (https://en.wikipedia.org/wiki/Transport_Layer_Security[TLS]) access.
Please note that Browsers only use `HTTP/2` when using `https`.

When using `https` also https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation[ALPN] is supported which can upgrade an `HTTP/1.1` request to an `HTTP/2` request if the client supports it.

For Scout 24 and newer enabling `HTTP/2` for your application is recommended. Please refer to the xref:technical-guide:user-interface/browser-support.adoc[documentation] on how to enable `HTTP/2`.


== UI Notifications

It is now possible to push notifications from the backend directly to the UI running in the browser.
With JavaScript, you'll just subscribe for one or more topics and add a handler that should be called when a notification for that topic is published.
To publish a notification, just add any xref:technical-guide:working-with-data/data-object.adoc[Data Object] to the notification registry for a topic.

Learn more about the usage and functionality in the chapter xref:technical-guide:working-with-data/ui-notifications.adoc[UI Notifications].

== Apache HttpComponents Client 5.2.x

With Scout version 7 the usage of Apache HttpComponents Client was introduced (for example for communication between frontend and backend server). At that time version 4.5.3 was used which received only minor updates between releases (for major defects and security issues), version 24.1 of Scout upgrades the Apache HTTP Client to the next major version - now version 5.2.x is used.

Scout does not depend itself on an older Apache HttpComponents Client version anymore; however the new client version can be co-located with earlier major version on the same classpath as package names and maven coordinates have been changed.

This may result in changes if your project references (imports) Apache HttpComponents classes itself, e.g. `org.apache.http.HttpHeaders` has been moved to `org.apache.hc.core5.http.HttpHeaders`, `org.apache.http.impl.client.HttpClientBuilder` has been moved to `org.apache.hc.client5.http.impl.classic.HttpClientBuilder`, for further details the link:https://hc.apache.org/httpcomponents-client-5.2.x/migration-guide/index.html[Apache HttpClient 5.x migration guide] may be consulted (at the moment the classic API is still used to avoid too many changes).

Of course there is also behavior and API which has changed, the following behavioral changes have been noticed during development:

* `org.eclipse.scout.rt.shared.http.EnhancedLaxRedirectStrategy` is removed, this strategy previously enforced a second HTTP POST request for certain HTTP redirect status codes (e.g. 302 Found). According to link:https://www.rfc-editor.org/rfc/rfc9110.html#status.302[RFC 9110] in this case the POST request may be replaced with a GET request which the HttpClient will now respect. For redirects which require to re-send the POST request a different status code must be used (e.g. 307 Temporary Redirect). The config property `scout.http.redirectPost` has been removed.
* Internal test `org.eclipse.scout.rt.server.commons.http.HttpRetryTest.testPostWithUnsupportedRetryAndFailureWhileHeadersAreSent` has been removed as retry-strategy has been changed, requests failing with a `org.apache.hc.core5.http.ConnectionClosedException` while sending the request are not retried anymore in general, furthermore only idempotent requests will be retried by default. However, the Scout specific implementation to retry requests dealing with a stale socket channel is kept (regardless of the request method).

For third-party dependencies which refer to an older HttpClient version either both versions will co-exist (see above) or it is necessary to search for updated third-party versions which reference the new version of the HttpClient.

To use the new version with the Google HTTP Client library a `org.eclipse.scout.rt.shared.http.transport.ApacheHttpTransport` is introduced (as the third party library itself does not support the newer version yet as the library itself refers to an older HttpClient version this older version is explicitly excluded).

For `org.eclipse.scout.rt.server.commons.servlet.HttpProxy` the Google HTTP Client library is not used anymore, instead a new class `org.eclipse.scout.rt.shared.http.async.DefaultAsyncHttpClientManager` (configurable using a config property) is used. The new concept uses the HttpClient directly as async variant. `org.eclipse.scout.rt.shared.http.transport.ApacheHttpTransport` still uses the classic variant.

`org.eclipse.scout.rt.shared.http.BasicAuthHttpTransportManager` was removed, users may provide pre-emptive basic authentication using a custom `org.apache.hc.client5.http.protocol.HttpClientContext` for specific hosts (e.g for the `HttpProxy` using `org.eclipse.scout.rt.server.commons.servlet.HttpProxy.withHttpClientContextSupplier`).

== Accessibility

We are excited to announce the introduction of enhanced accessibility features in Scout.
This improves the overall user experience for individuals with diverse abilities, ensuring Scout applications are more inclusive and user-friendly.
Scout now includes comprehensive WAI-ARIA support to provide additional information to assistive technologies.
ARIA roles, properties, and states have been implemented to convey the purpose and state of most of Scout's widgets.
Very few complex widgets still lack a comprehensive WAI-ARIA support as these widgets require new concepts of interaction to be completely accessible.

To get familiar with Scouts new accessibility features we recommend using `aria.ts` as a starting point.

== Login form: Add support for second-factor (form-based)

For the `FormBasedAccessController` and the corresponding login box a basic second-factor support was added; a new credential verifier return value `org.eclipse.scout.rt.platform.security.ICredentialVerifier.AUTH_2FA_REQUIRED` was added which will prompt for a second factor token. To verify this token a second-factor verifier `ICredentialVerifier` needs to be registered.

During form-based login, for second-factor enabled accounts, a token is requested (after first challenge has been completed successful), for this token a new text `ui.Token` has been added to the login form and must be added to the `[...].ui.html/src/main/resources/WebContent/login.html`:

[source,html]
----
<scout:message style="tag" key="ui.Login" key="ui.LoginFailed" key="ui.User" key="ui.Password" key="ui.Token" />
----


