FROM tomcat:jre8
MAINTAINER BSI-Business-Systems-Integration-AG

ADD org.eclipse.scout.contacts.all.app.dev-9.0.0.011_Simrel_2019_06_M1.war /usr/local/tomcat/webapps/contacts.war

CMD ["catalina.sh", "run"]
