FROM tomcat:jre8
MAINTAINER BSI-Business-Systems-Integration-AG

ADD org.eclipse.scout.contacts.all.app.dev-9.0.0.006_Simrel_2019_03_M3.war /usr/local/tomcat/webapps/contacts.war

CMD ["catalina.sh", "run"]
