package org.eclipse.scout.contacts.shared.organization;

import javax.annotation.Generated;

import org.eclipse.scout.contacts.shared.template.AbstractLocationBoxData;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "org.eclipse.scout.contacts.client.organization.OrganizationSearchForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class OrganizationSearchFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public Homepage getHomepage() {
    return getFieldByClass(Homepage.class);
  }

  public Location getLocation() {
    return getFieldByClass(Location.class);
  }

  public Name getName() {
    return getFieldByClass(Name.class);
  }

  public static class Homepage extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Location extends AbstractLocationBoxData {

    private static final long serialVersionUID = 1L;
  }

  public static class Name extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
