/**
 * 
 */
package org.eclipsescout.contacts.shared.premium.ui.desktop.outlines;

import java.io.Serializable;

import javax.annotation.Generated;

import org.eclipse.scout.commons.annotations.Extends;
import org.eclipsescout.contacts.shared.ui.desktop.outlines.ContactsTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Extends(ContactsTablePageData.ContactsTableRowData.class)
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.pagedata.PageDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ContactsTableDataExtension implements Serializable {

  private static final long serialVersionUID = 1L;
  public static final String events = "events";
  private Long m_events;

  public ContactsTableDataExtension() {
  }

  /**
   * @return the Events
   */
  public Long getEvents() {
    return m_events;
  }

  /**
   * @param events
   *          the Events to set
   */
  public void setEvents(Long events) {
    m_events = events;
  }
}