
ifndef::finaldoc[]
include::_initDoc.adoc[]
endif::finaldoc[]

//fallback for safe mode == secure:
ifndef::imgsdir[:imgsdir: ../imgs]
ifndef::codedir[:codedir: ../../code]
ifndef::mdledir[:mdledir: .]
:experimental:

//-----------------------------------------------------------------------------
//Asciidoctor input file: "Copyright" used in the books
//
//WARNING: this file is a text module, it should be embedded in a master asciidoctor document.
//-----------------------------------------------------------------------------

[appendix]
[[apx-cclicence]]
== Licence and Copyright

This appendix first provides a summary of the Creative Commons (CC-BY) licence used for this book. 
The licence is followed by the complete list of the contributing individuals, and the full licence text.

=== Licence Summary

This work is licensed under the Creative Commons Attribution License.
To view a copy of this license, visit 
https://creativecommons.org/licenses/by/3.0/ or send a letter to
Creative Commons, 559 Nathan Abbott Way, Stanford, California 94305, USA.

A summary of the license is given below, followed by the full legal text.

You are free:

* **to Share** ---to copy, distribute and transmit the work
* **to Remix**---to adapt the work
* to make commercial use of the work

Under the following conditions:

**Attribution** ---You must attribute the work in the
manner specified by the author or licensor (but not in any way that
suggests that they endorse you or your use of the work).

With the understanding that: 

**Waiver** ---Any of the above conditions can be waived if
  you get permission from the copyright holder.

**Public Domain** ---Where the work or any of its
elements is in the public domain under applicable law, that status is
in no way affected by the license.

**Other Rights** ---In no way are any of the following
rights affected by the license:

* Your fair dealing or fair use rights, or other applicable copyright exceptions and limitations;
* The author's moral rights;
* Rights other persons may have either in the work itself or in how the work is used, such as publicity or privacy rights.


**Notice** ---For any reuse or distribution, you must make clear to
others the license terms of this work. The best way to do this is with
a link to https://creativecommons.org/licenses/by/3.0/.

[[sec-contributing_individuals]]
=== Contributing Individuals

Copyright (c) 2012-2014.

In the text below, all contributing individuals are listed in alphabetical order by name. 
For contributions in the form of GitHub pull requests, the name should match the one provided in the corresponding public profile.

include::{mdledir}/names.txt[]

=== Full Licence Text

The full licence text is available online at 
http://creativecommons.org/licenses/by/3.0/legalcode
