
ifndef::finaldoc[]
include::_initDoc.adoc[]
endif::finaldoc[]

//fallback for safe mode == secure:
ifndef::imgsdir[:imgsdir: ../imgs]
ifndef::codedir[:codedir: ../../code]
ifndef::mdledir[:mdledir: .]
:experimental:

//-----------------------------------------------------------------------------
//Asciidoctor input file: "Preface" used in the books
//
//WARNING: this file is a text module, it should be embedded in a master asciidoctor document.
//-----------------------------------------------------------------------------

:numbered!:
== Preface

The goal of this book is to get you familiar with the Scout framework in a short time.
Scout's core features and concepts are introduced and explained by writing actual Scout applications.
As Scout applications are written in Java, we make the assumption that you are familiar with the Java language and its core concepts.

We hope that this book helps you to get started quickly and would love to get your feedback.
This feedback is very valuable to us as it helps to improve both the book's content and the quality for all future readers.

To allow for contributions to this book, the technical setup and the book's licence have been selected to minimize restrictions.
According to the terms of the Creative Commons (CC-BY) license, you are allowed to freely use, share and adapt this book.
All source files of the book including the Scout projects described in the book are available on https://github.com/BSI-Business-Systems-Integration-AG/org.eclipse.scout.docs[Github].
