ifndef::finaldoc[]
include::_initDoc.adoc[]
endif::finaldoc[]

//fallback for safe mode == secure:
ifndef::imgsdir[:imgsdir: ../imgs]
ifndef::codedir[:codedir: ../../code]
ifndef::mdledir[:mdledir: .]
:experimental:

//-----------------------------------------------------------------------------
//WARNING: this file is a text module, it should be embedded in a master asciidoctor document.
//-----------------------------------------------------------------------------

As Eclipse has no JDK included, make sure you have a Java Development Kit (JDK) installed.
In case you need to download and install it, we recommend downloading an OpenJDK 11 (HotSpot) from https://adoptopenjdk.net/[adoptopenjdk.net].

Make sure the JDK installation is on the PATH. You can verify it by using your command line:

----
C:\> java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
----

Then download the `Eclipse IDE for Scout Developers` package for your platform by visiting the https://www.eclipse.org/downloads/packages[official Eclipse download page].
After the package selection, confirm the suggested mirror and extract the downloaded archive to your local disk.

Congratulations! You have successfully installed Eclipse for Scout development.
