/*
 * Copyright (c) 2010, 2024 BSI Business Systems Integration AG
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.scout.widgets.client.ui.forms;

import java.util.Date;
import java.util.Set;

import jakarta.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@ClassId("ef19288c-40fe-4f5e-a7a7-8526159c1cae-formdata")
@Generated(value = "org.eclipse.scout.widgets.client.ui.forms.SearchForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class SearchFormData extends AbstractFormData {
  private static final long serialVersionUID = 1L;

  public Boolean getBoolean() {
    return getFieldByClass(Boolean.class);
  }

  public DateFrom getDateFrom() {
    return getFieldByClass(DateFrom.class);
  }

  public DateTo getDateTo() {
    return getFieldByClass(DateTo.class);
  }

  public IntegerFrom getIntegerFrom() {
    return getFieldByClass(IntegerFrom.class);
  }

  public IntegerTo getIntegerTo() {
    return getFieldByClass(IntegerTo.class);
  }

  public LongFrom getLongFrom() {
    return getFieldByClass(LongFrom.class);
  }

  public LongTo getLongTo() {
    return getFieldByClass(LongTo.class);
  }

  public Smart getSmart() {
    return getFieldByClass(Smart.class);
  }

  public String getString() {
    return getFieldByClass(String.class);
  }

  @ClassId("c3b66216-1fab-4fe6-8faf-ff689b3f7722-formdata")
  public static class Boolean extends AbstractValueFieldData<java.lang.Boolean> {
    private static final long serialVersionUID = 1L;
  }

  @ClassId("cddff8f2-71ef-4ecf-8aec-a95c6ff4d37e-formdata")
  public static class DateFrom extends AbstractValueFieldData<Date> {
    private static final long serialVersionUID = 1L;
  }

  @ClassId("6426902a-ae05-4c97-bd91-ba6256c5d52c-formdata")
  public static class DateTo extends AbstractValueFieldData<Date> {
    private static final long serialVersionUID = 1L;
  }

  @ClassId("02ab6052-5b62-4c6b-907a-f71b2dfbc36d-formdata")
  public static class IntegerFrom extends AbstractValueFieldData<Integer> {
    private static final long serialVersionUID = 1L;
  }

  @ClassId("023b47c0-bde6-4df7-8e59-102171d256e8-formdata")
  public static class IntegerTo extends AbstractValueFieldData<Integer> {
    private static final long serialVersionUID = 1L;
  }

  @ClassId("dfddba95-6862-4c52-8740-eb4576f5d94c-formdata")
  public static class LongFrom extends AbstractValueFieldData<Long> {
    private static final long serialVersionUID = 1L;
  }

  @ClassId("818b0da9-b4ee-4973-8db0-dbd52e991bd1-formdata")
  public static class LongTo extends AbstractValueFieldData<Long> {
    private static final long serialVersionUID = 1L;
  }

  @ClassId("00839a31-351f-44fe-93b2-bbd1234db36d-formdata")
  public static class Smart extends AbstractValueFieldData<Set<Long>> {
    private static final long serialVersionUID = 1L;
  }

  @ClassId("ac28944e-b7d3-4b5b-a36a-11f7abeb93b1-formdata")
  public static class String extends AbstractValueFieldData<java.lang.String> {
    private static final long serialVersionUID = 1L;
  }
}
