:imgsdir: ../../imgs

////
- Use {NOTRELEASEDWARNING} on its own line to mark parts about not yet released code (also add a "since 7.1.xxx" note)
////

== About This Release

Eclipse Scout 7.1 is a preview version of the Eclipse _Photon_ release. It will be released in June 2018 (https://wiki.eclipse.org/Simultaneous_Release[release schedule]). The latest version of this release is: None released yet.

IMPORTANT: If you are upgrading from version 6.1, please also read the migration guide for the 7.0 (_Oxygen_) release: +
https://eclipsescout.github.io/7.0/migration-guide.html

* <<PLACEHOLDER>>

You can see the https://github.com/eclipse/scout.rt/compare/releases/7.0.x%2E%2E%2Ereleases/7.1.x[detailed change log] on GitHub.

=== Service Releases

The following changes were made after the initial 7.1 release (Eclipse Photon release). The following notes relate to a _service release_.

==== Photon.1 (7.1.100) Release expected on September, 2018

{NotReleasedWarning}


=== Obtaining the Latest Version

==== Runtime (Scout RT)
Scout RT artifacts are distributed via Maven:

* http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.eclipse.scout.rt%22%20AND%20v%3A%227.1.0.001_Photon%22[7.1.0.001_Photon] on _Maven Central_
* https://mvnrepository.com/artifact/org.eclipse.scout.rt/org.eclipse.scout.rt/7.1.0.001_Photon[7.1.0.001_Photon] on _mvnrepository.com_

Usage example in the parent POM of your Scout application:

[source,xml]
----
<dependency>
    <groupId>org.eclipse.scout.rt</groupId>
    <artifactId>org.eclipse.scout.rt</artifactId>
    <version>7.1.0.001_Photon</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

==== Eclipse IDE Tooling (Scout SDK)
You can download the complete Eclipse IDE with Scout SDK included (EPP) here: +
https://www.eclipse.org/downloads/packages/eclipse-scout-developers/Photon[Eclipse for Scout Developers]

To install the Scout SDK into your existing Eclipse IDE, use this update site: +
http://download.eclipse.org/scout/releases/7.1/7.1.0/001_Photon/

==== Demo Applications
The demo applications for this version can be found on the https://github.com/BSI-Business-Systems-Integration-AG/org.eclipse.scout.docs/tree/features/version/7.1.0.001_Photon[features/version/7.1.0.001_Photon] branch of our docs repository on GitHub.

If you just want to play around with them without looking at the source code, you can always use the deployed versions:

* https://scout.bsi-software.com/contacts/
* https://scout.bsi-software.com/widgets/
* https://scout.bsi-software.com/jswidgets/

// ----------------------------------------------------------------------------

// ----------------------------------------------------------------------------

== Java 8 required

The required Java Runtime Environment (JRE) to run an Eclipse Scout application has changed: Starting with Eclipse Scout _Photon_ (Scout 7.1 and newer), a Java 8 (or newer) runtime is required.

To reflect this change some existing Scout classes have been migrated to the newly available Java 8 classes:

`org.eclipse.scout.rt.platform.filter.IFilter` replaced with `java.util.function.Predicate`.

`org.eclipse.scout.rt.platform.filter.AlwaysFilter` replaced with `java.util.function.Predicate` e.g. `a -> true`.

`org.eclipse.scout.rt.platform.filter.NotFilter` replaced with `java.util.function.Predicate#negate`.

`org.eclipse.scout.rt.platform.filter.OrFilter` replaced with `java.util.function.Predicate#or`.

`org.eclipse.scout.rt.platform.util.concurrent.IConsumer` replaced with `java.util.function.Consumer`.

`org.eclipse.scout.rt.platform.util.concurrent.IFunction` replaced with `java.util.function.Function`.

`org.eclipse.scout.rt.platform.util.concurrent.IBiConsumer` replaced with `java.util.function.BiConsumer`.

`org.eclipse.scout.rt.platform.util.concurrent.IBiFunction` replaced with `java.util.function.BiFunction`.


== New SDK Feature in Eclipse: Search for missing NLS keys

If NLS keys are used in the code that do not exist in a properties file, an ugly placeholder is displayed to the user. To find such missing translations the new Menu `Scout -> Search missing text keys...` may be handy.
The result is listed in the Eclipse `Search` view.

The search also takes the scope of each NLS key into account. So that the key is considered to be available there must be a `TextProviderService` with that key on the classpath of that module.

Reported false positives can be suppressed using the following comment at the end of the corresponding line: `NO-NLS-CHECK`. Matches on that line are then not reported in future searches anymore.


== Config Properties
=== Descriptions
Config properties based on `org.eclipse.scout.rt.platform.config.IConfigProperty` include a description text. This description is stored in the new `description()` method.

The class `org.eclipse.scout.rt.platform.config.ConfigDescriptionExporter` can be used to export these descriptions. By default an AsciiDoctor exporter is included.

All Scout properties have been extended with descriptions. The same text is also part of the technical documentation.

=== Default value
Config properties based on `org.eclipse.scout.rt.platform.config.IConfigProperty` include a default value. The default value is stored in the `getDefaultValue()` method.

The method was moved  from `org.eclipse.scout.rt.platform.config.AbstractConfigProperty<DATA_TYPE, RAW_TYPE>` to the interface. Therefore the visibility has changed from protected to public.

=== Validation
The concreate implementation `org.eclipse.scout.rt.platform.config.ConfigPropertyValidator` which validates the configuration of `config.properties` files will also check if a configured value matches the default value.
In case it does a info message (warn in development mode) will be logged but platform will still start.
To minimize configuration files such entries should be removed from `config.properties` files.

== GroupBox enhancements
=== Layout Configuration
It is now possible to adjust the parameters of how the group box will be layouted. The following parameters may be set:

* hgap: the horizontal gap in pixels to use between two logical grid columns
* vgap: the vertical gap in pixels to use between two logical grid rows
* columnWidth: the width in pixels to use for a grid column
* rowHeight: the height in pixels to use for a grid row
* minWidth: the minimum width of the group box. If this width is > 0 a horizontal scrollbar is shown when the group box gets smaller than this value.

These values may be set using `getConfiguredBodyLayoutConfig`.
