
ifndef::finaldoc[]
include::../_initDoc.adoc[]
endif::finaldoc[]

//fallback for safe mode == secure:
:imgsdir: ../../imgs
:codedir: ../../../code
ifndef::mdledir[:mdledir: .]
:experimental:

//-----------------------------------------------------------------------------
// This file contains the release notes
//-----------------------------------------------------------------------------

//!!! not finished yet
Here are the release notes for the Scout Release 6.0

*TODO: a lot is still missing!*

== API Changes
* renamed `ITable.resetDisplayableColumns()` to `resetColumns()`
* removed `ITable.resetColumns(boolean, boolean, boolean, boolean)` from interface (is now protected in `AbstractTable`)
* AbstractAccessControlService is now generic with key as a type parameter, execLoadPermissions takes the key as parameter
* `AbstractTable.execResetTable(...)`: changed signature
** old: `protected void execResetColumns(boolean visibility, boolean order, boolean sorting, boolean widths)`
** new: `protected void execResetColumns(Set<String> options)`
* OutlineMenuWrapper: refactored constructors, for details consult the javadoc. This was needed to ensure the correct menuTypes throughout the wrapped menu's sub-hierarchy.
* Deleted AbstractCheckBox, AbstractCheckboxExtension, ICheckBoxExtension, ICheckBox. Use AbstractBooleanField, AbstractBooleanExtension, IBooleanExtension, IBooleanField instead.
* Deleted AbstractTextField, AbstractTextFieldExtension, ITextFieldExtension, ITextField. Use AbstractStringField, AbstractStringExtension, IStringExtension, IStringField instead.
