////
Howto:
- Write this document such that it helps people to discover new features and other important changes of this release.
- Chronological order is not necessary.
- Describe necessary migration steps in the MigrationGuide document.
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////

ifndef::finaldoc[]
include::../_initDoc.adoc[]
endif::finaldoc[]

== About This Release

The latest version of this release is: {maven-version}.

You can see the {github-changelog-link} on GitHub.

Coming from an older Scout version? Check out the {migration-guide-link} for instructions on how to obtain the new version and upgrade existing applications.

//The following enhancements were made after the initial {scout-version} release.
//
//==== 22.0.1
//
// The initial release of this version was *22.0.0.xyz* (Maven: 22.0.0.xyz_Simrel_2022_03).
//
//WARNING: {NotReleasedWarning}
//
//(Section intentionally left blank for possible future release)
//
// * <<New Feature (since 22.0.0.xyz)>>
//
// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// WARNING: {NotReleasedWarning}
//
// * <<New Feature (since 22.0.0.xyz)>>

== Demo Applications

The demo applications for this version can be found on the {scout-docs-link} branch of our docs repository on GitHub.

If you just want to play around with them without looking at the source code, you can always use the deployed versions:

* https://scout.bsi-software.com/contacts/
* https://scout.bsi-software.com/widgets/
* https://scout.bsi-software.com/jswidgets/

// ----------------------------------------------------------------------------

== New 3rd Party requirements

The Java 8 support has been dropped in Scout 22.
Therefore, only Java 11 is supported at the moment.
Support for Java 17 is planned for a future release.

Furthermore the minimal Maven version has been raised to 3.6.3.

See the migration guide for instructions on how to update.

Please note that Scout 22 makes use of the `Jakarta EE 8` artifacts.
These artifacts already use the new `jakarta.\*` Maven coordinates but still contain the old `javax.*` Java packages.
This ensures backwards compatibility with older `Java EE 8` containers.
The transition to `Jakarta EE 9.1` or newer is planned for a future release.

== Native Notification Support

It's now possible to send notifications via the https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API[Notification API].
The `DesktopNotification` has two new properties to control the behavior: *nativeOnly* and *nativeNotificationVisibility*.

// ----------------------------------------------------------------------------

== Text Post-Processors

A new bean *org.eclipse.scout.rt.platform.nls.ITextPostProcessor* has been introduced which allows to modify all texts returned by a TextProviderService.

This allows applying application wide logic on all translated texts including the ones provided by Scout itself.

// ----------------------------------------------------------------------------

== Browser Field: Support for Posting Messages

Browser fields provide a new method *postMessage(data, targetOrigin)* to send arbitrary data to the embedded web page.

To prevent malicious data from being sent to your application, the origin of the message should always be validated in the callback handler
(`execPostMessage` in Java, `message` event listener in Scout JS).
Scout will now do this check automatically for you if you configure the valid origins in the new property *trustedMessageOrigins*.

== Icon Support for Notifications

Notifications in GroupBoxes (`IGroupBox.setNotification()`) and desktop notifications (`IDesktop.addNotification`) now also support icons.

// ----------------------------------------------------------------------------

== REST LookupCall support for hierarchical data

Scout lookup calls may return hierarchically linked rows (parent-child relation).
The support for hierarchical lookup rows using REST lookup calls (e.g. the `parentId` attribute definition) was moved from `AbstractLookupRowDo` to the new class `AbstractHierarchicalLookupRowDo`.

In order to support hierarchical lookups using REST, change your lookup row implementation and extend the new base class `AbstractHierachicalLookupRowDo`.

[source,java]
.Example
----
@TypeName("ExampleLookupRow")
public class ExampleLookupRowDo extends AbstractHierarchicalLookupRowDo<MyLookupRowDo, ExampleId> {

  @Override
  public DoValue<ExampleId> id() {
    return createIdAttribute(this);
  }

  @Override
  public DoValue<ExampleId> parentId() {
    return createParentIdAttribute(this);
  }

  // ...
}
----




// ----------------------------------------------------------------------------
