:imgsdir: ../../imgs

////
- Use {NOTRELEASEDWARNING} on its own line to mark parts about not yet released code (also add a "since 7.1.xxx" note)
////

== About This Release

Eclipse Scout 7.1 is part of the Eclipse _Photon_ release. It was released in June 2018 (https://wiki.eclipse.org/Simultaneous_Release[release schedule]). The latest version of this release is _7.1.0.001_Photon_.

IMPORTANT: If you are upgrading from version 6.1, please also read the migration guide for the 7.0 (_Oxygen preview_) release: +
https://eclipsescout.github.io/7.0/migration-guide.html

* <<PLACEHOLDER>>

You can see the https://github.com/eclipse/scout.rt/compare/releases/7.0.x%2E%2E%2Ereleases/7.1.x[detailed change log] on GitHub.

=== Service Releases

The following changes were made after the initial 7.1 release (Eclipse Photon release). The following notes relate to a _service release_.

==== Photon.1 (7.1.100) Release expected on September, 2018

{NotReleasedWarning}


=== Obtaining the Latest Version

==== Runtime (Scout RT)
Scout RT artifacts are distributed via Maven:

* http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.eclipse.scout.rt%22%20AND%20v%3A%227.1.0.001_Photon%22[7.1.0.001_Photon] on _Maven Central_
* https://mvnrepository.com/artifact/org.eclipse.scout.rt/org.eclipse.scout.rt/7.1.0.001_Photon[7.1.0.001_Photon] on _mvnrepository.com_

Usage example in the parent POM of your Scout application:

[source,xml]
----
<dependency>
    <groupId>org.eclipse.scout.rt</groupId>
    <artifactId>org.eclipse.scout.rt</artifactId>
    <version>7.1.0.001_Photon</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

==== Eclipse IDE Tooling (Scout SDK)
You can download the complete Eclipse IDE with Scout SDK included (EPP) here: +
https://www.eclipse.org/downloads/packages/eclipse-scout-developers/Photon[Eclipse for Scout Developers]

To install the Scout SDK into your existing Eclipse IDE, use this update site: +
http://download.eclipse.org/scout/releases/7.1/7.1.0/001_Photon/

==== Demo Applications
The demo applications for this version can be found on the https://github.com/BSI-Business-Systems-Integration-AG/org.eclipse.scout.docs/tree/features/version/7.1.0.001_Photon[features/version/7.1.0.001_Photon] branch of our docs repository on GitHub.

If you just want to play around with them without looking at the source code, you can always use the deployed versions:

* https://scout.bsi-software.com/contacts/
* https://scout.bsi-software.com/widgets/
* https://scout.bsi-software.com/jswidgets/

// ----------------------------------------------------------------------------

// ----------------------------------------------------------------------------

N/A
