/*******************************************************************************
 * Copyright (c) 2015 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 ******************************************************************************/
package org.eclipse.scout.contacts.event.shared.contact;

import java.io.Serializable;

import javax.annotation.Generated;

import org.eclipse.scout.commons.annotations.Extends;
import org.eclipse.scout.contacts.shared.contact.ContactTablePageData.ContactTableRowData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Extends(ContactTableRowData.class)
@Generated(value = "org.eclipse.scout.contacts.event.client.contact.ContactTableExtension", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ContactTableDataExtension implements Serializable {

  private static final long serialVersionUID = 1L;
  public static final String events = "events";
  private Long m_events;

  public ContactTableDataExtension() {
  }

  public Long getEvents() {
    return m_events;
  }

  public void setEvents(Long events) {
    m_events = events;
  }
}
