/*******************************************************************************
 * Copyright (c) 2015 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.html
 * 
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 ******************************************************************************/
package org.eclipse.scout.tutorial.jaxws.shared.services.outline;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.pagedata.PageDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class WSLogTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  public WSLogTablePageData() {
  }

  @Override
  public WSLogTableRowData addRow() {
    return (WSLogTableRowData) super.addRow();
  }

  @Override
  public WSLogTableRowData addRow(int rowState) {
    return (WSLogTableRowData) super.addRow(rowState);
  }

  @Override
  public WSLogTableRowData createRow() {
    return new WSLogTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return WSLogTableRowData.class;
  }

  @Override
  public WSLogTableRowData[] getRows() {
    return (WSLogTableRowData[]) super.getRows();
  }

  @Override
  public WSLogTableRowData rowAt(int index) {
    return (WSLogTableRowData) super.rowAt(index);
  }

  public void setRows(WSLogTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class WSLogTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String wsLogNr = "wsLogNr";
    public static final String date = "date";
    public static final String service = "service";
    public static final String port = "port";
    public static final String operation = "operation";
    private Long m_wsLogNr;
    private String m_date;
    private String m_service;
    private String m_port;
    private String m_operation;

    public WSLogTableRowData() {
    }

    public Long getWsLogNr() {
      return m_wsLogNr;
    }

    public void setWsLogNr(Long wsLogNr) {
      m_wsLogNr = wsLogNr;
    }

    public String getDate() {
      return m_date;
    }

    public void setDate(String date) {
      m_date = date;
    }

    public String getService() {
      return m_service;
    }

    public void setService(String service) {
      m_service = service;
    }

    public String getPort() {
      return m_port;
    }

    public void setPort(String port) {
      m_port = port;
    }

    public String getOperation() {
      return m_operation;
    }

    public void setOperation(String operation) {
      m_operation = operation;
    }
  }
}