package org.eclipse.scout.docs.snippets.person;

import java.util.Set;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@ClassId("7d73104f-4982-4b7d-856f-ce133b70bb26-formdata")
@Generated(value = "org.eclipse.scout.docs.snippets.person.PersonForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PersonFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public LastBox getLastBox() {
    return getFieldByClass(LastBox.class);
  }

  public Name getName() {
    return getFieldByClass(Name.class);
  }

  @ClassId("d45e0930-b0aa-4bf9-8db5-4d54a9a44dc8-formdata")
  public static class LastBox extends AbstractValueFieldData<Set<Long>> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("eafb7554-6295-4ec4-a7d4-45211ecbd69f-formdata")
  public static class Name extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
