/*******************************************************************************
 * Copyright (c) 2015 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.html
 * 
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 ******************************************************************************/
package org.eclipse.scout.tutorial.jaxws.shared.services.process;

import java.util.Date;
import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class CompanyFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public CompanyFormData() {
  }

  public Change getChange() {
    return getFieldByClass(Change.class);
  }

  /**
   * access method for property CompanyNr.
   */
  public Long getCompanyNr() {
    return getCompanyNrProperty().getValue();
  }

  /**
   * access method for property CompanyNr.
   */
  public void setCompanyNr(Long companyNr) {
    getCompanyNrProperty().setValue(companyNr);
  }

  public CompanyNrProperty getCompanyNrProperty() {
    return getPropertyByClass(CompanyNrProperty.class);
  }

  public Name getName() {
    return getFieldByClass(Name.class);
  }

  public Symbol getSymbol() {
    return getFieldByClass(Symbol.class);
  }

  public TradeTime getTradeTime() {
    return getFieldByClass(TradeTime.class);
  }

  public ValueHigh getValueHigh() {
    return getFieldByClass(ValueHigh.class);
  }

  public ValueLast getValueLast() {
    return getFieldByClass(ValueLast.class);
  }

  public ValueLow getValueLow() {
    return getFieldByClass(ValueLow.class);
  }

  public ValueOpen getValueOpen() {
    return getFieldByClass(ValueOpen.class);
  }

  public Volume getVolume() {
    return getFieldByClass(Volume.class);
  }

  public static class Change extends AbstractValueFieldData<Double> {

    private static final long serialVersionUID = 1L;

    public Change() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_VALUE, Double.MAX_VALUE);
      ruleMap.put(ValidationRule.MIN_VALUE, -Double.MAX_VALUE);
    }
  }

  public static class CompanyNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;

    public CompanyNrProperty() {
    }
  }

  public static class Name extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Name() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class Symbol extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Symbol() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 5);
    }
  }

  public static class TradeTime extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;

    public TradeTime() {
    }
  }

  public static class ValueHigh extends AbstractValueFieldData<Double> {

    private static final long serialVersionUID = 1L;

    public ValueHigh() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_VALUE, Double.MAX_VALUE);
      ruleMap.put(ValidationRule.MIN_VALUE, -Double.MAX_VALUE);
    }
  }

  public static class ValueLast extends AbstractValueFieldData<Double> {

    private static final long serialVersionUID = 1L;

    public ValueLast() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_VALUE, Double.MAX_VALUE);
      ruleMap.put(ValidationRule.MIN_VALUE, -Double.MAX_VALUE);
    }
  }

  public static class ValueLow extends AbstractValueFieldData<Double> {

    private static final long serialVersionUID = 1L;

    public ValueLow() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_VALUE, Double.MAX_VALUE);
      ruleMap.put(ValidationRule.MIN_VALUE, -Double.MAX_VALUE);
    }
  }

  public static class ValueOpen extends AbstractValueFieldData<Double> {

    private static final long serialVersionUID = 1L;

    public ValueOpen() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_VALUE, Double.MAX_VALUE);
      ruleMap.put(ValidationRule.MIN_VALUE, -Double.MAX_VALUE);
    }
  }

  public static class Volume extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;

    public Volume() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_VALUE, Long.MAX_VALUE);
      ruleMap.put(ValidationRule.MIN_VALUE, Long.MIN_VALUE);
    }
  }
}
