////
Howto:
- Write this document such that it helps people to migrate. Describe what they should do.
- Chronological order is not necessary.
- Choose the right top level chapter (java, js, other)
////

== Migration Guide from Scout 6.1 to Scout 7.0

////
  =============================================================================
  === API CHANGES IN JAVA CODE ================================================
  =============================================================================
////

NOTE: If you upgrade from version 6.0, also see the migration guide for the 6.1 release. +
https://eclipsescout.github.io/6.1/migration-guide.html +

=== API Changes (Java)

==== New scout modules for Jackson-based REST services

The following new Scout modules were added to support Jackson-based REST services:

* `org.eclipse.scout.rt.rest`
* `org.eclipse.scout.rt.rest.test`
* `org.eclipse.scout.rt.jackson`
* `org.eclipse.scout.rt.jackson.test`

In order to use REST services based on the JAX-RS Jersey implementation, the following section must be added to the project `web.xml`:

[source,xml]
----
<!-- JAX-RS Jersey Servlet -->
<servlet>
  <servlet-name>api</servlet-name>
  <servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
  <init-param>
    <param-name>javax.ws.rs.Application</param-name>
    <param-value>org.eclipse.scout.rt.rest.RestApplication</param-value>
  </init-param>
  <load-on-startup>1</load-on-startup>
</servlet>
----

The `RestApplication` class searches for all implemenations of `IRestResource` and exposes them as REST services.

// ^^^
// Insert descriptions of Java API changes here

////
  =============================================================================
  === API CHANGES IN JAVA SCRIPT CODE =========================================
  =============================================================================
////

=== API Changes (JavaScript)

==== Promises
With jQuery 3 the promise API is now Promises/A+ compliant. This means you may need to adjust your code if you use promises.

We noticed the following effects:

- If a rejection is catched using a fail handler, the fail handler has
to return a rejected promise as well, otherwise the next success handler
would be called instead of the next fail handler.
- Every callback is now executed asynchronously. This is especially
relevant for the tests.
- Catch has been added -> replace fail(null, func) for better
readability.

See also https://jquery.com/upgrade-guide/3.0/ for details.

==== Removed addClassSVG, removeClassSVG, attrSVG, removeAttrSVG
These functions are now supported by jQuery directly. Just use `addClass`, `removeClass`, `attr` and `removeAttr`.

==== Property Change Event

The property change event has been simplified.

The event had 3 properties:
- newProperties
- oldProperties
- changedProperties

This was added to be able to react to multiple property change events at
once. Since 6.1, bulk property changes don't exist anymore, so there is
no need for these properties anymore.

Now, with 7.0, the property change event has the following properties:
- name
- oldValue
- newValue

This makes handling the event easier. Check your propertyChange event handlers and adjust them accordingly.

// ^^^
// Insert descriptions of JavaScript API changes here

////
  =============================================================================
  === OTHER IMPORTANT CHANGES REQUIRING MIGRATION =============================
  =============================================================================
////

=== Other Changes

==== Maven provided dependencies

In Maven dependencies with the scope provided are not transitive.
This makes sense if a dependency is set to provided depending on the environment.
Any artifacts that are not intended to be used in a certain environment should not have the scope provided and are therefore now transitive.
We removed any current dependency `javax.servlet:javax.servlet-api` except for the one in the artifact `org.eclipse.scout.rt.server.commons`.

To migrate your project, remove any dependency to `javax.servlet:javax.servlet-api`, `javax.xml.ws:jaxws-api` or `javax.ws.rs:javax.ws.rs-api`.
Then add to all artifacts with packaging type war the dependency to `javax.servlet:javax.servlet-api` with scope provided.
Depending on the container, you may want also to add the depdendency `javax.xml.ws:jaxws-api` with scope provided to the war artifact.

[source,xml]
----
<project>

  <artifactId>myproject.server.war</artifactId>
  <packaging>war</packaging>

  <dependencies>
    <dependency>
      <groupId>myproject</groupId>
      <artifactId>myproject.server</artifactId>
    </dependency>

    <!-- provided by container -->
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
----

#TODO#

// ^^^
// Insert descriptions of other important changes here
