
ifndef::finaldoc[]
include::../_initDoc.adoc[]
endif::finaldoc[]

//fallback for safe mode == secure:
:imgsdir: ../../imgs
:codedir: ../../../code
ifndef::mdledir[:mdledir: .]
:experimental:

//-----------------------------------------------------------------------------
// This file describes the scout migration from the previous version
//-----------------------------------------------------------------------------

//!!! not finished yet
This document describes the migration from Scout 5.0 to Scout 6.0

== Project Structure

With the upgrade to pure maven without OSGi the project structure should be changed to the maven default footnote:[
https://maven.apache.org/guides/getting-started/
]:


[source,text,indent=0]
.Eclipse Plugin Structure (Scout 5.0, old)
----
org.eclipsescout.helloworld.client
    pom.xml
    plugin.xml
    src
        org
            eclipsescout
                helloworld
                    ClientSession.java
                    Activator.java

org.eclipsescout.helloworld.test
    pom.xml
    plugin.xml
    src
        org
            eclipsescout
                helloworld
                    HelloworldTest.java
----

[source,text,indent=0]
.Maven Project Structure (Scout 6.0, new)
----
org.eclipsescout.helloworld.client
    pom.xml
    src
        main
            java
                org
                    eclipsescout
                        helloworld
                            ClientSession.java
                            Activator.java
        test
            java
                org
                    eclipsescout
                        helloworld
                        HelloworldTest.java
----

== Manifest.MF

Manifest.MF is no longer used. Migrate dependencies to `pom.xml`!


== Logging

Scout switched from a custom, typically java.util.logging-based logger implementation to SLF4j. The log format does not support indexed placeholders anymore.

The regular expression pattern `\{\d+\}` finds potential occurrences. Replace those within log formats with `{}`. See http://www.slf4j.org/api/org/slf4j/helpers/MessageFormatter.html[SLF4j MessageFormatter].

[source,java,indent=0]
.Placeholders in log format
----
LOG.info("message {}", obj); // this worked before and still works. No action required

LOG.info("message {0}", obj); // the index is not supported anymore. You have to remove it (see previous statement)
----

NOTE: Indexed placeholders are actually deprecated since Scout's open-source debut. The values were filled in from left to right, independent of the possibly declared index.

== AccessControlService

The IAccessControlService has been improved to allow for other keys than the userId. AbstractAccessControlService is now generic with key as a type parameter.

If you want to use access control based on the userid as before, extend UserIdAccessControlService and change the API of execLoadPermissions to
[source,java,indent=0]
----
protected abstract PermissionCollection execLoadPermissions(String userId)
----

== Offline
Offline functionality in the scout client was removed (not needed anymore). Delete
- OfflineState
- IClientSession.getOfflineSubject
- IDesktop.changeVisibilityAfterOfflineSwitch

== Moves
The following Classes were moved. Organize imports to fix errors:

- IDNDSupport
- TransferObject
- TextTransferObject
- ResourceListTransferObject
- JavaTransferObject
- ImageTransferObject


== Logging

migrate logging.properties to logback.xml

1) in logging.properties applay the following regex
search: ^(\w.*)\.level\s*=\s*(ALL|OFF|SEVERE|WARNING|INFO|FINE|FINEST)\s*$
replace: <logger name="$1" level="$2"/>

search: ^(\w.*)\.useParentHandlers\s*=\s*(false)\s*$
replace: <logger name="$1"><appender-ref ref="CONSOLE"/></logger>

search: ^#+\s*(.*)$
replace: <!-- $1 -->

search: (FINEST|finest)
replace: TRACE

search: (FINE|fine)
replace: DEBUG

search: (WARNING|warning)
replace: WARN

search: (SEVERE|severe)
replace: ERROR


2) create a new logback.xml as

<?xml version="1.0" encoding="UTF-8" ?>
<configuration>

  <appender name="CONSOLE"
    class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg %n</pattern>
    </encoder>
  </appender>

  <root level="INFO">
    <appender-ref ref="CONSOLE" />
  </root>

  <!-- (3) -->

</configuration>


3) include the converted content of logging.properties at (3)


4) adjust the format pattern if needed
available variables are
%d{HH:mm:ss.SSS}
%thread
%-5level
%logger{36}
%msg
%n
%X{scout.ui.session.id}
%X{scout.session.id}
%X{http.request.method}
%X{http.request.uri}
%X{http.session.id}
%X{scout.user.name}
%X{subject.principal.name}

Default ui.html pattern
      <pattern>%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg [%X{subject.principal.name} @ %X{http.request.method} %X{http.request.uri} %X{scout.ui.session.id}]%n</pattern>
Default server pattern
      <pattern>%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg [%X{subject.principal.name} @ %X{http.session.id} in %thread ]%n</pattern>



