////
Howto:
- Write this document such that it helps people to migrate. Describe what they should do.
- Chronological order is not necessary.
- Choose the right top level chapter (java, js, other)
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////

ifndef::finaldoc[]
include::../_initDoc.adoc[]
endif::finaldoc[]

// double underscore
:dus: __

== About This Document

This document describes all relevant changes *from Eclipse Scout {scout-previous-version} to Eclipse Scout {scout-version}*. If existing code has to be migrated, instructions are provided here.

== Obtaining the Latest Version

=== Scout Runtime for Java
Scout Runtime artifacts for Java are distributed using Maven Central:

* {maven-central-link} on _Maven Central_
* {mvnrepository-link} on _mvnrepository.com_

Usage example in the parent POM of your Scout application:

[source,xml]
[subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.eclipse.scout.rt</groupId>
    <artifactId>org.eclipse.scout.rt</artifactId>
    <version>{maven-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

=== Scout Runtime for JavaScript

Scout Runtime artifacts for JavaScript are distributed using npm:

* https://www.npmjs.com/package/@eclipse-scout/core[Scout Core Runtime]
* https://www.npmjs.com/search?q=%40eclipse-scout[All official Scout JavaScript packages]

Usage example in your package.json:
[source,json]
[subs="verbatim,attributes"]
----
{
  "name": "my-module",
  "version": "1.0.0",
  "dependencies": {
    "@eclipse-scout/core": "{node-version}",
    "jquery": "3.5.1"
  }
}
----

The pre-built Scout JavaScript assets are also available using a CDN (e.g. to be directly included in a html document):
https://www.jsdelivr.com/package/npm/@eclipse-scout/core?path=dist


=== IDE Tooling (Scout SDK)

Starting with Scout 11 the IDE Tooling requires at least Java 11 to run.
With the help of the SDK plugins you can still develop applications running with Java 8, but the IDE itself requires Java 11 or newer.

Scout officially supports https://www.jetbrains.com/idea/[IntelliJ IDEA] and {scout-sdk-download-link}.

==== IntelliJ IDEA

You can download the Scout plugin for IntelliJ IDEA from the https://plugins.jetbrains.com/plugin/13393-eclipse-scout/[JetBrains Plugin Repository] or you can use the plugins client built into IntelliJ IDEA.
Please refer to the https://www.jetbrains.com/help/idea/managing-plugins.html[IntelliJ Help] on how to install and manage plugins.

==== Eclipse

You can download the complete Eclipse IDE with Scout SDK included here: +
{scout-sdk-download-link}

To install the Scout SDK into your existing Eclipse IDE, use this P2 update site: +
{scout-sdk-update-site}

== TypeVersion Annotation Type Change

The type version of a data object is used to identify a certain structure version of the stored data object.
A data object may be stored in a database or be available as a container to export certain data for import in a different compatible system.
Such a data object may evolve over time and undergo structural changes.
Some structural changes make it necessary to apply migrations to existing serialized data objects to comply with the new structure.

In order to prepare for migration support, the type version annotation so far containing a String value changes to a value of Class<? extends ITypeVersion>.
A ITypeVersion represents a namespace/version and it's dependencies.

*Migration*

For each different String value used in type version annotation, create an implementation of `ITypeVersion` as described
in _Data Objects_/_Namespace and ITypeVersion_ in the technical documentation.

`DataObjectInventory#getTypeVersion` returns `NamespaceVersion` instead of `String`.
Use `NamespaceVersion::unwrap` to access text representation.

== Annotation EnumVersion removed

`EnumVersion` was designed for migration support similar as the TypeVersion but was never part of any serialization output of a data object,
therefore couldn't be used as indicator for migrations.
Support for `EnumVersion` is removed.

*Migration*

Remove `EnumVersion` annotation on `IEnum` implementors.

== Native Notification Support

The new notifications displayed by the browser use the application logo configured in `AbstractDesktop#getConfiguredLogoId()`.

*Migration*
If you use native notifications, provide an application logo with a resolution of at least 150x150 px.

== Less Variables

- @navigation-background-color -> @desktop-navigation-background-color
- @navigation-color -> @desktop-navigation-color
- @outline-title-margin-left/right -> @outline-title-padding-left/right

Notes:
@desktop-navigation-background-color now points to @desktop-header-background-color;
Instead of customizing the navigation background color it is suggested to now customize the header background color.