
ifndef::finaldoc[]
include::../_initDoc.adoc[]
endif::finaldoc[]

//fallback for safe mode == secure:
:imgsdir: ../../imgs
:codedir: ../../../code
ifndef::mdledir[:mdledir: .]
:experimental:

//-----------------------------------------------------------------------------
// This file describes the scout migration from the previous version
//-----------------------------------------------------------------------------

//!!! not finished yet
This document describes the migration from Scout 5.0 to Scout 6.0

== Project Structure

With the upgrade to pure maven without OSGi the project structure should be changed to the maven default footnote:[
https://maven.apache.org/guides/getting-started/
]:


[source,text,indent=0]
.Eclipse Plugin Structure (Scout 5.0, old)
----
org.eclipsescout.helloworld.client
    pom.xml
    plugin.xml
    src
        org
            eclipsescout
                helloworld
                    ClientSession.java
                    Activator.java

org.eclipsescout.helloworld.test
    pom.xml
    plugin.xml
    src
        org
            eclipsescout
                helloworld
                    HelloworldTest.java
----

[source,text,indent=0]
.Maven Project Structure (Scout 6.0, new)
----
org.eclipsescout.helloworld.client
    pom.xml
    src
        main
            java
                org
                    eclipsescout
                        helloworld
                            ClientSession.java
                            Activator.java
        test
            java
                org
                    eclipsescout
                        helloworld
                        HelloworldTest.java
----

== Manifest.MF

Manifest.MF is no longer used. Migrate dependencies to `pom.xml`!


== Logging

Scout switched from a custom, typically java.util.logging-based logger implementation to SLF4j. The log format does not support indexed placeholders anymore.

The regular expression pattern `\{\d+\}` finds potential occurrences. Replace those within log formats with `{}`. See http://www.slf4j.org/api/org/slf4j/helpers/MessageFormatter.html[SLF4j MessageFormatter].

[source,java,indent=0]
.Placeholders in log format
----
LOG.info("message {}", obj); // this worked before and still works. No action required

LOG.info("message {0}", obj); // the index is not supported anymore. You have to remove it (see previous statement)
----

NOTE: Indexed placeholders are actually deprecated since Scout's open-source debut. The values were filled in from left to right, independent of the possibly declared index.

== AccessControlService

The IAccessControlService has been improved to allow for other keys than the userId. AbstractAccessControlService is now generic with key as a type parameter.

If you want to use access control based on the userid as before, extend UserIdAccessControlService and change the API of execLoadPermissions to
[source,java,indent=0]
----
protected abstract PermissionCollection execLoadPermissions(String userId)
----


