////
Howto:
- Write this document such that it helps people to migrate. Describe what they should do.
- Chronological order is not necessary.
- Choose the right top level chapter (java, js, other)
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////

== About This Document

This document describes all relevant changes *from Eclipse Scout 9.0 to Eclipse Scout 10.0*. If existing code has to be migrated, instructions are provided here.

=== Service Releases

Scout 10.0 will continue to be maintained for a while and a new build may be released from time to time, following the https://wiki.eclipse.org/SimRel/Simultaneous_Release_Cycle_FAQ#What_is_the_Simultaneous_Release_cycle_.3F[Simultaneous Release Cycle]. Beside bugfixes, these service releases may even contain some minor features.

The following changes were made after the initial 10.0 release.

==== Simrel 2020-03 -- TBD

WARNING: {NotReleasedWarning}

// * <<Migration Description (since 10.0.0.xyz)>>

// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// WARNING: {NotReleasedWarning}
//
// * <<Migration Description (since 10.0.0.xyz)>>

////
  =============================================================================
  === API CHANGES IN JAVA CODE ================================================
  =============================================================================
////

== API Changes (Java)

=== StrictSimpleDateFormat
`org.eclipse.scout.rt.jackson.dataobject.StrictSimpleDateFormat` was removed. Use `org.eclipse.scout.rt.platform.util.date.StrictSimpleDateFormat` instead.

=== ObjectUtility
`nvlOptional()` was renamed to `nvlOpt()`.

=== Data Objects
The Scout data object support was moved from the Scout platform to the module `org.eclipse.scout.rt.dataobject`.
The package imports of all data object related classes therefore changed:
From `org.eclipse.scout.rt.platform.dataobject` to `org.eclipse.scout.rt.dataobject`

==== Renamings
`org.eclipse.scout.rt.client.ui.desktop.datachange.DoChangeEvent` -> `org.eclipse.scout.rt.client.ui.desktop.datachange.ItemDataChangeEvent`

==== Dependencies
All modules which use data objects were extended with a dependency to `org.eclipse.scout.rt.dataobject`

* `org.eclipse.scout.rt.rest`
* `org.eclipse.scout.rt.mom.api`

==== Renamings in ErrorDo
* `org.eclipse.scout.rt.rest.error.ErrorDo#status` -> `org.eclipse.scout.rt.rest.error.ErrorDo#httpStatus`
* `org.eclipse.scout.rt.rest.error.ErrorDo#code` -> `org.eclipse.scout.rt.rest.error.ErrorDo#errorCode`

=== CacheBuilder
The following methods on `CacheBuilder` where removed, since they were unused and covered unused, old functionality:

* Method `org.eclipse.scout.rt.shared.cache.CacheBuilder.addCacheInstance(ICache<K, V>)`
* Method `org.eclipse.scout.rt.shared.cache.CacheBuilder.getCacheInstances()`

=== Move ICache and transactional Map
`AbstractTransactionalMap` and its concrete implementations `ConcurrentTransactionalMap` and `CopyOnWriteTransactionalMap` have been moved to `org.eclipse.scout.rt.platform.util.collection`.

`ICache`, its implementations and cache wrappers have been moved to  `org.eclipse.scout.rt.platform.cache`.




// ^^^
// Insert descriptions of Java API changes here

////
  =============================================================================
  === API CHANGES IN JAVA SCRIPT CODE =========================================
  =============================================================================
////

== API Changes (JavaScript)


// ^^^
// Insert descriptions of other important changes here

== REST Service Changes

Any changes which may change how REST consumer or provider behave.

=== Renamings in ErrorDo
`org.eclipse.scout.rt.rest.error.ErrorDo` used by `org.eclipse.scout.rt.rest.client.proxy.ErrorDoRestClientExceptionTransformer` and some `org.eclipse.scout.rt.rest.exception.AbstractExceptionMapper<E>` was slightly changed:

* `ErrorDo#status` -> `ErrorDo#httpStatus`
* `ErrorDo#code` -> `ErrorDo#errorCode`

=== Different HTTP status codes

A REST service client using `ErrorDoRestClientExceptionTransformer` will now transform

* any client request error (HTTP `4xx` status codes) into a `VetoException`
* `403 - Forbidden` into a `org.eclipse.scout.rt.dataobject.exception.AccessForbiddenException`
* `404 - Not Found` into a `org.eclipse.scout.rt.dataobject.exception.ResourceNotFoundException`

The `org.eclipse.scout.rt.rest.exception.VetoExceptionMapper` used by a REST service provide will now create an error response with status `400 - Bad Request` (this was formerly a `403`).

