////
Howto:
- Write this document such that it helps people to migrate. Describe what they should do.
- Chronological order is not necessary.
- Choose the right top level chapter (java, js, other)
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////

== About This Document

This document describes all relevant changes *from Eclipse Scout 10.0 to Eclipse Scout 11.0*. If existing code has to be migrated, instructions are provided here.

=== Service Releases

Scout 11.0 will continue to be maintained for a while and new builds may be released from time to time.
Beside bugfixes, these service releases may even contain some minor features.


//The following enhancements were made after the initial 11.0 release.
//
//==== 11.0.1
//
// The initial release of this version was *11.0.0.xyz* (Maven: 11.0.0.xyz_Simrel_2019_06).
//
//WARNING: {NotReleasedWarning}
//
//(Section intentionally left blank for possible future release)
//
// * <<New Feature (since 11.0.0.xyz)>>
//
// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// WARNING: {NotReleasedWarning}
//
// * <<New Feature (since 11.0.0.xyz)>>


////
  =============================================================================
  === API CHANGES IN JAVA CODE ================================================
  =============================================================================
////
// == API Changes (Java)

// === First Change

////
  =============================================================================
  === API CHANGES IN JAVA SCRIPT CODE =========================================
  =============================================================================
////

// == API Changes (JavaScript)

// =)= First Change

////
  =============================================================================
  === OTHER CHANGES ===========================================================
  =============================================================================
////

== Updated 3rd party dependencies

All 3rd party build- and runtime-dependencies have been updated to the latest versions. This requires the following modifications:

If you are using the `jaxws-maven-plugin`, please change the groupId in your pom.xml files from `com.helger.maven` to `com.sun.xml.ws`.

In all your `web.xml` files update the `web-app` xml document element to:

[source,xml]
[subs="verbatim,attributes"]
----
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee
                      http://xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd"
  version="4.0"
  metadata-complete="true">
...
</web-app>
----

If you have Jax-Ws web service providers (this is the case if you use the `org.eclipse.scout.rt.server.jaxws.provider.annotation.WebServiceEntryPoint` annotation), the classpath of the annotation processor must be updated as described for each IDE:

For Eclipse Developers: Update the content of all `.factorypath` files as follows:

[source,xml]
[subs="verbatim,attributes"]
----
<factorypath>
<factorypathentry kind="VARJAR" id="M2_REPO/org/eclipse/scout/rt/org.eclipse.scout.jaxws.apt/11.0-SNAPSHOT/org.eclipse.scout.jaxws.apt-11.0-SNAPSHOT.jar" enabled="true" runInBatchMode="false"/>
<factorypathentry kind="VARJAR" id="M2_REPO/org/glassfish/jaxb/codemodel/2.3.3/codemodel-2.3.3.jar" enabled="true" runInBatchMode="false"/>
<factorypathentry kind="VARJAR" id="M2_REPO/org/eclipse/scout/rt/org.eclipse.scout.rt.platform/11.0-SNAPSHOT/org.eclipse.scout.rt.platform-11.0-SNAPSHOT.jar" enabled="true" runInBatchMode="false"/>
<factorypathentry kind="VARJAR" id="M2_REPO/org/eclipse/scout/rt/org.eclipse.scout.rt.server.jaxws/11.0-SNAPSHOT/org.eclipse.scout.rt.server.jaxws-11.0-SNAPSHOT.jar" enabled="true" runInBatchMode="false"/>
<factorypathentry kind="VARJAR" id="M2_REPO/jakarta/servlet/jakarta.servlet-api/4.0.4/jakarta.servlet-api-4.0.4.jar" enabled="true" runInBatchMode="false"/>
<factorypathentry kind="VARJAR" id="M2_REPO/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar" enabled="true" runInBatchMode="false"/>
<factorypathentry kind="VARJAR" id="M2_REPO/jakarta/jws/jakarta.jws-api/2.1.0/jakarta.jws-api-2.1.0.jar" enabled="true" runInBatchMode="false"/>
<factorypathentry kind="VARJAR" id="M2_REPO/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar" enabled="true" runInBatchMode="false"/>
<factorypathentry kind="VARJAR" id="M2_REPO/jakarta/xml/ws/jakarta.xml.ws-api/2.3.3/jakarta.xml.ws-api-2.3.3.jar" enabled="true" runInBatchMode="false"/>
</factorypath>
----

For IntelliJ IDEA Developers: Update the content of the element `<annotationProcessing>` in the file `.idea/compiler.xml` as follows (replace profile name and module names accordingly):

[source,xml]
[subs="verbatim,attributes"]
----
<profile name="<your_name>" enabled="true">
  <sourceOutputDir name="target/generated-sources/annotations" />
  <sourceTestOutputDir name="target/generated-test-sources/test-annotations" />
  <outputRelativeToContentRoot value="true" />
  <option name="consoleLog" value="true" />
  <processorPath useClasspath="false">
    <entry name="$MAVEN_REPOSITORY$/org/eclipse/scout/rt/org.eclipse.scout.jaxws.apt/11.0-SNAPSHOT/org.eclipse.scout.jaxws.apt-11.0-SNAPSHOT.jar" />
    <entry name="$MAVEN_REPOSITORY$/org/glassfish/jaxb/codemodel/2.3.3/codemodel-2.3.3.jar" />
    <entry name="$MAVEN_REPOSITORY$/org/eclipse/scout/rt/org.eclipse.scout.rt.platform/11.0-SNAPSHOT/org.eclipse.scout.rt.platform-11.0-SNAPSHOT.jar" />
    <entry name="$MAVEN_REPOSITORY$/org/eclipse/scout/rt/org.eclipse.scout.rt.server.jaxws/11.0-SNAPSHOT/org.eclipse.scout.rt.server.jaxws-11.0-SNAPSHOT.jar" />
    <entry name="$MAVEN_REPOSITORY$/jakarta/servlet/jakarta.servlet-api/4.0.4/jakarta.servlet-api-4.0.4.jar" />
    <entry name="$MAVEN_REPOSITORY$/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar" />
    <entry name="$MAVEN_REPOSITORY$/jakarta/jws/jakarta.jws-api/2.1.0/jakarta.jws-api-2.1.0.jar" />
    <entry name="$MAVEN_REPOSITORY$/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar" />
    <entry name="$MAVEN_REPOSITORY$/jakarta/xml/ws/jakarta.xml.ws-api/2.3.3/jakarta.xml.ws-api-2.3.3.jar" />
  </processorPath>
  <module name="<your_first_module_having_jaxws_providers>" />
  <module name="<your_second_module_having_jaxws_providers>" />
  ...
</profile>
----

== New ESLint Settings

The eslint rules used by Scout have been adjusted.
So if you have a dependency to `@eclipse-scout/eslint-config` and you update to the latest version,
your JavaScript code may report some new warnings.

The following rules have been turned on:
`no-var`, `prefer-arrow-callback`,`prefer-rest-params`, `prefer-spread`.

If you don't like the warnings, you can adjust your `eslintrc.js` and disable the rules.
But we suggest migrating your code because it really benefits from using these new ES6 features.

Luckily, eslint provides an automatic fix for the first two.
Just run the following command in the root of your project:

 node_modules/.bin/eslint . --fix

You may also need to ignore some files or folders first, just add them to the `.eslintignore` file.

`prefer-rest-params` and `prefer-spread` need a manual migration, unless you choose to disable them.
