////
Howto:
- Write this document such that it helps people to migrate. Describe what they should do.
- Chronological order is not necessary.
- Choose the right top level chapter (java, js, other)
- Use {NOTRELEASEDWARNING} on its own line to mark parts about not yet released code (also add a "since 7.1.xxx" note)
////

== About This Document

This document describes all relevant changes *from Eclipse Scout 7.0 to Eclipse Scout 7.1*. If existing code has to be migrated, instructions are provided here.

IMPORTANT: If you are upgrading from version 6.1, please also read the migration guide for the 7.0 (_Oxygen preview_) release: +
https://eclipsescout.github.io/7.0/migration-guide.html

* <<Removed property `focusable` from IFormField, AbstractFormField>>

=== Service Release Migration

The following changes were made after the initial 7.1 release (Eclipse Photon release). Additionally follow these instructions when updating to a _service release_.

==== Photon.1 (7.1.100) Release expected on September, 2018

{NotReleasedWarning}


////
  =============================================================================
  === API CHANGES IN JAVA CODE ================================================
  =============================================================================
////

== API Changes (Java)

== Removed property `focusable` from IFormField, AbstractFormField
Since the new Html UI was introduced with Scout 5.2 this property had no effect on the UI anymore. Instead the UI uses sensible defaults for each field type. For instance: a LabelField is never focusable, a normal StringField is always focusable, as long as it is enabled. Since the property was rarely used, we removed all methods from the interface/class FormField. Removed methods/properties:

* boolean IFormField#isFocusable()
* void IFormField#setFocusable(boolean f)
* boolean IFormField#PROP_FOCUSABLE
* boolean AbstractFormField#getConfiguredFocusable()
* class AbstractNonFocusableButton
* class AbstractNonFocusableRadioButton

Since there is no replacement for the focusable property, remove all code that uses one of the methods/properties listed above.

== ISmartField2 replaced old ISmartField
In Scout 7.0 the new SmartField implementation used the package and name `smartfield2.SmartField2`. With Scout 7.1 the new SmartField replaced the old SmartField completely, and thus was moved to and renamed to `smartfield.SmartField`. If you have already used the new SmartField in Scout 7.0 you must move / rename all references to these classes.

== IContentAssistField classes and interfaces removed
The base class and interfaces of the old SmartField implementation was IContentAssistField. With the new SmartField implementation this interfaces and all classes containing the word "ContentAssist" in their name, have been either removed or renamed to "SmartField". If your code references one of these classes you should simply try to rename all references. Since the API of the new SmartField is almost the same as the old, this should work and should cause no or few changes in your code. The following classes have been removed without replacement:

* org.eclipse.scout.rt.client.ui.form.fields.smartfield.AbstractMixedSmartField
* org.eclipse.scout.rt.client.ui.form.fields.smartfield.ContentAssistFieldEvent
* org.eclipse.scout.rt.client.ui.form.fields.smartfield.ContentAssistFieldListener
* org.eclipse.scout.rt.client.ui.form.fields.smartfield.ContentAssistFieldTable
* org.eclipse.scout.rt.client.ui.form.fields.smartfield.IMixedSmartField

Since the new SmartImplementation does not have a proposal chooser model anymore these classes have also been removed. If you must have a special implementation of a proposal chooser, you must implement a proposal chooser in JavaScript (see: ProposalChooser.js), which renders the data / lookup-rows it receives from the server-side SmartField:

* org.eclipse.scout.rt.client.ui.form.fields.smartfield.AbstractProposalChooser
* org.eclipse.scout.rt.client.ui.form.fields.smartfield.IProposalChooser
* org.eclipse.scout.rt.client.ui.form.fields.smartfield.IProposalChooserProvider
* org.eclipse.scout.rt.client.ui.form.fields.smartfield.TableProposalChooser
* org.eclipse.scout.rt.client.ui.form.fields.smartfield.TreeProposalChooser



// ^^^
// Insert descriptions of Java API changes here


////
  =============================================================================
  === API CHANGES IN JAVA SCRIPT CODE =========================================
  =============================================================================
////

== API Changes (JavaScript)

N/A

// ^^^
// Insert descriptions of JavaScript API changes here

////
  =============================================================================
  === OTHER IMPORTANT CHANGES REQUIRING MIGRATION =============================
  =============================================================================
////

== Other Changes

N/A

// ^^^
// Insert descriptions of other important changes here
