////
Howto:
- Write this document such that it helps people to migrate. Describe what they should do.
- Chronological order is not necessary.
- Choose the right top level chapter (java, js, other)
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////

== About This Document

This document describes all relevant changes *from Eclipse Scout 9.0 to Eclipse Scout 10.0*. If existing code has to be migrated, instructions are provided here.

=== Service Releases

Scout 10.0 will continue to be maintained for a while and a new build may be released from time to time, following the https://wiki.eclipse.org/SimRel/Simultaneous_Release_Cycle_FAQ#What_is_the_Simultaneous_Release_cycle_.3F[Simultaneous Release Cycle]. Beside bugfixes, these service releases may even contain some minor features.

The following changes were made after the initial 10.0 release.

==== Simrel 2020-03 -- TBD

WARNING: {NotReleasedWarning}

// * <<Migration Description (since 10.0.0.xyz)>>

// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// WARNING: {NotReleasedWarning}
//
// * <<Migration Description (since 10.0.0.xyz)>>

////
  =============================================================================
  === API CHANGES IN JAVA CODE ================================================
  =============================================================================
////

== New Web Tool Stack
Scout updated the web tool stack from a custom implementation to a standard Node.js, Webpack and Babel based setup.
Thanks to the power of these tools it is now possible to write modern JavaScript code which will be transpiled at build time so that old browsers can execute the code.

To run the JavaScript build a JavaScript runtime is required. This can be downloaded from https://nodejs.org/. It is recommended to use a Node.js version 12 because this is a LTS release.
After downloading run the installer and add the installation directory to the PATH environment variable. This allows to use commands like `node` or `npm` from the command line.
These commands will be required later.

=== Migration for Scout Classic applications

This migration section applies to Scout Classic applications which do not have custom JavaScript code. For all other applications follow the description on how to migrate Scout JS applications in the next section.

. In the pom.xml of your parent project change the version of the parent maven_rt_plugin_config-master to 3.6.0.
. Create a file named `.gitignore` in the .ui.html module with the following content:
+
----
node_modules
dist
test-results
----
. Copy the following file to the root of your .ui.html module (replace the placeholder ${rootArtifactId} with your application name and ${version} with your application version): link:https://git.eclipse.org/c/scout/org.eclipse.scout.sdk.git/plain/scout-helloworld-app/src/main/resources/archetype-resources/__rootArtifactId__.ui.html/package.json?h=releases/10.0[package.json]
. Copy the following file to the root of the .ui.hml module: link:https://git.eclipse.org/c/scout/org.eclipse.scout.sdk.git/plain/scout-helloworld-app/src/main/resources/archetype-resources/__rootArtifactId__.ui.html/webpack.config.js?h=releases/10.0[webpack.config.js]
. Overwrite the file src/main/resources/WebContent/res/index.js with the following content:
+
[source,javascript]
----
import {RemoteApp} from '@eclipse-scout/core';
new RemoteApp().init();
----
. Move this file index.js to src/main/js
. Overwrite the file src/main/resources/WebContent/res/login.js with the following content:
+
[source,javascript]
----
import {LoginApp} from '@eclipse-scout/core';
new LoginApp().init();
----
. Move the login.js to src/main/js
. Overwrite the file src/main/resources/WebContent/res/logout.js with the following content:
+
[source,javascript]
----
import {LogoutApp} from '@eclipse-scout/core';
new LogoutApp().init();
----
. Move the logout.js to src/main/js
. Delete the files src/main/resources/WebContent/res/*macro.js
. Delete the files src/main/resources/WebContent/res/*macro.less
. Rename the file src/main/js/*-module.less in theme.less and add the following line at the top
+
[source,less]
----
@import "~@eclipse-scout/core/src/index";
----
. Replace the content of file src/main/resources/WebContent/index.html in the .ui.html module with this (replace ${displayName} with the title of your application): link:https://git.eclipse.org/c/scout/org.eclipse.scout.sdk.git/plain/scout-helloworld-app/src/main/resources/archetype-resources/__rootArtifactId__.ui.html/src/main/resources/WebContent/index.html?h=releases/10.0[index.html]
. Replace the content of file src/main/resources/WebContent/login.html in the .ui.html module with this (replace ${displayName} with the title of your application): link:https://git.eclipse.org/c/scout/org.eclipse.scout.sdk.git/plain/scout-helloworld-app/src/main/resources/archetype-resources/__rootArtifactId__.ui.html/src/main/resources/WebContent/login.html?h=releases/10.0[login.html]
. Replace the content of file src/main/resources/WebContent/logout.html in the .ui.html module with this (replace ${displayName} with the title of your application): link:https://git.eclipse.org/c/scout/org.eclipse.scout.sdk.git/plain/scout-helloworld-app/src/main/resources/archetype-resources/__rootArtifactId__.ui.html/src/main/resources/WebContent/logout.html?h=releases/10.0[logout.html]
. In the file src/main/webapp/WEB-INF/web.xml files of the .ui.html.app.dev and .ui.html.app.war modules change the `filter-exclude` list of the `UiServletFilter` declaration to the following:
+
----
/favicon/*
/fonts/*
/logo.png
/jquery*.js
/login*.js
/logout*.js
/theme*.css
/eclipse-scout*.js
----
. Remove property `scout.ui.prebuild` and `scout.ui.prebuild.files` from all config.properties files
. Open a terminal and navigate to the .ui.html module
. Run command `npm install`. This will download all JavaScript dependencies
. When finished run command `npm run build:dev`. This starts the transpile process and creates the output in the dist subfolder. The UI server will then pickup the files from there.


=== Migration for Scout JS applications

In Scout JS applications the project specific JavaScript code must be migrated to EcmaScript 6. For this a migration application is available.
This application migrates a single Maven module. For a standard Scout JS application it must be executed for the .ui module. If the project contains more modules with JavaScript code, the migration application must be executed for each of these.
To launch the migration application follow these steps:

. Open a Browser and download the API definition files from the https://git.eclipse.org/c/scout/org.eclipse.scout.rt.git/tree/js-mig-apis?h=releases/10.0[Scout Git Repository]. To do so right click on the small `plain` link for each file and save the target in a local directory.
. Create a new simple Maven project in Eclipse (File -> New -> Project -> Maven -> Maven Project -> Next, choose `Create a simple project`). Click Next.
. Choose a Group- and Artifact Id and click Finish.
. Open the created pom.xml and add a dependency to `org.eclipse.scout.rt:org.eclipse.scout.migration.ecma6:10.0.0-SNAPSHOT` and update the project using Alt+F5.
. Create a new class `Config` in src/main/js extending the class `org.eclipse.scout.migration.ecma6.Configuration`.
. Add an `@Replace` annotation to the class
. In the src/main/resources folder create a folder `META-INF` and within a file `scout.xml` (can be empty).
. Overwrite the following methods in the created `Config` class to configure the migration application to your local setup:
.. `getLibraryApiDirectory`: Point to the local directory where the API files from the first step are stored.
.. `getPersistLibraryFileName`: The application will create an API file for your project too. This is the place to specify the file name.
.. `getPersistLibraryName`: Choose the simple name of the module under migration.
.. `getSourceModuleDirectory`: Absolute path to the Maven module that should be migrated. If you have a Scout Classic application this is the module that ends with .ui.html. If you have a Scout JS application it is typically the module that ends with .ui.
.. `getTargetModuleDirectory`: Where the migrated files should be stored. If you want to perform an in-place migration to commit the changes to VCS return `getSourceModuleDirectory()`. To test and tweak the migration you can choose an temporary output directory.
.. `getJsFolderName`: The subfolder within src/main/js in which your JavaScript code is stored.
.. `getNamespace`: The JavaScript application namespace. This is the prefix all your JavaScript code lives in. If you have code like `helloworld.MyClass.prototype`, then the namespace is `helloworld`.
. Create a new Java Application launch configuration that uses your newly created project and launches the `org.eclipse.scout.migration.ecma6.Migration` class.
. The migration application has some prerequisites that the code can be migrated. Ensure that these are met before launching:
.. The source must be properly formatted.
.. One file must only contain one JavaScript class.
. If the above conditions are fulfilled the migration can be started using the created launch config.
. The migration is executed in two steps:
.. First all existing files are overwritten with the migrated content.
.. Second the files are moved to their new locations.
. When the first step finished, the migration app requests confirmation to continue with the second step. This gives you the possibility to commit the first step to VCS which preserves the history.

After the migration execution there are some manual post processing tasks that must be executed:

. In the pom.xml of your parent project change the version of the parent maven_rt_plugin_config-master to 3.6.0.
. Create a file named `.gitignore` in the .ui.html module and the .app module with the following content:
+
----
node_modules
dist
test-results
----
. Copy the following file to the root of the .ui module (replace the placeholders ${simpleArtifactName} with your application name and ${version} with your application version): link:https://git.eclipse.org/c/scout/org.eclipse.scout.sdk.git/plain/scout-hellojs-app/src/main/resources/archetype-resources/__rootArtifactId__.ui/package.json?h=releases/10.0[package.json]
. Copy the following file to the root of the .ui module: link:https://git.eclipse.org/c/scout/org.eclipse.scout.sdk.git/plain/scout-hellojs-app/src/main/resources/archetype-resources/__rootArtifactId__.ui/webpack.config.js?h=releases/10.0[webpack.config.js]
. Copy the following file to the root of the .ui module: link:https://git.eclipse.org/c/scout/org.eclipse.scout.sdk.git/plain/scout-hellojs-app/src/main/resources/archetype-resources/__rootArtifactId__.ui/karma.conf.js?h=releases/10.0[karma.conf.js]
. Copy the following file to the directory src/test/js of the .ui module: link:https://git.eclipse.org/c/scout/org.eclipse.scout.sdk.git/plain/scout-hellojs-app/src/main/resources/archetype-resources/__rootArtifactId__.ui/src/test/js/test-index.js?h=releases/10.0[test-index.js]
. Copy the following file to the root of the .app module (replace the placeholders ${simpleArtifactName} with your application name, ${version} with your application version and ${rootArtifactId} with the root module name): link:https://git.eclipse.org/c/scout/org.eclipse.scout.sdk.git/plain/scout-hellojs-app/src/main/resources/archetype-resources/__rootArtifactId__.app/package.json?h=releases/10.0[package.json]
. Copy the following file to the root of the .app module (replace the placeholder ${simpleArtifactName} with your application name): link:https://git.eclipse.org/c/scout/org.eclipse.scout.sdk.git/plain/scout-hellojs-app/src/main/resources/archetype-resources/__rootArtifactId__.app/webpack.config.js?h=releases/10.0[webpack.config.js]
. Create the file src/main/js/index.js in the .app module with the following content (replace the placeholder ${simpleArtifactName} with your application name):
+
[source,javascript]
----
import {App} from '@${simpleArtifactName}/ui';
new App().init({
  bootstrap: {
    textsUrl: 'res/texts.json'
  }
});
----
. Create the file src/main/js/theme.less in the .ui module with the following content:
+
[source,less]
----
@import "~@eclipse-scout/core/src/index";
@import "index";
----
. Create the file src/main/js/theme-dark.less in the .ui module with the following content:
+
[source,less]
----
@import "theme";
@import "~@eclipse-scout/core/src/index-dark";
----
. Delete the files src/main/resources/WebContent/res/*macro.* in the .app module
. Delete the file src/main/resources/WebContent/res/index.js in the .app module
. Replace the content of file src/main/resources/WebContent/index.html in the .app module with this (replace ${displayName} with the title of your application and ${simpleArtifactName} with your application name): link:https://git.eclipse.org/c/scout/org.eclipse.scout.sdk.git/plain/scout-hellojs-app/src/main/resources/archetype-resources/__rootArtifactId__.app/src/main/resources/WebContent/index.html?h=releases/10.0[index.html]
. In the file src/main/resources/WebContent/popup-window.html in the .app module add `includes/` in front of the template attribute of the <scout:include> tag.
. Move all files and folders in src/main/resources/WebContent/res one folder up directly into WebContent and delete the empty res folder.
. Search for all occurrences of `res` within the `WebContent` folder and remove the res folder.
. If you have a Repository.js change the global object holding the repositories from `${yourAppNamespace}.repositories = {};` to `static repositories = {};` and change all references in this file from `${yourAppNamespace}.repositories` to `Repository.repositories`.
. Remove any Jasmine server test launch configurations (*jasmine*.launch files).
. Remove any Spec runner HTML files (Spec*Runner*.html files).
. Remove all entries of the Maven plugins `jasmine-maven-plugin` and `phantomjs-maven-plugin` from the pom.xml files.
. In all pom.xml files remove the entries of the Maven plugin `maven-dependency-plugin` that runs in phase `generate-test-sources` and unpacks files from `org.eclipse.scout.rt.ui.html` or `org.eclipse.scout.rt.ui.html.test`.
. In the pom.xml of the .ui module add the following properties:
.. `master_skip_pnpm_install_dev=true`
.. `master_skip_pnpm_install_prod=true`
.. `master_skip_copy_webpack_build_output=true`
. Move all Specs from src/test/js/${yourAppNamespace} to src/test/js (one folder up).
. Open a terminal in the folder of the .ui module and run the command `npm install`. This installs all dependencies that are required by the .ui module.
. Open a terminal in the folder of the .app module and run the command `npm install`. This installs all dependencies that are required by the .app module (including the .ui module of your project).
. In the terminal of the .app module run the following command: `npm run build:dev`. This triggers the transpiler that creates the JavaScript build output in the dist folder of the .app module. Only after this command has been executed the server can find the web resources to deliver them to the browser.
. In the terminal of the .ui module run the following command: `npm run testserver:start`. This executes the Jasmine Specs in a Chrome browser (Chrome must be installed locally, the same applies to ChromeHeadless if running the build in a CI environment).
. If there are any build errors, fix them manually. The migration application might not fix any possible code correctly.

The steps above used NPM to install dependencies (`npm install`). Depending on your needs there might be other frameworks that better suit your setup.
We recommend having a look at the following alternatives:

. https://pnpm.js.org/[PNPM]
. https://yarnpkg.com[Yarn]

Please note that Scout uses PNPM internally during the Maven build.


== API Changes (Java)

=== StrictSimpleDateFormat
`org.eclipse.scout.rt.jackson.dataobject.StrictSimpleDateFormat` was removed. Use `org.eclipse.scout.rt.platform.util.date.StrictSimpleDateFormat` instead.

=== ObjectUtility
`nvlOptional()` was renamed to `nvlOpt()`.

=== Data Objects
The Scout data object support was moved from the Scout platform to the module `org.eclipse.scout.rt.dataobject`.
The package imports of all data object related classes therefore changed:
From `org.eclipse.scout.rt.platform.dataobject` to `org.eclipse.scout.rt.dataobject`

==== Renamings
`org.eclipse.scout.rt.client.ui.desktop.datachange.DoChangeEvent` -> `org.eclipse.scout.rt.client.ui.desktop.datachange.ItemDataChangeEvent`

==== Dependencies
All modules which use data objects were extended with a dependency to `org.eclipse.scout.rt.dataobject`

* `org.eclipse.scout.rt.rest`
* `org.eclipse.scout.rt.mom.api`

==== Renamings in ErrorDo
* `org.eclipse.scout.rt.rest.error.ErrorDo#status` -> `org.eclipse.scout.rt.rest.error.ErrorDo#httpStatus`
* `org.eclipse.scout.rt.rest.error.ErrorDo#code` -> `org.eclipse.scout.rt.rest.error.ErrorDo#errorCode`

=== CacheBuilder
The following methods on `CacheBuilder` where removed, since they were unused and covered unused, old functionality:

* Method `org.eclipse.scout.rt.shared.cache.CacheBuilder.addCacheInstance(ICache<K, V>)`
* Method `org.eclipse.scout.rt.shared.cache.CacheBuilder.getCacheInstances()`

=== Move ICache and transactional Map
`AbstractTransactionalMap` and its concrete implementations `ConcurrentTransactionalMap` and `CopyOnWriteTransactionalMap` have been moved to `org.eclipse.scout.rt.platform.util.collection`.

`ICache`, its implementations and cache wrappers have been moved to  `org.eclipse.scout.rt.platform.cache`.




=== Authorization API
The authorization API of scout was extended and moved from `org.eclipse.scout.rt.shared` into its own module.
You may check the technical guide for further details.

* Introduced `IPermissionCollection` and `IPermission` interfaces
* Let all current scout permission (e.g. `CopyToClipboardPermission`) implement `IPermission`
* All scout permission names are now prefixed with `scout.`
* `RemoteServiceAccessPermission#getName` returns a stable name instead of the service operation pattern
* Deleted `BasicHierarchyPermission`.
If required, you may copy from an older version of scout.
* `org.eclipse.scout.rt.shared.services.common.security.IAccessControlService` moved to `org.eclipse.scout.rt.security`
* `IAccessControlService#getPermissionLevel` removed; use instead `ACCESS#getGrantedPermissionLevel`
* `IAccessControlService#checkPermission` removed; use instead `ACCESS#check`
* `IAccessControlService#getPermissions` must now *never* return `null`. Instead `NonePermissionCollection` or `AllPermissionCollection` may be returned.
* `org.eclipse.scout.rt.shared.services.common.security.ACCESS` moved to `org.eclipse.scout.rt.security.ACCESS`
* `ACCESS#check` now fails if argument is `null` (before succeeds).
* `org.eclipse.scout.rt.shared.services.common.security.AbstractAccessControlService` moved to `org.eclipse.scout.rt.security`
* `AbstractAccessControlService#getUserIdOfCurrentUser` moved to `Sessions#getCurrentUserId()`

==== Load Permissions
With the new `IPermissionCollection`, loading of permissions in `AbstractAccessControlService#execLoadPermissions` has changed.

* Create a new instance by calling `BEANS.get(DefaultPermissionCollection.class)` instead of `new java.security.Permissions()`.
* Add permissions with a permission level: `permissions.add(new ReadUsersPermission(), PermissionLevel.ALL);`
* Do not forget to set permission collection as read only: `permissions.setReadOnly();`

There is also a `AllPermissionCollection` which may be used instead of `DefaultPermissionCollection`.


=== TestingUtility -> BeanTestingHelper
The following methods are deprecated. Use the corresponding methods on `BeanTestingHelper` via `BeanTestingHelper.get()` instead:

* `registerBeans`
* `registerBean`
* `unregisterBean`
* `unregisterBeans`
* `mockConfigProperty`

The following replacement regex can be applied on all Java files: +
`\bTestingUtility\.(registerBeans|registerBean|unregisterBean|unregisterBeans|mockConfigProperty)` to `BeanTestingHelper.get().$1`

The following methods are deprecated and will be removed in a future release without a replacement:

* `registerWithReplace`
* `registerWithTestingOrder`
* `clearHttpAuthenticationCache`


=== MailHelper.getCharacterEncodingOfPart(Part)
`MailHelper.getCharacterEncodingOfPart(Part)` is deprecated, use `ObjectUtility.nvl(BEANS.get(MailHelper.class).getPartCharset(part), StandardCharsets.UTF_8).name()` instead if same behavior is required.


// ^^^
// Insert descriptions of Java API changes here

////
  =============================================================================
  === API CHANGES IN JAVA SCRIPT CODE =========================================
  =============================================================================
////

== API Changes (JavaScript)


// ^^^
// Insert descriptions of other important changes here

== REST Service Changes

Any changes which may change how REST consumer or provider behave.

=== Renamings in ErrorDo
`org.eclipse.scout.rt.rest.error.ErrorDo` used by `org.eclipse.scout.rt.rest.client.proxy.ErrorDoRestClientExceptionTransformer` and some `org.eclipse.scout.rt.rest.exception.AbstractExceptionMapper<E>` was slightly changed:

* `ErrorDo#status` -> `ErrorDo#httpStatus`
* `ErrorDo#code` -> `ErrorDo#errorCode`

=== Different HTTP status codes

A REST service client using `ErrorDoRestClientExceptionTransformer` will now transform

* any client request error (HTTP `4xx` status codes) into a `VetoException`
* `403 - Forbidden` into a `org.eclipse.scout.rt.dataobject.exception.AccessForbiddenException`
* `404 - Not Found` into a `org.eclipse.scout.rt.dataobject.exception.ResourceNotFoundException`

The `org.eclipse.scout.rt.rest.exception.VetoExceptionMapper` used by a REST service provide will now create an error response with status `400 - Bad Request` (this was formerly a `403`).
