////
Howto:
- Write this document such that it helps people to migrate. Describe what they should do.
- Chronological order is not necessary.
- Choose the right top level chapter (java, js, other)
- Use {NOTRELEASEDWARNING} on its own line to mark parts about not yet released code (also add a "since 8.0.xxx" note)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////

== About This Document

This document describes all relevant changes *from Eclipse Scout 8.0 to Eclipse Scout 9.0*. If existing code has to be migrated, instructions are provided here.

//=== Service Release Migration

//The following changes were made after the initial 9.0 release. Additionally follow these instructions when updating to a _service release_.

//==== 9.0.100 (release date to be defined)

{NotReleasedWarning}

////
  =============================================================================
  === API CHANGES IN JAVA CODE ================================================
  =============================================================================
////

== API Changes (Java)

=== Disabling Close- & Cancel-Buttons

Until Scout 8.0 a Close- or Cancel-Button ignored the enabled-granted property to ensure the form can be closed even if the full form has been disabled using `setEnabledGranted(false)`. This was confusing because the same convenience was not available for all other enabled dimensions.

Since Scout 9.0 Close- and Cancel-Buttons can be disabled like any other form field. But one special handling is still present: The method `isEnabledIncludingParents` ignores the enabled state of the parents and always returns the state of the button only.

So if a Form or GroupBox is disabled using `setEnabled(false)` or `setEnabledGranted(false)` or any other dimension, the full form gets disabled except the Close- and Cancel-Buttons. As soon as the button is disabled explicitly (e.g. by calling `setEnabled(false)` on the button itself or by propagating to the button using `setEnabled(false, false, true)` on a parent composite) it will be disabled and the form cannot be closed anymore.

*Migration:*

If you never wanted to have a Close- or Cancel-Button to be disabled (to ensure the form can be closed) there is no migration necessary.

If you have Close- or Cancel-Buttons that need to be disabled, you need to check the code and ensure that the button itself is disabled, not only a parent form field.
Also the trick not using the granted-dimension on a parent field of the button (to disable the button as well) will no longer work. Now the button must be disabled explicitly on the button or by propagating the change on a parent form field.

=== Add custom header for REST services

By default REST services exposed by Scout using the `org.eclipse.scout.rt.rest.RestApplication` are protected against https://en.wikipedia.org/wiki/Cross-site_request_forgery[CSRF] now.
This requires a custom header to be present on all non GET or HEAD requests. Please do also ensure that GET or HEAD requests do follow the HTTP specification and therefore do not perform any data or state changing operations!

As long as the ScoutJS App or the `org.eclipse.scout.rt.rest.client.AbstractRestClientHelper` is used to call REST services this header is automatically added.
For other 3rd party clients the custom header `X-Requested-With` must be added.
There is no value for the header required. Typically `XMLHttpRequest` is passed but the value can be chosen freely.

If there are non CSRF prone clients (like backend systems) such clients may also be excluded from the CSRF header check by replacing the Scout Bean `AntiCsrfHelper` and ignoring such requests.

See the Scout Bean `org.eclipse.scout.rt.rest.csrf.AntiCsrfHelper` for more details.

// ^^^
// Insert descriptions of Java API changes here

////
  =============================================================================
  === API CHANGES IN JAVA SCRIPT CODE =========================================
  =============================================================================
////

== API Changes (JavaScript)

=== Rename of LESS Variables

If you created a custom theme, you might have to adjust some LESS variables.

* Renamed `@scrollbar-thumb-color` to `@scrollbar-thumb-main-color`
* Renamed `@scrollbar-thumb-inverted-color` to `@scrollbar-thumb-inverted-main-color`
* Renamed `@calendar-mode-active-text-color` to `@calendar-mode-selected-color`
* Renamed `@planner-mode-active-text-color` to `@planner-mode-selected-color`
* Renamed `@popup-border-color` to `@control-popup-border-color`
* Renamed `@view-tab-active-color` to `@simple-tab-active-color`
* Renamed `@view-tab-active-background-color` to `@simple-tab-active-background-color`
* Renamed `@view-tab-background-color` to `@simple-tab-background-color`
* Renamed `@table-header-menu-cmd-active-background-color` to `@table-header-menu-cmd-selected-background-color`
* Renamed `@table-header-menu-cmd-active-border-color` to `@table-header-menu-cmd-selected-border-color`
* Renamed `@table-header-menu-cmd-active-color` to `@table-header-menu-cmd-selected-color`
* Renamed `@table-control-active-color` to `@table-control-selected-color`
* Renamed `@table-control-active-background-color` to `@table-control-selected-background-color`
* Renamed `@scrollbar-side-margin` to `@scrollbar-side-padding`
////
  =============================================================================
  === OTHER IMPORTANT CHANGES REQUIRING MIGRATION =============================
  =============================================================================
////

== Other Changes
