= Hello Scout JS Full Stack

NOTE: Looking for something else? Visit https://eclipsescout.github.io for all Scout related documentation.

include::common:partial$Init.adoc[]

ifndef::source-highlighter[:source-highlighter: coderay]

== Introduction

In this tutorial we will create a Scout JS application consisting of a JavaScript frontend connected using REST to a Java backend that stores the data in a database.

NOTE: If you don't know what Scout JS is yet, please read the xref:getstarted:getstarted.adoc[], first.

We will create the application using IntelliJ.
The generated application can display persons loaded from a database.
These persons can be edited or deleted and new persons can be added.

== Prerequisites

This section guides you through the installation of the tools required to start the `Hello Scout JS Full Stack` application.

=== Node.js

include::common:partial$InstallNode.adoc[]

=== IntelliJ

include::common:partial$InstallIntelliJ.adoc[]

== Create the Project

include::common:partial$CreateNewJsProjectIntellij.adoc[]

== What's Next?

:jswidgets: https://scout.bsi-software.com/jswidgets_{doc-short-version-underlined}/
:jswidgets-code: https://github.com/bsi-software/org.eclipse.scout.docs/tree/releases/{doc-short-version}/modules/common/examples/widgets

To learn more about Scout JS, we recommend having a look at xref:technicalGuideJS:ScoutJS.adoc[].

To see more example code of Scout JS, you should have a look at the {jswidgets}[Scout JS Widgets] application
and its {jswidgets-code}[source code].

In case you should get stuck somewhere and need help, contact us on the http://www.eclipse.org/forums/eclipse.scout[Scout Forum] or on https://stackoverflow.com/tags/eclipse-scout[Stack Overflow].
