= Hello Scout JS Full Stack
// comment prevents empty line after formatting, needed for toc
include::../../../common/src/docs/_header.adoc[]

== Introduction

In this tutorial we will create a Scout JS application consisting of a JavaScript frontend connected using REST to a Java backend that stores the data in a database.

NOTE: If you don't know what Scout JS is yet, please read the https://eclipsescout.github.io/{doc-short-version}/getstarted.html[Get Started Guide] first.

We will create the application using IntelliJ.
The generated application can display persons loaded from a database.
These persons can be edited or deleted and new persons can be added.

== Prerequisites

This section guides you through the installation of the tools required to start the `Hello Scout JS Full Stack` application.

=== Node.js

include::{mdledir}/InstallNode.adoc[]

=== IntelliJ

include::{mdledir}/InstallIntelliJ.adoc[]

== Create the Project

include::{mdledir}/CreateNewJsProjectIntellij.adoc[]

== What's Next?

:jswidgets: https://scout.bsi-software.com/jswidgets_{doc-short-version-underlined}/
:jswidgets-code: https://github.com/bsi-software/org.eclipse.scout.docs/tree/releases/{doc-short-version}/code/widgets
:docs: https://eclipsescout.github.io/{doc-short-version}
:technical-guide-js: {docs}/technical-guide-js.html
:scout-forum: http://www.eclipse.org/forums/eclipse.scout

To learn more about Scout JS, we recommend having a look at the other {docs}[Scout JS Tutorials] and the {technical-guide-js}[Scout JS Technical Guide].

To see more example code of Scout JS, you should have a look at the {jswidgets}[Scout JS Widgets] application
and its {jswidgets-code}[source code].

In case you should get stuck somewhere and need help, contact us on the http://www.eclipse.org/forums/eclipse.scout[Scout Forum] or on https://stackoverflow.com/tags/eclipse-scout[Stack Overflow].

:_footer-link-path: build/helloscout_js_fullstack/src/docs/{docname}.adoc
include::../../../common/src/docs/_footer.adoc[]