/**
 * Copyright (c) 2019 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.html
 * <p>
 * Contributors:
 * BSI Business Systems Integration AG - initial API and implementation
 */
package org.eclipsescout.demo.bahbah.shared.services.process;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "org.eclipsescout.demo.bahbah.client.ui.forms.UserForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class UserFormData extends AbstractFormData {
  private static final long serialVersionUID = 1L;

  public Username getUsername() {
    return getFieldByClass(Username.class);
  }

  public Password getPassword() {
    return getFieldByClass(Password.class);
  }

  public UserRole getUserRole() {
    return getFieldByClass(UserRole.class);
  }

  public UserIdProperty getUserIdProperty() {
    return getPropertyByClass(UserIdProperty.class);
  }

  /**
   * access method for property UserId.
   */
  public Long getUserId() {
    return getUserIdProperty().getValue();
  }

  /**
   * access method for property UserId.
   */
  public void setUserId(Long userId) {
    getUserIdProperty().setValue(userId);
  }

  public static class UserIdProperty extends AbstractPropertyData<Long> {
    private static final long serialVersionUID = 1L;
  }

  public static class Username extends AbstractValueFieldData<String> {
    private static final long serialVersionUID = 1L;
  }

  public static class Password extends AbstractValueFieldData<String> {
    private static final long serialVersionUID = 1L;
  }

  public static class UserRole extends AbstractValueFieldData<Integer> {
    private static final long serialVersionUID = 1L;
  }
}
