/*******************************************************************************
 * Copyright (c) 2015 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 ******************************************************************************/
package org.eclipse.scout.contacts.server.sql;

public interface SQLs {

  String CONTACT_LOOKUP = ""
      + "SELECT   contact_id, "
      + "         CASE "
      + "           WHEN first_name IS null "
      + "            THEN last_name "
      + "           WHEN last_name IS null "
      + "            THEN first_name "
      + "           ELSE "
      + "            first_name || ' ' || last_name "
      + "         END "
      + "FROM     CONTACT "
      + "WHERE    1 = 1 "
      + "<key>    AND contact_id = :key</key> "
      + "<text>   AND (UPPER(first_name) LIKE UPPER('%'||:text||'%') "
      + "         OR UPPER(last_name) LIKE UPPER('%'||:text||'%')) "
      + "</text>"
      + "<all> </all>";

  String COMPANY_LOOKUP = ""
      + "SELECT   company_id, "
      + "         name "
      + "FROM     COMPANY "
      + "WHERE    1 = 1 "
      + "<key>    AND company_id = :key</key> "
      + "<text>   AND UPPER(name) LIKE UPPER(:text||'%') </text> "
      + "<all></all>";

  String AND_LIKE_CAUSE = "AND UPPER(%s) LIKE UPPER(:%s || '%s')";

  String COMPANY_PAGE_SELECT = ""
      + "SELECT   company_id, "
      + "         name, "
      + "         city, "
      + "         country, "
      + "         url "
      + "FROM     COMPANY";

  String COMPANY_PAGE_DATA_SELECT_INTO = ""
      + "INTO     :{page.companyId}, "
      + "         :{page.name}, "
      + "         :{page.city}, "
      + "         :{page.country}, "
      + "         :{page.homepage}";

  String COMPANY_INSERT = ""
      + "INSERT   INTO "
      + "COMPANY  (company_id) "
      + "VALUES   (:companyId)";

  String COMPANY_SELECT = ""
      + "SELECT   name, "
      + "         logo_url, "
      + "         url, "
      + "         phone, "
      + "         email, "
      + "         street, "
      + "         city, "
      + "         country, "
      + "         comment "
      + "FROM     COMPANY "
      + "WHERE    company_id = :companyId "
      + "INTO     :name, "
      + "         :logoBox.pictureUrl, "
      + "         :homepage, "
      + "         :phone, "
      + "         :email, "
      + "         :addressBox.street, "
      + "         :addressBox.city, "
      + "         :addressBox.country, "
      + "         :comments";

  String COMPANY_UPDATE = ""
      + "UPDATE   COMPANY "
      + "SET      name = :name, "
      + "         logo_url = :logoBox.pictureUrl, "
      + "         url = :homepage, "
      + "         phone = :phone, "
      + "         email = :email, "
      + "         street = :addressBox.street, "
      + "         city = :addressBox.city, "
      + "         country = :addressBox.country, "
      + "         comment = :comments "
      + "WHERE    company_id = :companyId";

  String CONTACT_PAGE_SELECT = ""
      + "SELECT   contact_id, "
      + "         first_name, "
      + "         last_name, "
      + "         city, "
      + "         country, "
      + "         phone, "
      + "         mobile, "
      + "         email, "
      + "         company_id "
      + "FROM     CONTACT";

  String CONTACT_PAGE_DATA_SELECT_INTO = ""
      + "INTO     :{page.contactId}, "
      + "         :{page.firstName}, "
      + "         :{page.lastName}, "
      + "         :{page.city}, "
      + "         :{page.country}, "
      + "         :{page.phone}, "
      + "         :{page.mobile}, "
      + "         :{page.email}, "
      + "         :{page.company}";

  String CONTACT_INSERT = ""
      + "INSERT   INTO "
      + "CONTACT  (contact_id) "
      + "VALUES   (:contactId)";

  String CONTACT_SELECT = ""
      + "SELECT   first_name, "
      + "         last_name, "
      + "         picture_url, "
      + "         date_of_birth, "
      + "         gender, "
      + "         phone, "
      + "         mobile, "
      + "         email, "
      + "         street, "
      + "         city, "
      + "         country, "
      + "         position, "
      + "         company_id, "
      + "         phone_work, "
      + "         email_work, "
      + "         comment "
      + "FROM     CONTACT "
      + "WHERE    contact_id = :contactId "
      + "INTO     :firstName, "
      + "         :lastName, "
      + "         :pictureBox.pictureUrl, "
      + "         :dateOfBirth, "
      + "         :genderGroup, "
      + "         :phone, "
      + "         :mobile, "
      + "         :email, "
      + "         :addressBox.street, "
      + "         :addressBox.city, "
      + "         :addressBox.country, "
      + "         :position, "
      + "         :company, "
      + "         :phoneWork, "
      + "         :emailWork, "
      + "         :comments";

  String CONTACT_UPDATE = ""
      + "UPDATE   CONTACT "
      + "SET      first_name = :firstName, "
      + "         last_name = :lastName, "
      + "         picture_url = :pictureBox.pictureUrl, "
      + "         date_of_birth = :dateOfBirth, "
      + "         gender = :genderGroup, "
      + "         phone  = :phone, "
      + "         mobile = :mobile, "
      + "         email = :email, "
      + "         street = :addressBox.street, "
      + "         city = :addressBox.city, "
      + "         country = :addressBox.country, "
      + "         position = :position, "
      + "         company_id = :company, "
      + "         phone_work = :phoneWork, "
      + "         email_work = :emailWork, "
      + "         comment = :comments "
      + "WHERE    contact_id = :contactId";

  String SELECT_TABLE_NAMES = ""
      + "SELECT   UPPER(tablename) "
      + "FROM     sys.systables "
      + "INTO     :result";

  String COMPANY_CREATE_TABLE = ""
      + "CREATE   TABLE COMPANY "
      + "         (company_id VARCHAR(64) NOT NULL CONSTRAINT COMPANY_PK PRIMARY KEY, "
      + "          name VARCHAR(64), "
      + "          logo_url VARCHAR(512), "
      + "          url VARCHAR(64), "
      + "          street VARCHAR(64), "
      + "          city VARCHAR(64), "
      + "          country VARCHAR(2), "
      + "          phone VARCHAR(20), "
      + "          email VARCHAR(64), "
      + "          comment VARCHAR(1024)"
      + "         )";

  String CONTACT_CREATE_TABLE = ""
      + "CREATE   TABLE CONTACT "
      + "         (contact_id VARCHAR(64) NOT NULL CONSTRAINT PERSON_PK PRIMARY KEY, "
      + "          first_name VARCHAR(64), "
      + "          last_name VARCHAR(64), "
      + "          picture_url VARCHAR(512), "
      + "          date_of_birth DATE, "
      + "          gender VARCHAR(1), "
      + "          street VARCHAR(64), "
      + "          city VARCHAR(64), "
      + "          country VARCHAR(2), "
      + "          phone VARCHAR(20), "
      + "          mobile VARCHAR(20), "
      + "          email VARCHAR(64), "
      + "          company_id VARCHAR(64), "
      + "          position VARCHAR(512), "
      + "          phone_work VARCHAR(20), "
      + "          email_work VARCHAR(64), "
      + "          comment VARCHAR(1024), "
      + "          CONSTRAINT COMPANY_FK FOREIGN KEY (company_id) REFERENCES COMPANY (company_id)"
      + "         )";

  String COMPANY_INSERT_SAMPLE_DATA_1 = ""
      + "INSERT   INTO COMPANY "
      + "        (company_id, "
      + "         name, city, "
      + "         country, "
      + "         url) "
      + "VALUES  (:company_id, "
      + "         'Alice''s Adventures in Wonderland', "
      + "         'London', "
      + "         'GB', "
      + "         'http://en.wikipedia.org/wiki/Alice%27s_Adventures_in_Wonderland')";

  String COMPANY_INSERT_SAMPLE_DATA_2 = ""
      + "INSERT   INTO COMPANY "
      + "         (company_id, "
      + "          name, "
      + "          city, "
      + "          country, "
      + "          url) "
      + "VALUES   (:company_id, "
      + "          'BSI Business Systems Integration AG', "
      + "          'Daettwil, Baden', "
      + "          'CH', "
      + "          'https://www.bsi-software.com')";

  String CONTACT_INSERT_SAMPLE_DATA_1 = ""
      + "INSERT   INTO CONTACT "
      + "         (contact_id, "
      + "          first_name, "
      + "          picture_url, "
      + "          date_of_birth, "
      + "          gender, "
      + "          city, "
      + "          country, "
      + "          position, "
      + "          company_id) "
      + "VALUES   (:person_id, "
      + "          'Alice', "
      + "          'http://www.uergsel.de/uploads/Alice.png', "
      + "          :dob, "
      + "          'F', "
      + "          'Daresbury, Cheshire', "
      + "          'GB', "
      + "          'The curious girl', "
      + "          (SELECT  company_id "
      + "           FROM    COMPANY "
      + "           WHERE   name = 'Alice''s Adventures in Wonderland')"
      + "           )";

  String CONTACT_INSERT_SAMPLE_DATA_2 = ""
      + "INSERT   INTO CONTACT "
      + "         (contact_id, "
      + "          first_name, "
      + "          last_name, "
      + "          picture_url, "
      + "          date_of_birth, "
      + "          gender, "
      + "          city, "
      + "          country, "
      + "          position, "
      + "          company_id) "
      + "VALUES   (:person_id, "
      + "          'Rabbit', "
      + "          'the White', "
      + "          'http://upload.wikimedia.org/wikipedia/commons/e/ec/Down_the_Rabbit_Hole.png', "
      + "          :dob, "
      + "          'F', "
      + "          'Daresbury, Cheshire', "
      + "          'GB', "
      + "          'Follow me', "
      + "          (SELECT  company_id "
      + "          FROM     COMPANY "
      + "          WHERE    name = 'Alice''s Adventures in Wonderland')"
      + "          )";
}
