/*******************************************************************************
 * Copyright (c) 2015 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 ******************************************************************************/
package org.eclipse.scout.contacts.shared.company;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "PageDataUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class CompanyTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  public CompanyTablePageData() {
  }

  @Override
  public CompanyTableRowData addRow() {
    return (CompanyTableRowData) super.addRow();
  }

  @Override
  public CompanyTableRowData addRow(int rowState) {
    return (CompanyTableRowData) super.addRow(rowState);
  }

  @Override
  public CompanyTableRowData createRow() {
    return new CompanyTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return CompanyTableRowData.class;
  }

  @Override
  public CompanyTableRowData[] getRows() {
    return (CompanyTableRowData[]) super.getRows();
  }

  @Override
  public CompanyTableRowData rowAt(int index) {
    return (CompanyTableRowData) super.rowAt(index);
  }

  public void setRows(CompanyTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class CompanyTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String companyId = "companyId";
    public static final String name = "name";
    public static final String city = "city";
    public static final String country = "country";
    public static final String homepage = "homepage";
    private String m_companyId;
    private String m_name;
    private String m_city;
    private String m_country;
    private String m_homepage;

    public CompanyTableRowData() {
    }

    public String getCompanyId() {
      return m_companyId;
    }

    public void setCompanyId(String companyId) {
      m_companyId = companyId;
    }

    public String getName() {
      return m_name;
    }

    public void setName(String name) {
      m_name = name;
    }

    public String getCity() {
      return m_city;
    }

    public void setCity(String city) {
      m_city = city;
    }

    public String getCountry() {
      return m_country;
    }

    public void setCountry(String country) {
      m_country = country;
    }

    public String getHomepage() {
      return m_homepage;
    }

    public void setHomepage(String homepage) {
      m_homepage = homepage;
    }
  }
}
