/**
 * 
 */
package org.eclipsescout.contacts.shared.premium;

import java.util.Date;
import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.tablefield.AbstractTableFieldBeanData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;
import org.eclipsescout.contacts.shared.ui.template.formfield.AbstractAddressBoxData;
import org.eclipsescout.contacts.shared.ui.template.formfield.AbstractEmailFieldData;
import org.eclipsescout.contacts.shared.ui.template.formfield.AbstractPhoneFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class EventFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public EventFormData() {
  }

  public Comments getComments() {
    return getFieldByClass(Comments.class);
  }

  public Email getEmail() {
    return getFieldByClass(Email.class);
  }

  public Ends getEnds() {
    return getFieldByClass(Ends.class);
  }

  /**
   * access method for property EventId.
   */
  public String getEventId() {
    return getEventIdProperty().getValue();
  }

  /**
   * access method for property EventId.
   */
  public void setEventId(String eventId) {
    getEventIdProperty().setValue(eventId);
  }

  public EventIdProperty getEventIdProperty() {
    return getPropertyByClass(EventIdProperty.class);
  }

  public Homepage getHomepage() {
    return getFieldByClass(Homepage.class);
  }

  public LocationBox getLocationBox() {
    return getFieldByClass(LocationBox.class);
  }

  public Participants getParticipants() {
    return getFieldByClass(Participants.class);
  }

  public Phone getPhone() {
    return getFieldByClass(Phone.class);
  }

  public Starts getStarts() {
    return getFieldByClass(Starts.class);
  }

  public Title getTitle() {
    return getFieldByClass(Title.class);
  }

  public static class Comments extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Comments() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class Email extends AbstractEmailFieldData {

    private static final long serialVersionUID = 1L;

    public Email() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class Ends extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;

    public Ends() {
    }
  }

  public static class EventIdProperty extends AbstractPropertyData<String> {

    private static final long serialVersionUID = 1L;

    public EventIdProperty() {
    }
  }

  public static class Homepage extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Homepage() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class LocationBox extends AbstractAddressBoxData {

    private static final long serialVersionUID = 1L;

    public LocationBox() {
    }
  }

  public static class Participants extends AbstractTableFieldBeanData {

    private static final long serialVersionUID = 1L;

    public Participants() {
    }

    @Override
    public ParticipantsRowData addRow() {
      return (ParticipantsRowData) super.addRow();
    }

    @Override
    public ParticipantsRowData addRow(int rowState) {
      return (ParticipantsRowData) super.addRow(rowState);
    }

    @Override
    public ParticipantsRowData createRow() {
      return new ParticipantsRowData();
    }

    @Override
    public Class<? extends AbstractTableRowData> getRowType() {
      return ParticipantsRowData.class;
    }

    @Override
    public ParticipantsRowData[] getRows() {
      return (ParticipantsRowData[]) super.getRows();
    }

    @Override
    public ParticipantsRowData rowAt(int index) {
      return (ParticipantsRowData) super.rowAt(index);
    }

    public void setRows(ParticipantsRowData[] rows) {
      super.setRows(rows);
    }

    public static class ParticipantsRowData extends AbstractTableRowData {

      private static final long serialVersionUID = 1L;
      public static final String contactId = "contactId";
      public static final String firstName = "firstName";
      public static final String lastName = "lastName";
      public static final String company = "company";
      private String m_contactId;
      private String m_firstName;
      private String m_lastName;
      private String m_company;

      public ParticipantsRowData() {
      }

      /**
       * @return the ContactId
       */
      public String getContactId() {
        return m_contactId;
      }

      /**
       * @param contactId
       *          the ContactId to set
       */
      public void setContactId(String contactId) {
        m_contactId = contactId;
      }

      /**
       * @return the FirstName
       */
      public String getFirstName() {
        return m_firstName;
      }

      /**
       * @param firstName
       *          the FirstName to set
       */
      public void setFirstName(String firstName) {
        m_firstName = firstName;
      }

      /**
       * @return the LastName
       */
      public String getLastName() {
        return m_lastName;
      }

      /**
       * @param lastName
       *          the LastName to set
       */
      public void setLastName(String lastName) {
        m_lastName = lastName;
      }

      /**
       * @return the Company
       */
      public String getCompany() {
        return m_company;
      }

      /**
       * @param company
       *          the Company to set
       */
      public void setCompany(String company) {
        m_company = company;
      }
    }
  }

  public static class Phone extends AbstractPhoneFieldData {

    private static final long serialVersionUID = 1L;

    public Phone() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class Starts extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;

    public Starts() {
    }
  }

  public static class Title extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Title() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }
}