ifndef::finaldoc[]
include::../_initDoc.adoc[]
endif::finaldoc[]

//fallback for safe mode == secure:
:imgsdir: ../../imgs
:codedir: ../../../code
ifndef::mdledir[:mdledir: .]
:experimental:

=== How to integrate https://www.chartjs.org/[ChartJS] in a ScoutJS SPA
This cheat sheet shows how to integrate ChartJS charts into a ScoutJS single page application (SPA).

==== Prerequisites
* ScoutJS project: Use the archetype to create a new project.

==== Include ChartJs library
https://github.com/chartjs/Chart.js/releases/latest[Download] the latest version of ChartJS. On the bottom of the page you will find the 'Assets'. From there you can pick the `Chart.js` and `Chart.css` files and put them into the filder `/helloworld.ui/src/main/resources/WebContent/res`.

Include ChartJS to the SPA by adding:


/helloworld.app/src/main/resources/WebContent/res/libs-all-macro.js
[source,js]
----
__include("Chart.js");
----

/helloworld.app/src/main/resources/WebContent/res/libs-all-macro.less
[source,css]
----
@import "Chart.css"
----

==== Create a Chart Widget
WARNING: The library under `/helloworld.ui/src/main/resources/WebContent/res/Chart.js` and the widget under `/helloworld.ui/src/main/js/helloworld/chart/Chart.js` do have the same filename. Take care to not mix them up. From this point in the cheat sheet we are only talking about the Chart.js as widget.

/helloworld.ui/src/main/js/helloworld/chart/Chart.js
[source,js]
----
helloworld.Chart = function() {
  helloworld.Chart.parent.call(this);
  this.chart = null;
  this.chartConfig = null;
};
scout.inherits(helloworld.Chart, scout.Widget); <!--1-->

helloworld.Chart.prototype._init = function(model) {
  helloworld.Chart.parent.prototype._init.call(this, model);
  var defaultConfig = { <!--2-->
    options: {
      elements: {
        arc: {
          borderWidth: 1
        }
      },
      layout: {
        padding: {
          left: 20,
          right: 20,
          top: 20,
          bottom: 20
        }
      }
    }
  };
  this.chartConfig = $.extend(true, defaultConfig, model.chartConfig); <!--3-->
};

helloworld.Chart.prototype._render = function() {
  this.$container = this.$parent.appendElement('<canvas>', 'chart');
  this.chart = new Chart(this.$container[0], this.chartConfig); <!--4-->

  // render Properties
  this._renderChartData();
};

helloworld.Chart.prototype.setChartData = function(chartData) { <!--5-->
  this.setProperty('chartData', chartData);
};

helloworld.Chart.prototype._renderChartData = function() { <!--6-->
  if (!this.chartData) {
    return;
  }
  this.chartConfig.data = this.chartData;
  this.chart.update();
};

----
<1> `Chart` inherits from `Widget`
<2> Create a default config. The default config contains properties valid for all charts in your application.
<3> Extend the default config with the config received from the model.
<4> Create a ChartJS instance on the above created canvas.
<5> This function is used to set the data series.
<6> Updates the chart with the data series and update the chart.


