
ifndef::finaldoc[]
include::../_initDoc.adoc[]
endif::finaldoc[]

//fallback for safe mode == secure:
:imgsdir: ../../imgs
:codedir: ../../../code
ifndef::mdledir[:mdledir: .]
:experimental:

//-----------------------------------------------------------------------------
// This file describes the architecture of RunContext
//-----------------------------------------------------------------------------

= JobManager
Scout provides a job manager based on Java Executors framework to smoothly integrate concurrent execution into Scout application. The following bullets gives a brief overview of its core functionality:

* asynchronous work is given to the job manager in the form of a Callable or Runnable, and is called a job
* interaction with an in-progress job is done with its Future, e.g. to cancel the job or to wait for its completion
* a job can be scheduled with a delay, meaning that execution only starts once the delay elapsed
* a job can be scheduled as periodic action at a fixed rate, or with a fixed delay
* a job can be configured to run in sequence among other jobs (mutual exclusion)
* a job can be given a `RunContext` to run on behalf
* a job's Future is associated with the `RunMonitor` as provided by `RunContext`, and is cancelled as well once the `RunMonitor` is cancelled
* the job manager is based on a thread pool with support for 'core-pool-size', 'maximum-pool-size' and 'keep-alive-time'
* support to wait for blocking conditions
* support to listen for job lifecycle events based on filters
* support to wait for jobs to complete based on filters
* support to visit running jobs based on filters
* support for named threads
* there is one job manager per platform
* factories facilitate job scheduling based on the current calling context

== Job
A job is defined as some work to be executed asynchronously and is associated with a `JobInput` to describe how to run that work. The work is encapsulated in the form of a `Runnable` or `Callable`. The only difference is, that a `Runnable` represents  a 'fire-and-forget' action, meaning that the submitter of the job does not expect the job to return a result. On the other hand, a `Callable` returns the computation's result, which the submitter can wait for. Of course, a runnable's completion can also be waited for.

[source,java,indent=0]
.Work that does not return a result
----
include::{codedir}/org.eclipse.scout.docs.snippets/src/main/java/org/eclipse/scout/docs/snippets/JobManagerSnippet.java[tags=IRunnable]
----
[source,java,indent=0]
.Work that returns a computation result
----
include::{codedir}/org.eclipse.scout.docs.snippets/src/main/java/org/eclipse/scout/docs/snippets/JobManagerSnippet.java[tags=Callable]
----

Any uncaught exception thrown during the jobs's execution is available to the submitter by the associated `IFuture`, and is wrapped into a `ProcessingException`.

While executing a long-running operation, it is good practice to query the job's cancellation status from time to time. That can either be done by the associated `RunMonitor` or `IFuture`. However, querying the `RunMonitor` for cancellation is the preferred way, because being available when running inside a job as well as when running outside a job. +

[source,java,indent=0]
.Query for cancellation
----
include::{codedir}/org.eclipse.scout.docs.snippets/src/main/java/org/eclipse/scout/docs/snippets/JobManagerSnippet.java[tags=queryCancellationStatus]
----

TIP: Jobs can be cancelled 'hard' or 'soft'. 'Hard' means, that you are interrupted when waiting for a monitor to be acquired.

== Future
A future represents the result of an asynchronous computation, and is returned once scheduling a job. The future provides functionality to await for the job to complete, or to get its computation result or exception, or to attempt to cancel execution. If the job was instrumented to run on behalf of a `RunContext`, its `RunMonitor` is associated with the job's `Future`, meaning that cancellation of the `Future` or `RunMonitor` is equivalent.

If you are running within a job, the associated `IFuture` can be obtained as following:
[source,java,indent=0]
----
include::{codedir}/org.eclipse.scout.docs.snippets/src/main/java/org/eclipse/scout/docs/snippets/JobManagerSnippet.java[tags=obtainAssociatedFuture]
----

The following list describes the core functionality of the `IFuture`:

[cols="10,90"]
|===
|method |description

|cancel(interrupt)
|Attempts to cancel the execution of the associated job. The boolean argument controls whether to interrupt the worker thread, meaning that it is interrupted if waiting for monitor to be acquired.

|isCancelled()
|To query if the associated job was cancelled before it completed normally.

|isDone()
|To query if the associated job completed either normally, by an exception or was canceled.

|isBlocked()
|To query if the associated job is waiting for a blocking condition to fall.

|* awaitDone() +
 * awaitDone(timeout, unit)
|Waits if necessary for the job to complete, or until cancelled, or the timeout elapses. This method does not throw an exception if cancelled, or the timeout elapses, or the computation failed.

|* awaitDoneAndGet() +
 * awaitDoneAndGet(timeout, unit)
|Waits if necessary for the computation to complete, and then retrieves its result. In case of a computation exception, that exception is thrown in the form of a `ProcessingException`.
However, if the job was cancelled, or the waiting thread interrupted, or the optional timeout elapsed, this method throws a `ProcessingException` with the corresponding flag set.

|whenDone(callback)
|Registers the given callback to be notified once the Future enters 'done' state. That is once the associated job completes successfully or with an exception, or was cancelled. Thereby, the callback is invoked in any thread with no `RunContext` applied. If the job is already in 'done' state when the callback is registered, the callback is invoked immediately.
|===


== JobInput
When scheduling a job, a `JobInput` must be provided in order to describe the job, and to instruct the job manager of how to run the job. The following properties are supported:

[cols="30%,70%"]
|===
|name
|The name of the job, which is used for logging purpose and to name the executing thread.

|expiration{nbsp}time
|The maximal expiration time, until the job must commence execution. If elapsed, the executable is cancelled and never commence execution. This is useful when using a scheduling strategy which might queue scheduled executables prior execution. By default, there is no expiration time set.

|mutex{nbsp}object +
(mutual{nbsp}exclusion)
|To run the job in sequence among other jobs with the same mutex object, so that no two such jobs are run in parallel at the same time. By default, no mutex object is set, meaning the job is not executed in mutually exclusive manner.

|thread{nbsp}name
|To name the worker thread that will execute the job.

|logOnError
|Instruments the job manager to log uncaught exceptions on behalf of the installed `ExceptionHandler`. That is enabled by default, but might be disabled, if the caller handles exceptions himself by waiting for the job to complete (`IFuture.awaitDoneAndGet()`).

|runContext
|Sets the `RunContext` to be applied during job execution. Also, the context's `RunMonitor` is associated with the jobs's Future, meaning that cancellation requests to the `Future` or `RunContext` are equivalent. +
However, if no context is provided, the job manager ensures a `RunMonitor` to be installed, so that executing code can always query the cancellation status by `RunMonitor.CURRENT.get().isCancelled()`.
|===

== Scheduling a Job
A job is scheduled by being given to the job manager for execution. The manager itself is registered as _applicationScoped_ Bean within the platform. As mentioned in the previous paragraphs, the job is made up of two parts: the input and the executable. The following listing shows how to schedule a job.

[source,java,indent=0]
.Schedule a job
----
include::{codedir}/org.eclipse.scout.docs.snippets/src/main/java/org/eclipse/scout/docs/snippets/JobManagerSnippet.java[tags=scheduleByJobManager]
----
<1> Obtain the job manager from the platform
<2> Create a new job input to describe the job
<3> Give the job a name and `RunContext` to be applied once running
<4> Give the job with its input to the job manager for execution

That looks a little bit clumsy, with lot of code to simply run some code asynchronously. And things are getting worse if scheduling model jobs which require to be executed in sequence. That is why Scout provides you with some convenience in the form of static factory methods. They are based on the convention, that if providing no input, a new input initialized with a copy of the current calling context is used.

There exist a factory for each kind of job:
[cols="10%,90%"]
|===
|Factory |Description

|Jobs
|Use this factory to schedule jobs that do not require to run on a specific `RunContext`, or do not require a context at all.

|ServerJobs
|Use this factory to schedule jobs that require to run on a `ServerRunContext`.

|ClientJobs
|Use this factory to schedule jobs that require to run on a `ClientRunContext`.

|ModelJobs
|Use this factory to schedule jobs that write to the Scout client model and therefore are required to run on a `ClientRunContext` and in sequence. A model job guarantees that at no time two model jobs are running in parallel. Technically, such jobs are instrumented with a mutex, which corresponds to the caller's client session.
|===

[source,java,indent=0]
.Schedule a job by use of job factory
----
include::{codedir}/org.eclipse.scout.docs.snippets/src/main/java/org/eclipse/scout/docs/snippets/JobManagerSnippet.java[tags=scheduleByFactory]
----
<1> Schedules a job associated with the current `RunContext`
<2> Schedules a job associated with the current `RunContext` and with a specific job name

== Scheduling periodic actions
The job manager supports work to be executed periodically. There are two modes for a period action to be scheduled:

* _at fixed rate:_ +
Use this mode to run a job at a fixed rate, e.g. every two seconds. If a run takes longer than the delay, the next run is started immediately once the previous run completes. At any time, there is only one 'run' running.
* _with fixed delay:_ +
Use this mode to run a job with a fixed delay in between of the completion of the previous run and the start of the next run.

[source,java,indent=0]
.Schedule a job at a fixed rate
----
include::{codedir}/org.eclipse.scout.docs.snippets/src/main/java/org/eclipse/scout/docs/snippets/JobManagerSnippet.java[tags=Jobs.scheduleAtFixedRate]
----

* A periodic action is either stopped by canceling its `IFuture`, or by throwing an exception during execution.
* When scheduling a periodic action, a `JobInput` must be provided explicitly. That is because typically being a background job which is run as a particular user and with a dedicated `ISession`.

== Scheduling of delayed jobs
A job must not start execution immediately once being given to the job manager. Instead, a _delay_ can be provided to execute a job only after the given delay elapsed.

[source,java,indent=0]
.Schedule a job to be executed after a delay
----
include::{codedir}/org.eclipse.scout.docs.snippets/src/main/java/org/eclipse/scout/docs/snippets/JobManagerSnippet.java[tags=Jobs.scheduleDelayed]
----

== Blocking condition
A blocking condition allows a thread to wait for a condition to become `true`. That is similar to the Java Object's 'wait/notify' mechanism, but with some additional functionality regarding mutual exclusive jobs. In case of such a job enters a blocking condition, it releases ownership of the mutex, which allows another job of the same mutex to begin execution. Hence, the job must compete for the mutex anew once the blocking condition falls. However, the condition can be used by any thread, and that thread must not be managed by the job manager.

A blocking condition is often used by model jobs to wait for something to happen, but to allow other model jobs to run while waiting. A typical use case is to wait for a `MessageBox` to be closed.


[source,java,indent=0]
.Example usage of a blocking condition
----
include::{codedir}/org.eclipse.scout.docs.snippets/src/main/java/org/eclipse/scout/docs/snippets/JobManagerSnippet.java[tags=BlockingCondition]
----
<1> Create the blocking condition to wait for the long running operation to complete.
<2> Schedule the long running operation.
<3> Register a 'done callback' to be notified once the job completes. If the job already completed, the callback is invoked immediately.
<4> Cause the current thread to wait for maximal one minute for the condition to become 'unblocked'. That is once the long running operation completes. If already completed, the condition does not block the current thread.
<5> Callback invoked upon completion of the job. Change the blocking state of the condition to release the waiting thread.
<6> This code is executed once the long running operation completed.

== Lifecycle events
The job managers allows registration of listeners to be notified upon job lifecycle changes. Thereto, a filter must be provided to indicate in what events you are interested in. The filter must implement `IFilter` interface, and has a single method to accept such lifecyle events. If accepted by the filter, the event is propagated to the listener. +
Scout provides you with some 'ready-to-go' filters and some convenience to concatenate filters with a logical 'AND' operator. For example, you can create a filter to only accept events of server jobs of your current session, and jobs with a name that match a regular expression.


Such filters are created from a factory and profit from method chaining



== Wait for jobs to complete

== Visit running jobs

== Configuration

== Blocking condition

== Implementation details

