/**
 * 
 */
package org.eclipsescout.contacts.shared.premium.ui.forms;

import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.commons.annotations.Extends;
import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.tablefield.AbstractTableFieldBeanData;
import org.eclipsescout.contacts.shared.ContactFormData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Extends(ContactFormData.class)
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ContactFormTabExtensionData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  public ContactFormTabExtensionData() {
  }

  public Events getEvents() {
    return getFieldByClass(Events.class);
  }

  public static class Events extends AbstractTableFieldBeanData {

    private static final long serialVersionUID = 1L;

    public Events() {
    }

    @Override
    public EventsRowData addRow() {
      return (EventsRowData) super.addRow();
    }

    @Override
    public EventsRowData addRow(int rowState) {
      return (EventsRowData) super.addRow(rowState);
    }

    @Override
    public EventsRowData createRow() {
      return new EventsRowData();
    }

    @Override
    public Class<? extends AbstractTableRowData> getRowType() {
      return EventsRowData.class;
    }

    @Override
    public EventsRowData[] getRows() {
      return (EventsRowData[]) super.getRows();
    }

    @Override
    public EventsRowData rowAt(int index) {
      return (EventsRowData) super.rowAt(index);
    }

    public void setRows(EventsRowData[] rows) {
      super.setRows(rows);
    }

    public static class EventsRowData extends AbstractTableRowData {

      private static final long serialVersionUID = 1L;
      public static final String id = "id";
      public static final String title = "title";
      public static final String starts = "starts";
      public static final String city = "city";
      public static final String country = "country";
      private String m_id;
      private String m_title;
      private Date m_starts;
      private String m_city;
      private String m_country;

      public EventsRowData() {
      }

      /**
       * @return the Id
       */
      public String getId() {
        return m_id;
      }

      /**
       * @param id
       *          the Id to set
       */
      public void setId(String id) {
        m_id = id;
      }

      /**
       * @return the Title
       */
      public String getTitle() {
        return m_title;
      }

      /**
       * @param title
       *          the Title to set
       */
      public void setTitle(String title) {
        m_title = title;
      }

      /**
       * @return the Starts
       */
      public Date getStarts() {
        return m_starts;
      }

      /**
       * @param starts
       *          the Starts to set
       */
      public void setStarts(Date starts) {
        m_starts = starts;
      }

      /**
       * @return the City
       */
      public String getCity() {
        return m_city;
      }

      /**
       * @param city
       *          the City to set
       */
      public void setCity(String city) {
        m_city = city;
      }

      /**
       * @return the Country
       */
      public String getCountry() {
        return m_country;
      }

      /**
       * @param country
       *          the Country to set
       */
      public void setCountry(String country) {
        m_country = country;
      }
    }
  }
}