////
Howto:
- Write this document such that it helps people to migrate. Describe what they should do.
- Chronological order is not necessary.
- Choose the right top level chapter (java, js, other)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////

== About This Document

This document describes all relevant changes *from Eclipse Scout {scout-previous-version} to Eclipse Scout {scout-version}*. If existing code has to be migrated, instructions are provided here.

== Obtaining the Latest Version

=== Scout Runtime for Java

Scout Runtime artifacts for Java are distributed using Maven Central:

* {maven-central-link} on _Maven Central_
* {mvnrepository-link} on _mvnrepository.com_

Usage example in the parent POM of your Scout application:

[source,xml]
[subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.eclipse.scout.rt</groupId>
    <artifactId>org.eclipse.scout.rt</artifactId>
    <version>{maven-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

=== Scout Runtime for JavaScript

Scout Runtime artifacts for JavaScript are distributed using npm:

* https://www.npmjs.com/package/@eclipse-scout/core[Scout Core Runtime]
* https://www.npmjs.com/search?q=%40eclipse-scout[All official Scout JavaScript packages]

Usage example in your package.json:

[source,json]
[subs="verbatim,attributes"]
----
{
  "name": "my-module",
  "version": "1.0.0",
  "devDependencies": {
    "@eclipse-scout/cli": "{node-version}",
    "@eclipse-scout/releng": "~26.2.0"
  },
  "dependencies": {
    "@eclipse-scout/core": "{node-version}",
    "jquery": "3.7.1"
  }
}
----

The pre-built Scout JavaScript assets are also available using a CDN (e.g. to be directly included in a html document):
https://www.jsdelivr.com/package/npm/@eclipse-scout/core?path=dist

=== IDE Tooling (Scout SDK)

Scout officially supports https://www.jetbrains.com/idea/[IntelliJ IDEA] and {scout-sdk-download-link}.

==== IntelliJ IDEA

You can download the Scout plugin for IntelliJ IDEA from the https://plugins.jetbrains.com/plugin/13393-eclipse-scout/[JetBrains Plugin Repository] or you can use the plugins client built into IntelliJ IDEA.
Please refer to the https://www.jetbrains.com/help/idea/managing-plugins.html[IntelliJ Help] on how to install and manage plugins.

==== Eclipse

You can download the complete Eclipse IDE with Scout SDK included here: +
{scout-sdk-download-link}

To install the Scout SDK into your existing Eclipse IDE, use this P2 update site: +
{scout-sdk-update-site}

// ----------------------------------------------------------------------------

== New Build & Runtime Requirements

Scout 27.1 requires at least the following:

* Build and runtime of Scout 27.1 require Java 25. The compiler target level is set to Java 21.
* Furthermore, the build requires
** Node: >= 24.12.0
** Pnpm: >= 10.26.1

== Batch Support for Scout JS Columns

The batch support for `Columns` has been improved (see the xref:release-notes.adoc#batch-support[release notes] for details).

The signature for the following functions changed:

* `Column.formatValue`, `Column.formatter` and `Column._formatValue`: Now returns `string | JQuery.Promise<BatchCallResult<TValue, unknown>>` returning all key-value-mappings in the batched async case.
* `Column.setCellTextDeferred` now expects this `JQuery.Promise<BatchCallResult<TValue, unknown>>` as argument for the async case. The `row` and `cell` arguments have been deleted as such a call is no longer executed for each row, but once for all rows.
+
To access or modify the new value by cell or row use `_batchFormatResultToCellText` which will be called for each row in the batch result.

The `StaticLookupCall` and `LookupColumn` have batching enabled now by default.
This means all `StaticLookupCalls` and all `LookupColumns` using a batch-enabled `LookupCall` (like `StaticLookupCall` now) do no longer get the `row` argument in the `prepareLookupCall` event (as they are batched now for several rows).
So if you make use of the `row` property in a `prepareLookupCall` event listener, you have to do one of the following:

* If possible: Change the listener implementation so that the row is no longer required.
* Set the `batch` property of the `LookupCall` to `false`. Then the old behavior without batching is applied in which the row is passed to the listener again. Please note that this is not recommended for large tables as it is much slower!
