////
Howto:
- Write this document such that it helps people to migrate. Describe what they should do.
- Chronological order is not necessary.
- Choose the right top level chapter (java, js, other)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////

== About This Document

This document describes all relevant changes *from Eclipse Scout {scout-previous-version} to Eclipse Scout {scout-version}*. If existing code has to be migrated, instructions are provided here.

== Obtaining the Latest Version

=== Scout Runtime for Java

Scout Runtime artifacts for Java are distributed using Maven Central:

* {maven-central-link} on _Maven Central_
* {mvnrepository-link} on _mvnrepository.com_

Usage example in the parent POM of your Scout application:

[source,xml]
[subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.eclipse.scout.rt</groupId>
    <artifactId>org.eclipse.scout.rt</artifactId>
    <version>{maven-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

=== Scout Runtime for JavaScript

Scout Runtime artifacts for JavaScript are distributed using npm:

* https://www.npmjs.com/package/@eclipse-scout/core[Scout Core Runtime]
* https://www.npmjs.com/search?q=%40eclipse-scout[All official Scout JavaScript packages]

Usage example in your package.json:

[source,json]
[subs="verbatim,attributes"]
----
{
  "name": "my-module",
  "version": "1.0.0",
  "devDependencies": {
    "@eclipse-scout/cli": "{node-version}",
    "@eclipse-scout/releng": "^26.2.0"
  },
  "dependencies": {
    "@eclipse-scout/core": "{node-version}",
    "jquery": "3.7.1"
  }
}
----

The pre-built Scout JavaScript assets are also available using a CDN (e.g. to be directly included in a html document):
https://www.jsdelivr.com/package/npm/@eclipse-scout/core?path=dist

=== IDE Tooling (Scout SDK)

Scout officially supports https://www.jetbrains.com/idea/[IntelliJ IDEA] and {scout-sdk-download-link}.

==== IntelliJ IDEA

You can download the Scout plugin for IntelliJ IDEA from the https://plugins.jetbrains.com/plugin/13393-eclipse-scout/[JetBrains Plugin Repository] or you can use the plugins client built into IntelliJ IDEA.
Please refer to the https://www.jetbrains.com/help/idea/managing-plugins.html[IntelliJ Help] on how to install and manage plugins.

==== Eclipse

You can download the complete Eclipse IDE with Scout SDK included here: +
{scout-sdk-download-link}

To install the Scout SDK into your existing Eclipse IDE, use this P2 update site: +
{scout-sdk-update-site}

// ----------------------------------------------------------------------------

== REST operations: Add Consumes annotation

It is recommended that all REST operations which consume a request entity body message have a `Consumes` annotation set to restrict invalid input.
Therefore, a test has been added which fails if there are such operations which do not have a `Consumes` annotation.
The `AbstractRestResourceAnnotationTest` has to be extended in your modules to run this test.

== REST resources: Explicit `@Path` annotation required

It is recommended that all REST resource classes explicitly declare a `@Path` annotation.

According to the Jakarta RESTful Web Services specification, JAX-RS annotations — including `@Path` — are not inherited from superclasses or interfaces.
While Jersey, the implementation we use, does attempt to locate a `@Path` annotation on parent classes, this behavior is not defined by the specification and should not be relied upon.

To ensure compliance, a test has been introduced that fails if any REST resource is missing a `@Path` annotation.
To activate this validation for your module, extend the `AbstractRestResourceAnnotationTest` class accordingly.

== Removal of autoPrefixWildcardForTextSearch on Desktop

The methods `isAutoPrefixWildcardForTextSearch` and `setAutoPrefixWildcardForTextSearch` on `IDesktop` have been removed.
They have not been used since years and were never supported in Scout JS.

If you need a prefix wildcard, add it to your search texts manually where required.

== AbstractRestLookupCall moved to shared module

`AbstractRestLookupCall` was moved from the client to the shared module:
`org.eclipse.scout.rt.client.services.lookup.AbstractRestLookupCall` -> `org.eclipse.scout.rt.shared.services.lookup.AbstractRestLookupCall`.

== SmtpConnectionPool: Connection error/idle handling

For the `org.eclipse.scout.rt.mail.smtp.SmtpConnectionPool` in the past idle timeouts could be defined in seconds.
However, connections were only checked once per minute, hence idle timeouts less than one minute were not respected.
This check interval has been decreased from one minute to 20 seconds (default value), it is now configurable by config property `scout.smtp.pool.closeIdleConnectionsJobSchedule`.
Also the default idle timeout has been decreased from one minute to 20 seconds (existing config property `scout.smtp.pool.maxIdleTime`).

Also the connection error handling has been changed, connection error codes 421 and 451 are now also treated as failed connection (according to RFC 5312 3.8 connection failures and at least error codes 451 should be treated the same way).

[#tree-scout-js-api-of-visitnodes-changed]
== Tree (Scout JS): API of VisitNodes Changed

Returning `true` in a visitor used for `Tree.visitNodes` now stops visiting completely instead of just skipping the subtree, see also xref:release-notes.adoc#tree-scout-js-findnode-added-and-visitnodes-improved[Release Notes].

Please check your JavaScript / TypeScript code for occurrences of `visitNodes` and if the visitor explicitly returns `true`, replace it with `TreeVisitResult.SKIP_SUBTREE`.

[source,typescript,opts=novalidate]
.Old
----
tree.visitNodes(node => {
  return true;
});
----

[source,typescript,opts=novalidate]
.New
----
tree.visitNodes(node => {
  return TreeVisitResult.SKIP_SUBTREE;
});
----


