////
Howto:
- Write this document such that it helps people to migrate. Describe what they should do.
- Chronological order is not necessary.
- Choose the right top level chapter (java, js, other)
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////

== About This Document

This document describes all relevant changes *from Eclipse Scout {scout-previous-version} to Eclipse Scout {scout-version}*. If existing code has to be migrated, instructions are provided here.

WARNING: {NotReleasedWarning}

== Obtaining the Latest Version

=== Scout Runtime for Java

Scout Runtime artifacts for Java are distributed using Maven Central:

* {maven-central-link} on _Maven Central_
* {mvnrepository-link} on _mvnrepository.com_

Usage example in the parent POM of your Scout application:

[source,xml]
[subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.eclipse.scout.rt</groupId>
    <artifactId>org.eclipse.scout.rt</artifactId>
    <version>{maven-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

=== Scout Runtime for JavaScript

Scout Runtime artifacts for JavaScript are distributed using npm:

* https://www.npmjs.com/package/@eclipse-scout/core[Scout Core Runtime]
* https://www.npmjs.com/search?q=%40eclipse-scout[All official Scout JavaScript packages]

Usage example in your package.json:

[source,json]
[subs="verbatim,attributes"]
----
{
  "name": "my-module",
  "version": "1.0.0",
  "devDependencies": {
    "@eclipse-scout/cli": "{node-version}",
    "@eclipse-scout/releng": "^22.0.0"
  },
  "dependencies": {
    "@eclipse-scout/core": "{node-version}",
    "jquery": "3.6.0"
  }
}
----

The pre-built Scout JavaScript assets are also available using a CDN (e.g. to be directly included in a html document):
https://www.jsdelivr.com/package/npm/@eclipse-scout/core?path=dist

=== IDE Tooling (Scout SDK)

Scout officially supports https://www.jetbrains.com/idea/[IntelliJ IDEA] and {scout-sdk-download-link}.

==== IntelliJ IDEA

You can download the Scout plugin for IntelliJ IDEA from the https://plugins.jetbrains.com/plugin/13393-eclipse-scout/[JetBrains Plugin Repository] or you can use the plugins client built into IntelliJ IDEA.
Please refer to the https://www.jetbrains.com/help/idea/managing-plugins.html[IntelliJ Help] on how to install and manage plugins.

==== Eclipse

You can download the complete Eclipse IDE with Scout SDK included here: +
{scout-sdk-download-link}

To install the Scout SDK into your existing Eclipse IDE, use this P2 update site: +
{scout-sdk-update-site}

// ----------------------------------------------------------------------------

== Utilities

=== DateUtility: New Default Date Time Format

Since this version, the method `DateUtility#formatDateTime` returns the date formatted with the `DateFormat.DEFAULT` and no longer with the `DateFormat.SHORT`.
Now, both methods, `DateUtility#formatDate` and `DateUtility#formatDateTime`, are formatting the date identically.
To apply the old formatting, use `DateUtility#formatDateTimeShort`.

=== New ExceptionUtility

A set of utility methods dealing with `Exception` and `Throwable` were moved and added to the new `ExceptionUtility`.

Change invocations of `org.eclipse.scout.rt.platform.exception.ExceptionHandler.getRootCause()`
to the new utility method  `org.eclipse.scout.rt.platform.util.ExceptionUtility.getRootCause()`.

== Adapted REST ErrorDoRestClientExceptionTransformer

The transformation logic for exceptions which occur while invoking a REST client was slightly adapted.
For HTTP error codes 502 (bad gateway), 503 (service unavailable) and 504 (gateway timeout) the adapted `ErrorDoRestClientExceptionTransformer` returns a `org.eclipse.scout.rt.platform.exception.RemoteSystemUnavailableException` instead of the former generic `org.eclipse.scout.rt.platform.exception.ProcessingException`.

== Removed Deprecated Code

The following functions were deprecated in a previous release and are now removed completely.

* TabBox.ts: `selectTabById`, replaced by `setSelectedTab`
* JQueryMouseWheelEvent: instead of using `DOMMouseScroll mousewheel` events use `wheel` and JQueryWheelEvent type
* Menu.ts: `addChildActions`, replaced by `insertChildActions`
* Widget.ts: `_isRemovalPending`, replaced by `isRemovalPending`
* CompositeFieldUtility.java: `moveFieldTo`, third parameter removed
* AbstractExtensionChain.java: `callChain`, vararg removed
* AbstractDataModelOperatorField.java: setAttribute, second parameter is not optional anymore
* FocusManager.ts: `requestFocus` does not accept a boolean anymore as third parameter

== Removal of Public Holiday Calendar Support

A few classes used to read public holidays from an XML file and providing them to the calendar were removed without replacement:

** `org.eclipse.scout.rt.client.ui.basic.calendar.provider.AbstractHolidayItemProvider`
** `org.eclipse.scout.rt.shared.services.common.calendar.IHolidayCalendarService`
** `org.eclipse.scout.rt.server.services.common.calendar.HolidayCalendarService`
** `org.eclipse.scout.rt.shared.services.common.calendar.HolidayItem`
** `org.eclipse.scout.rt.shared.services.common.calendar.HolidayCalendarItemParser`

== Scout JS

=== Tree: Insert Order Changed

`Tree.insertNodes` now adds new nodes (without an explicit childNodeIndex) at the bottom of the existing nodes instead of the top.
This is already the case for the Scout Classic tree, and also for other widgets like table and tile grid.

To insert the nodes at the beginning or any other position, you can use the new parameter `index`.

=== Form

==== Modal Optional for Views

The default value for the `modal` property has been changed for forms with `displayStyle` = `Form.DisplaStyle.VIEW`, see xref:releasenotes:release-notes.adoc#modal-optional-for-views[Release Notes].
