////
Howto:
- Write this document such that it helps people to migrate. Describe what they should do.
- Chronological order is not necessary.
- Choose the right top level chapter (java, js, other)
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////

== About This Document

This document describes all relevant changes *from Eclipse Scout {scout-previous-version} to Eclipse Scout {scout-version}*. If existing code has to be migrated, instructions are provided here.

WARNING: {NotReleasedWarning}

== Obtaining the Latest Version

=== Scout Runtime for Java

Scout Runtime artifacts for Java are distributed using Maven Central:

* {maven-central-link} on _Maven Central_
* {mvnrepository-link} on _mvnrepository.com_

Usage example in the parent POM of your Scout application:

[source,xml]
[subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.eclipse.scout.rt</groupId>
    <artifactId>org.eclipse.scout.rt</artifactId>
    <version>{maven-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

=== Scout Runtime for JavaScript

Scout Runtime artifacts for JavaScript are distributed using npm:

* https://www.npmjs.com/package/@eclipse-scout/core[Scout Core Runtime]
* https://www.npmjs.com/search?q=%40eclipse-scout[All official Scout JavaScript packages]

Usage example in your package.json:

[source,json]
[subs="verbatim,attributes"]
----
{
  "name": "my-module",
  "version": "1.0.0",
  "devDependencies": {
    "@eclipse-scout/cli": "{node-version}",
    "@eclipse-scout/releng": "^25.1.0"
  },
  "dependencies": {
    "@eclipse-scout/core": "{node-version}",
    "jquery": "3.7.1"
  }
}
----

The pre-built Scout JavaScript assets are also available using a CDN (e.g. to be directly included in a html document):
https://www.jsdelivr.com/package/npm/@eclipse-scout/core?path=dist

=== IDE Tooling (Scout SDK)

Scout officially supports https://www.jetbrains.com/idea/[IntelliJ IDEA] and {scout-sdk-download-link}.

==== IntelliJ IDEA

You can download the Scout plugin for IntelliJ IDEA from the https://plugins.jetbrains.com/plugin/13393-eclipse-scout/[JetBrains Plugin Repository] or you can use the plugins client built into IntelliJ IDEA.
Please refer to the https://www.jetbrains.com/help/idea/managing-plugins.html[IntelliJ Help] on how to install and manage plugins.

==== Eclipse

You can download the complete Eclipse IDE with Scout SDK included here: +
{scout-sdk-download-link}

To install the Scout SDK into your existing Eclipse IDE, use this P2 update site: +
{scout-sdk-update-site}

// ----------------------------------------------------------------------------

== Table: column.sortActive Can Be Removed if sortIndex Is Set (Scout JS)

For Scout JS tables, `sortActive` is now automatically set to true if `sortIndex` is >= 0.
This means you can remove `sortActive: true` from your model files if you set a valid `sortIndex`.

[source,js]
.Old
----
{
  objectType: Column,
  sortActive: true,
  sortIndex: 0
}
----

[source,js]
.New
----
{
  objectType: Column,
  sortIndex: 0
}
----

[[gzipfilter-deprecated]]
== Deprecation of `GzipServletFilter` and `LegacyGzipServletFilter`

`org.eclipse.scout.rt.server.commons.servlet.filter.gzip.GzipServletFilter` and
`org.eclipse.scout.rt.server.commons.servlet.filter.gzip.LegacyGzipServletFilter` have been deprecated and should not be used anymore.
Among other things these filters do not support async requests which are used in some parts of the application.
If an applications keeps using the deprecated filters a warning will be logged during initialization of these classes.

Instead of these filters the Jetty built-in `org.eclipse.jetty.server.handler.gzip.GzipHandler` should be used.
This handler has been added to the main class `org.eclipse.scout.rt.app.Application` and is enabled by default.

It may be configured and also disabled using several new configuration properties:

* `scout.app.gzip.enabled`: Boolean (default: true); specifies whether the `GzipHandler` is used
* `scout.app.gzip.excluded.inflate.paths`: List of String; excluded inflate paths for `GzipHandler` (respected only if at least one is set otherwise Jetty default is used)
* `scout.app.gzip.excluded.methods`: List of String; excluded methods for `GzipHandler` (respected only if at least one is set otherwise Jetty default is used)
* `scout.app.gzip.excluded.mimeTypes`: List of String; excluded MIME types for `GzipHandler` (respected only if at least one is set otherwise Jetty default is used)
* `scout.app.gzip.excluded.paths`: List of String; excluded paths for `GzipHandler` (respected only if at least one is set otherwise Jetty default is used)
* `scout.app.gzip.included.inflate.paths`: List of String; included inflate paths for `GzipHandler` (respected only if at least one is set otherwise Jetty default is used)
* `scout.app.gzip.included.methods`: List of String; included methods for `GzipHandler` (respected only if at least one is set otherwise Jetty default is used)
* `scout.app.gzip.included.mimeTypes`: List of String; included MIME types for `GzipHandler` (respected only if at least one is set otherwise Jetty default is used)
* `scout.app.gzip.included.paths`: List of String; included paths for `GzipHandler` (respected only if at least one is set otherwise Jetty default is used)
* `scout.app.gzip.minSize`: Positive integer; minimum size to trigger compression for `GzipHandler` (respected only if at value is set otherwise Jetty default is used)
* `scout.app.gzip.syncFlush`: Boolean (default: true); enables sync flush for `GzipHandler`

If the application is not run using the recommended main class `org.eclipse.scout.rt.app.Application`, e.g. for .war deployments the `GzipHandler` is not registered automatically.
For example for a Jetty .war deployment it may be registered by activating the `gzip` Jetty module.
