////
Howto:
- Write this document such that it helps people to migrate. Describe what they should do.
- Chronological order is not necessary.
- Choose the right top level chapter (java, js, other)
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////

== About This Document

This document describes all relevant changes *from Eclipse Scout {scout-previous-version} to Eclipse Scout {scout-version}*. If existing code has to be migrated, instructions are provided here.

WARNING: {NotReleasedWarning}

== Obtaining the Latest Version

=== Scout Runtime for Java

Scout Runtime artifacts for Java are distributed using Maven Central:

* {maven-central-link} on _Maven Central_
* {mvnrepository-link} on _mvnrepository.com_

Usage example in the parent POM of your Scout application:

[source,xml]
[subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.eclipse.scout.rt</groupId>
    <artifactId>org.eclipse.scout.rt</artifactId>
    <version>{maven-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

=== Scout Runtime for JavaScript

Scout Runtime artifacts for JavaScript are distributed using npm:

* https://www.npmjs.com/package/@eclipse-scout/core[Scout Core Runtime]
* https://www.npmjs.com/search?q=%40eclipse-scout[All official Scout JavaScript packages]

Usage example in your package.json:

[source,json]
[subs="verbatim,attributes"]
----
{
  "name": "my-module",
  "version": "1.0.0",
  "devDependencies": {
    "@eclipse-scout/cli": "{node-version}",
    "@eclipse-scout/releng": "^22.0.0"
  },
  "dependencies": {
    "@eclipse-scout/core": "{node-version}",
    "jquery": "3.6.0"
  }
}
----

The pre-built Scout JavaScript assets are also available using a CDN (e.g. to be directly included in a html document):
https://www.jsdelivr.com/package/npm/@eclipse-scout/core?path=dist

=== IDE Tooling (Scout SDK)

Scout officially supports https://www.jetbrains.com/idea/[IntelliJ IDEA] and {scout-sdk-download-link}.

==== IntelliJ IDEA

You can download the Scout plugin for IntelliJ IDEA from the https://plugins.jetbrains.com/plugin/13393-eclipse-scout/[JetBrains Plugin Repository] or you can use the plugins client built into IntelliJ IDEA.
Please refer to the https://www.jetbrains.com/help/idea/managing-plugins.html[IntelliJ Help] on how to install and manage plugins.

==== Eclipse

You can download the complete Eclipse IDE with Scout SDK included here: +
{scout-sdk-download-link}

To install the Scout SDK into your existing Eclipse IDE, use this P2 update site: +
{scout-sdk-update-site}

// ----------------------------------------------------------------------------

== Utilities

=== DateUtility: New Default Date Time Format

Since this version, the method `DateUtility#formatDateTime` returns the date formatted with the `DateFormat.DEFAULT` and no longer with the `DateFormat.SHORT`.
Now, both methods, `DateUtility#formatDate` and `DateUtility#formatDateTime`, are formatting the date identically.
To apply the old formatting, use `DateUtility#formatDateTimeShort`.

=== New ExceptionUtility

A set of utility methods dealing with `Exception` and `Throwable` were moved and added to the new `ExceptionUtility`.

Change invocations of `org.eclipse.scout.rt.platform.exception.ExceptionHandler.getRootCause()`
to the new utility method  `org.eclipse.scout.rt.platform.util.ExceptionUtility.getRootCause()`.

== Adapted REST ErrorDoRestClientExceptionTransformer

The transformation logic for exceptions which occur while invoking a REST client was slightly adapted.
For HTTP error codes 502 (bad gateway), 503 (service unavailable) and 504 (gateway timeout) the adapted `ErrorDoRestClientExceptionTransformer` returns a `org.eclipse.scout.rt.platform.exception.RemoteSystemUnavailableException` instead of the former generic `org.eclipse.scout.rt.platform.exception.ProcessingException`.

== Removed Deprecated Code

The following functions were deprecated in a previous release and are now removed completely.

* TabBox.ts: `selectTabById`, replaced by `setSelectedTab`
* JQueryMouseWheelEvent: instead of using `DOMMouseScroll mousewheel` events use `wheel` and JQueryWheelEvent type
* Menu.ts: `addChildActions`, replaced by `insertChildActions`
* Widget.ts: `_isRemovalPending`, replaced by `isRemovalPending`
* CompositeFieldUtility.java: `moveFieldTo`, third parameter removed
* AbstractExtensionChain.java: `callChain`, vararg removed
* AbstractDataModelOperatorField.java: setAttribute, second parameter is not optional anymore
* FocusManager.ts: `requestFocus` does not accept a boolean anymore as third parameter

== Removal of Public Holiday Calendar Support

A few classes used to read public holidays from an XML file and providing them to the calendar were removed without replacement:

** `org.eclipse.scout.rt.client.ui.basic.calendar.provider.AbstractHolidayItemProvider`
** `org.eclipse.scout.rt.shared.services.common.calendar.IHolidayCalendarService`
** `org.eclipse.scout.rt.server.services.common.calendar.HolidayCalendarService`
** `org.eclipse.scout.rt.shared.services.common.calendar.HolidayItem`
** `org.eclipse.scout.rt.shared.services.common.calendar.HolidayCalendarItemParser`

== Health Check Servlet

The logic of executing health checks was extracted from `org.eclipse.scout.rt.server.commons.healthcheck.AbstractHealthCheckServlet` and moved to an own `org.eclipse.scout.rt.server.commons.healthcheck.HealthCheckService`.

The `AbstractHealthCheckServlet` is no longer abstract, was renamed to `HealthCheckServlet` and may be used without further individualization.

To update to the new servlet, the following changes in your `web.xml` are necessary:

* UI Server: Replace `org.eclipse.scout.rt.ui.html.admin.healthcheck.UiHealthCheckServlet` with `org.eclipse.scout.rt.server.commons.healthcheck.HealthCheckServlet` in your `web.xml`
* Backend Server: Replace `org.eclipse.scout.rt.server.admin.healthcheck.ServerHealthCheckServlet` with `org.eclipse.scout.rt.server.commons.healthcheck.HealthCheckServlet` in your `web.xml`

== Removed unused NLS texts

The following NLS texts were unused within the Scout framework and removed:

* ButtonDeselectAll
* ButtonSelectAll
* ErrorTextLogin
* ErrorTextSecurity
* ErrorTitleLogin
* FileNotFoundMessage
* FormIncompleteIntro
* IOErrorInfo
* IOErrorText
* IOErrorTitle
* LogicTimeIsInGEHours
* LogicTimeIsInGEMinutes
* LogicTimeIsInHours
* LogicTimeIsInLEHours
* LogicTimeIsInLEMinutes
* LogicTimeIsInMinutes
* LogicTimeIsNotNow
* LogicTimeIsNow
* NetErrorInfo
* NetErrorText
* NoSorting
* OriginalErrorMessageIs
* VetoErrorText
* WeekShort
* Without
* searchingProposals

== Scout JS

=== Tree: Insert Order Changed

`Tree.insertNodes` now adds new nodes (without an explicit childNodeIndex) at the bottom of the existing nodes instead of the top.
This is already the case for the Scout Classic tree, and also for other widgets like table and tile grid.

To insert the nodes at the beginning or any other position, you can use the new parameter `index`.

=== Form

==== Modal Optional for Views

The default value for the `modal` property has been changed for forms with `displayStyle` = `Form.DisplaStyle.VIEW`, see xref:releasenotes:release-notes.adoc#modal-optional-for-views[Release Notes].

==== Form Validation

The text to display when the Form validation failed has been moved from Lifecycle to Form:

* `Lifecycle.validationFailedTextKey` to `Form.validationFailedText` and use the `${textKey:TextKey}` notation to specify a text key
* `Lifecycle.validationFailedText` to `Form.validationFailedText`

The code to display a message box when the Form validation failed has been moved from Lifecycle to Form:

* `Lifecycle._showStatusMessageBox` to `Form._showFormInvalidMessageBox`
* `Lifecycle._createStatusMessageBox` to `Form._createStatusMessageBox`

==== Form Error Handling

The load, postLoad and save operations of a Scout JS Form include automatic error handling now.
Custom logic to handle errors (e.g. from REST calls) are in most cases no longer necessary and can therefore be removed.

If the default error handling does not suit your needs override one of the following methods:

* `_handleError`: to handle all phases (load, postLost, save)
* `_handleLoadError`: load errors only
* `_handlePostLoadError`: postLoad errors only
* `_handleSaveError`: save errors only

To customize the error handling from outside the form suppress the default handling using an event listener and apply your own logic in the catch:

[source,javascript]
[subs="verbatim,attributes"]
----
form.on('error', event => {
    if (event.phase === 'load') {
      event.preventDefault(); // disable default error handling for 'load' only
    }
});
form.open().catch(error => {
  // add your custom error handling logic here
});
----

As part of the new error handling the following methods changed its signature:

* `Form.validate` and `Lifecycle.validate`: Now return Promise<Status> instead of Promise<boolean>. The former boolean value can be obtained by calling isValid() on the new Status object.
* `Lifecycle.handle` now only takes a function returning Promise<void>. There is no need to return a Status anymore.
* `Form._onLifecycleLoad`, `Form._onLifecycleSave`, `Form._save`, `Form.save` and `Lifecycle._save`: now return Promise<void>. There is no need to return a Status anymore. A load/save failure should return a rejected Promise and a successful load/save should return a resolved promise. In case of an error the Promise might be rejected with any error or a Status describing the error.
* `Form._handleLoadError`: Returns Promise<void> which indicates that the error was handled. A rejected promise means the error could not be handled. In such a case no fallback is applied! It is therefore the developers responsibility to ensure the error was handled as desired.

==== FormField

[#rename-requiressave-to-saveneeded]
===== Rename requiresSave to saveNeeded

The property `requiresSave` and the function `updateRequiresSave` on the `FormField` have been renamed to `saveNeeded` resp. `updateSaveNeeded`.
This makes it consistent with the property `saveNeededVisible` on the Form and also with Scout Classic.

To migrate it is best to search for `requiresSave` resp. `RequiresSave` in your JS/TS code base and replace the occurrences accordingly.

[#formfield-visitfields-now-visits-deeper]
===== VisitFields Now Visits Deeper

The visiting is not limited to composite fields anymore which means more fields may be visited, see xref:releasenotes:release-notes.adoc#visitfields-across-field-trees[Release Notes]. If you need the old behavior, you can use the option `limitToSameFieldTree` in the options parameter of the `visitFields` method.

===== Touched not Affected by Value Change Anymore

A form field has a property `touched` which can be set by using `touch()`. A touched form field needs to be saved.
Until now, a value change (by the user or by using `setValue`) set this property to true.
This has been changed so that a value change does not change the property anymore, it can only be modified using `touch()` resp. `markAsSaved()`. This has the benefit that `touched` can be completely controlled by the developer.

In order to check if a value has been changed or a field touched you can use the property `saveNeeded`.
