////
Howto:
- Write this document such that it helps people to migrate. Describe what they should do.
- Chronological order is not necessary.
- Choose the right top level chapter (java, js, other)
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////

== About This Document

This document describes all relevant changes *from Eclipse Scout {scout-previous-version} to Eclipse Scout {scout-version}*. If existing code has to be migrated, instructions are provided here.

WARNING: {NotReleasedWarning}

== Obtaining the Latest Version

=== Scout Runtime for Java

Scout Runtime artifacts for Java are distributed using Maven Central:

* {maven-central-link} on _Maven Central_
* {mvnrepository-link} on _mvnrepository.com_

Usage example in the parent POM of your Scout application:

[source,xml]
[subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.eclipse.scout.rt</groupId>
    <artifactId>org.eclipse.scout.rt</artifactId>
    <version>{maven-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

=== Scout Runtime for JavaScript

Scout Runtime artifacts for JavaScript are distributed using npm:

* https://www.npmjs.com/package/@eclipse-scout/core[Scout Core Runtime]
* https://www.npmjs.com/search?q=%40eclipse-scout[All official Scout JavaScript packages]

Usage example in your package.json:

[source,json]
[subs="verbatim,attributes"]
----
{
  "name": "my-module",
  "version": "1.0.0",
  "devDependencies": {
    "@eclipse-scout/cli": "{node-version}",
    "@eclipse-scout/releng": "^24.1.0"
  },
  "dependencies": {
    "@eclipse-scout/core": "{node-version}",
    "jquery": "3.7.1"
  }
}
----

The pre-built Scout JavaScript assets are also available using a CDN (e.g. to be directly included in a html document):
https://www.jsdelivr.com/package/npm/@eclipse-scout/core?path=dist

=== IDE Tooling (Scout SDK)

Scout officially supports https://www.jetbrains.com/idea/[IntelliJ IDEA] and {scout-sdk-download-link}.

==== IntelliJ IDEA

You can download the Scout plugin for IntelliJ IDEA from the https://plugins.jetbrains.com/plugin/13393-eclipse-scout/[JetBrains Plugin Repository] or you can use the plugins client built into IntelliJ IDEA.
Please refer to the https://www.jetbrains.com/help/idea/managing-plugins.html[IntelliJ Help] on how to install and manage plugins.

==== Eclipse

You can download the complete Eclipse IDE with Scout SDK included here: +
{scout-sdk-download-link}

To install the Scout SDK into your existing Eclipse IDE, use this P2 update site: +
{scout-sdk-update-site}

// ----------------------------------------------------------------------------

== New Build & Runtime Requirements

Scout 24.1 requires at least the following:

* The Java 11 support has been dropped. Build and runtime therefore require Java 17 now. Java 21 Support is planned for a future release.
* Furthermore, the build requires
** Maven >= 3.9.2
** Node.js >= 20.10.0
** pnpm >= 8.11.0

== HTTP/2 Support

For Scout 24 and newer enabling `HTTP/2` for your application is recommended. Please refer to the xref:technical-guide:user-interface/browser-support.adoc[documentation] on how to enable `HTTP/2`.

== Build changes

* The Maven build has the enforcer rule https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html[dependencyConvergence] enabled by default.
Therefore, builds will fail if different versions for the same dependency are used.
To fix this, ensure your dependencies converge and use the https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html[dependencyManagement] where necessary to specify which version to use.
* The property `master_dependency_tycho-compiler_version` has been deleted as the Tycho compiler is no longer used.
Instead, the property `master_dependency_ecj_version` may be used to specify the https://search.maven.org/artifact/org.eclipse.jdt/ecj[Eclipse compiler (ECJ)] version. By default version 3.31.0 is used which is part of Eclipse 4.27 (2023-03), IntelliJ 2023.2 and IntelliJ 2023.3.
* Typescript has been updated from 4.9.5 to 5.3.2. See https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#breaking-changes-and-deprecations[here] for a list of breaking changes and update your code accordingly.
* Update the version of the `maven_rt_plugin_config-master` in your `pom.xml` files to the newest `24.1.x` release.
See https://search.maven.org/artifact/org.eclipse.scout/maven_rt_plugin_config-master[Maven central] for a list of versions available.
* Update the Scout versions (`package.json` and `pom.xml`) as shown in <<Obtaining the Latest Version>>.
* If you are using Eclipse and web-service providers, update the `.factorypath` files as shown in xref:technical-guide:working-with-data/jax-ws.adoc#jax-ws-appendix[JAX-WS Appendix].

== 3rd Party Libraries Update

=== Update to Jakarta EE

Until now, Scout was based on the Java EE Servlet Specification 4.0, many of our third-party libraries also depends on this specification
(e.g. Jetty, HttpServlet API, JMS, JAX-WS, JAX-RS etc).
With release 24/1 the Scout framework is moving towards Jakarta EE and is now based on the 5.0 specification.
As part of this Jakarta EE version update all module names and packages have been renamed from javax to jakarta
(due to legal requirements by Oracle as part of the open source donation of Java EE to the Eclipse Foundation).

Together with the Jakarta EE update many third-party libraries have received a new version defined in Scout parent POM.
Additionally, all Java EE imports have been migrated from `javax` to `jakarta`.

==== Migration guide

* Update Scout dependency to release 24.1
* Check third party library dependencies in your project, upgrade to Jakarta version if necessary
* Reload all maven projects in IntelliJ or Eclipse IDE
* Migrate your own code to Jakarta (e.g. using IntelliJ Migrator or similar Eclipse tooling)
** IntelliJ Menu: Refactor -> Migrate Packages and Classes -> Java EE to Jakarta EE
** Eclipse see _Eclipse Transformer_ tool
** All packages and classes are updated automatically

===== JAX-WS services

After the upgrade to 24.1, projects that use JAX-WS (Soap) as a provider should check the connection both on DEV and on the deployed system
to ensure that everything is working as desired.
This applies above all to cases when own libraries in /WEB-INF/lib are used or the corresponding resources in /META-INF/resources.

If your JAX-WS service uses global bindings, the _global-bindings.xml_ file must be updated according to the following example:

.Example global-bindings.xml
[source=xml]
----
<jaxb:bindings version="3.0"    <1>
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc"
xmlns:jaxb="https://jakarta.ee/xml/ns/jaxb">  <2>
<jaxb:globalBindings>
  <!-- your global mappings here -->
</jaxb:globalBindings>
</jaxb:bindings>
----

<1> Update to version 3.0
<2> Update to namespace _https://jakarta.ee/xml/ns/jaxb_

===== UI Server web.xml

As part of the switch to Jakarta EE the third party library dependency to Apache File Upload was eliminated.
Scout now relies on plain Jakarta EE API to process HTTP multipart requests.
Servlets processing multipart requests using Jakarta EE API requires a multipart-config in their servlet registration.
Make sure to add a _<multipart-config>_ section to your `web.xml` where the `UiServlet` is registered:

.Example multipart-config in _web.xml_ of Scout UI server
[source=xml]
----
<servlet>
<servlet-name>UiServlet</servlet-name>
<servlet-class>org.eclipse.scout.rt.ui.html.UiServlet</servlet-class>
<multipart-config>
  <location>/tmp</location>
  <max-file-size>104857600</max-file-size> <1>
  <max-request-size>104857600</max-request-size>   <2>
  <file-size-threshold>20971520</file-size-threshold>   <3>
</multipart-config>
</servlet>
----

<1> Maximum size of single file, e.g. 100mb
<2> Maximum size of multi-part request, e.g. 100mb
<3> Threshold for file chunking, e.g. 20mb

=== Other libraries

* Mockito 5: Uses the inline mock maker as new default and change the behavior of `any()`, which does not match varargs anymore (use `any(Class)` instead).

== Removed Deprecated Methods in ICacheBuilder and IFormHandler

The deprecated method `ICacheBuilder#withAtomicInsertion` was removed.
No migration is required, as this method did not change behavior in any way.

The method `IFormHandler#getHandlerId` was removed without a replacement as there is no use for it.

== Former JettyServer for development can be used in a productive environment

`org.eclipse.scout.dev.jetty.JettyServer` was so far only used for development environments.
With this release it was improved so that it can be used in a productive environment too (instead of building a .war file to be used in an application server).
The Scout Application class contains a main-method which may be started directly and itself starts an embedded Jetty server.

The following renaming is applied.

=== Modules

* `org.eclipse.scout.dev.jetty` -> `org.eclipse.scout.rt.app`
** Check dependencies within `pom.xml`

* `org.eclipse.scout.dev.jetty.test` -> `org.eclipse.scout.rt.app.test`
* `org.eclipse.scout.dev.jetty.test.affix` -> `org.eclipse.scout.rt.app.test.affix`

=== Java classes

* `org.eclipse.scout.dev.jetty.JettyServer` -> `org.eclipse.scout.rt.app.Application`
** Check run configurations etc.

=== Properties

* `scout.jetty.port` -> `scout.app.port`
* `scout.jetty.consoleInputHandler` -> `scout.app.consoleInputHandlerEnabled`

* `scout.jetty.webapp.contextpath` -> `scout.app.contextPath`
* `scout.jetty.webapp.folder` -> `scout.app.webappDirectory`

* `scout.jetty.keyStorePath` -> `scout.app.keyStorePath`
* `scout.jetty.autoCreateSelfSignedCertificate` -> `scout.app.autoCreateSelfSignedCertificate`
* `scout.jetty.keyStorePassword` -> `scout.app.keyStorePassword`
* `scout.jetty.privateKeyPassword` -> `scout.app.privateKeyPassword`
* `scout.jetty.certificateAlias` -> `scout.app.certificateAlias`

