////
Howto:
- Write this document such that it helps people to migrate. Describe what they should do.
- Chronological order is not necessary.
- Choose the right top level chapter (java, js, other)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////

== About This Document

This document describes all relevant changes *from Eclipse Scout {scout-previous-version} to Eclipse Scout {scout-version}*. If existing code has to be migrated, instructions are provided here.

== Obtaining the Latest Version

=== Scout Runtime for Java

Scout Runtime artifacts for Java are distributed using Maven Central:

* {maven-central-link} on _Maven Central_
* {mvnrepository-link} on _mvnrepository.com_

Usage example in the parent POM of your Scout application:

[source,xml]
[subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.eclipse.scout.rt</groupId>
    <artifactId>org.eclipse.scout.rt</artifactId>
    <version>{maven-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

=== Scout Runtime for JavaScript

Scout Runtime artifacts for JavaScript are distributed using npm:

* https://www.npmjs.com/package/@eclipse-scout/core[Scout Core Runtime]
* https://www.npmjs.com/search?q=%40eclipse-scout[All official Scout JavaScript packages]

Usage example in your package.json:

[source,json]
[subs="verbatim,attributes"]
----
{
  "name": "my-module",
  "version": "1.0.0",
  "devDependencies": {
    "@eclipse-scout/cli": "{node-version}",
    "@eclipse-scout/releng": "^25.1.0"
  },
  "dependencies": {
    "@eclipse-scout/core": "{node-version}",
    "jquery": "3.7.1"
  }
}
----

The pre-built Scout JavaScript assets are also available using a CDN (e.g. to be directly included in a html document):
https://www.jsdelivr.com/package/npm/@eclipse-scout/core?path=dist

=== IDE Tooling (Scout SDK)

Scout officially supports https://www.jetbrains.com/idea/[IntelliJ IDEA] and {scout-sdk-download-link}.

==== IntelliJ IDEA

You can download the Scout plugin for IntelliJ IDEA from the https://plugins.jetbrains.com/plugin/13393-eclipse-scout/[JetBrains Plugin Repository] or you can use the plugins client built into IntelliJ IDEA.
Please refer to the https://www.jetbrains.com/help/idea/managing-plugins.html[IntelliJ Help] on how to install and manage plugins.

==== Eclipse

You can download the complete Eclipse IDE with Scout SDK included here: +
{scout-sdk-download-link}

To install the Scout SDK into your existing Eclipse IDE, use this P2 update site: +
{scout-sdk-update-site}

// ----------------------------------------------------------------------------

== New Build & Runtime Requirements

Scout 26.1 requires at least the following:

* Build and runtime of Scout 26.1 require Java 25. The compiler target level is set to Java 21.

== Action / Menu: Tabbable Default Changed (Scout JS)
An `Action` and a `Menu` is now tabbable and has a keystroke to execute it by default.
This means if you used an action or a menu _outside_ a menu bar, it can now get the focus using the keyboard.
This is important to improve the accessibility of your application.

However, there may be some actions or menus that should not be tabbable.
In that case just set `tabbable` to false.

== WidgetField: Scrollable Default Changed (Scout JS)
A `WidgetField` has a property `scrollable` whose default value is `true`.
This is often not desired as a `WidgetField` is supposed to be a wrapper for a widget without changing its behavior.
This is why the default value has been changed to `false`.

So you need to check your widget fields if they really need to be scrollable and if yes set `scrollable` to true.
Normally, this should not be the case as a surrounding container like the main box is already scrollable.

== Switch: Tabbable Default Changed (Scout JS)
A `Switch` is now tabbable by default.
This is important to improve the accessibility of your application.

However, there may be some switches that should not be tabbable.
In that case just set `tabbable` to false.

== Code Cleanup

=== JQuery-Scout (Scout JS)
The following functions have been renamed:

- select(boolean) -> setSelected(boolean) +
  If you followed the naming convention, you can use the following regex to find the occurrences:
  `\$\w+\.select\(` +
  Note: `select()` also exists on an `HTMLInputElement`, so make sure you don't accidentally rename the wrong method (if you use TypeScript the compiler will help you).

The following functions have been removed:

- selectOne() +
  Replace with `setSelected(true)` and `setSelected(false)` on the siblings.

== Widget.cssClass: API Changes (Scout JS)

The methods to modify the `cssClass` property of the `Widget` were moved to the `styles` utility (see xref:releasenotes:release-notes.adoc#styles-css-class[Release Notes]).
The API of `setCssClass`, `addCssClass`, `removeCssClass`, `toggleCssClass` and `hasCssClass` remains the same but the method `cssClassAsArray` and the static method `cssClassAsArray` were removed.
Code using these methods must be migrated as follows:

.old: using the `cssClassAsArray` methods of the `Widget`.
[source,typescript,opts=novalidate]
----
const widget = scout.create(Widget, {
  // ...
  cssClass: 'foo bar'
});
const widgetCssClassAsArray = widget.cssClassAsArray();

const cssClass = 'foo bar';
const cssClassAsArray = Widget.cssClassAsArray(cssClass);
----

.new: using the `cssClassAsArray` methods of the `styles` utility.
[source,typescript,opts=novalidate]
----
const widget = scout.create(Widget, {
  // ...
  cssClass: 'foo bar'
});
const widgetCssClassAsArray = styles.cssClassAsArray(widget.cssClass);

const cssClass = 'foo bar';
const cssClassAsArray = styles.cssClassAsArray(cssClass);
----

== widgets Util: Behavior Change of preserveAndSetProperty (Scout JS)

If you use the function `widgets.preserveAndSetProperty` in your JavaScript code, please make sure that the variable that stores the preserved value is not initialized or initialized to `undefined`.
If it is initialized to `null`, remove the initialization.

== Service tunnel: Servlet removed, REST resource added

In the past the service tunnel used its own servlet/communication implementation to transfer data between client and server module.
The own (proprietary) logic was removed and standard REST communication will be used for data transfer now.

Most applications should not be affected by these changes as for the outside the service tunnel should still function the same way it did previously (most changes are under the hood).

However for further understanding a few changes included in this change are described here:

The service tunnel client (e.g. `HttpServiceTunnel`) has been moved from `org.eclipse.scout.rt.shared` to `org.eclipse scout.rt.client`; in the past it would have been possible to use the service tunnel for communication between backend servers, this is not possible anymore.
As the class now resides in the client the `ClientHttpServiceTunnel` has been integrated into the `HttpServiceTunnel`.

The `HttpServiceTunnel` does not send the outgoing HTTP request itself anymore, instead a newly created `ProcessResourceClient` (REST resource client) is used.
This resource client uses the newly added `ScoutBackendRestClientHelper` for configuration.
The `HttpServiceTunnelTransportManager` and its configuration properties `scout.servicetunnel.maxConnectionsPerRoute` and `scout.servicetunnel.maxConnectionsTotal` have been removed.

On the server-side there is no `ServiceTunnelServlet` anymore to answer incoming HTTP requests, instead a `ProcessResource` (REST resource) has been created which delegates the request to the `ServiceTunnelService`.

Arbitrary `IServiceTunnelContentHandler` support was removed (and also the `SoapServiceTunnelContentHandler` implementation), the service tunnel now always uses the `BinaryServiceTunnelContentHandler` bean (which may still be extended).

The duplicate request detection `SequenceNumberDuplicateDetector` has been removed.

By default, the service tunnel uses gzip compression for outgoing and incoming requests, this may be configured using the following configuration properties:

* `scout.servicetunnel.compress`: Specifies if the service tunnel should use gzip compression for outgoing requests (default: true)
* `scout.app.gzip.inflateBufferSize`: Set a positive number to enable incoming compressed requests (default: 2048), positive number must be set if previous property is set to `true`

For outgoing request compression the `org.glassfish.jersey.message.GZipEncoder` is installed (by the `GzipEncoderContributor`, it handles content-encoding possibly set by `ProcessResourceClient`).
Incoming request decompression is handled by the `org.eclipse.jetty.server.handler.gzip.GzipHandler`.
Outgoing response compression is handled (and decided) by the `org.eclipse.jetty.server.handler.gzip.GzipHandler`.
The response decompression (if applicable) is handled by the HTTP client `org.apache.hc.client5.http.entity.DecompressingEntity`.

Applications which are deployed using a `web.xml` to a Jetty (legacy) may need to add the `gzip` module and set the `-Djetty.gzip.inflateBufferSize=2048` command line property (as the configuration property `scout.app.gzip.inflateBufferSize`) is not respected.
Also the process servlet and its mapping must be removed from the `web.xml`.

The following configuration properties have been changed:

* `server.url` (legacy): Removed, use `scout.backendUrl` instead.
* `scout.servicetunnel.targetUrl`: Removed, use `scout.backendUrl` instead.
* `scout.backendUrl`: Moved from shared to client code (not applicable for server backend application anymore)
* `scout.createTunnelToServerBeans`: Moved from shared to client code (not applicable for server backend application anymore)

For all REST requests the cancellation behavior has been changed, previously a cancel request was sent and the client did wait (blocking) for the backend request to be cancelled.
Now the same cancel request is sent to the backend which tries to cancel the possibly running request, but the client-side also aborts the running request itself without waiting for any cancellation response allowing the user to interact quicker with the application again (same behavior as previously in service tunnel).

== DefaultAuthToken: Package changed, constant moved

As the `DefaultAuthToken` was not used exclusively for the service-tunnel the following types and constants have been moved:

[cols="1,1"]
|===
|Type/Constant|Target

|`org.eclipse.scout.rt.shared.servicetunnel.http.DefaultAuthToken`
|`org.eclipse.scout.rt.shared.authentication.DefaultAuthToken`

|`org.eclipse.scout.rt.shared.servicetunnel.http.DefaultAuthTokenPrincipalProducer`
|`org.eclipse.scout.rt.shared.authentication.DefaultAuthTokenPrincipalProducer`

|`org.eclipse.scout.rt.shared.servicetunnel.http.DefaultAuthTokenSigner`
|`org.eclipse.scout.rt.shared.authentication.DefaultAuthTokenSigner`

|`org.eclipse.scout.rt.shared.servicetunnel.http.DefaultAuthTokenVerifier`
|`org.eclipse.scout.rt.shared.authentication.DefaultAuthTokenVerifier`

|`org.eclipse.scout.rt.shared.servicetunnel.http.HttpServiceTunnel#TOKEN_AUTH_HTTP_HEADER`
|`org.eclipse.scout.rt.shared.authentication.DefaultAuthToken#HTTP_HEADER_NAME`
|===

== Session API changes

As part of the move toward a stateless backend server, the API of the session has been changed.

`ISession`:

* `getSharedVariableMap` moved to the `IClientSession`.

`IClientSession`:

* `replaceSharedVariableMapInternal` removed. To update variables on the client session use `setSharedVariables` or send a `SharedContextChangedNotification` from the backend.

`AbstractServerSession`:

* `m_sharedVariableMap` removed. No more data should be stored on the server session. The data should be stored in user-based caches or loaded from the database instead. To add additional variables during client session initialization, implement an `IInitialSharedVariableContributor`.

`AbstractClientSession`:

* `initializeSharedVariables` renamed to the `loadInitialSharedVariables`.

== Data Object Serializer Provider Implementations Supplemented with Order Annotation

The Scout implementation `ScoutDataObjectSerializerProvider` of serializer/deserializer provider interface `IDataObjectSerializerProvider` was supplemented with an `@Order` annotation using value 4500
to achieve a fixed order when looking up all instances by `BEANS.all(IDataObjectSerializerProvider.class)`.

ACTION: Check custom implementations of `IDataObjectSerializerProvider` interface.
Default order for bean implementations without `@Order` annotation is 5000, which means your `IDataObjectSerializerProvider` is invoked as last instance.
Usually this is appropriate if your implementation just adds serializer or deserializers for additional classes.

If you want to override any Scout serializer/deserializer use an order lower than 4500 for your implementation and become the first provider which is invoked.

== Simple tab box (Scout JS)

The `SimpleTabBox` has been improved and can now display the tabs on any side of the box.
As part of these adjustments, the associated `SimpleTabAreaLayout` has been modified and attributes have been renamed.

- `tabWidth` was renamed to `tabSize`
- `tabMinWidth` was renamed to `tabMinSize`
- `overflowTabItemWidth` was renamed to `overflowTabItemSize`
