////
Howto:
- Write this document such that it helps people to migrate. Describe what they should do.
- Chronological order is not necessary.
- Choose the right top level chapter (java, js, other)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////

== About This Document

This document describes all relevant changes *from Eclipse Scout {scout-previous-version} to Eclipse Scout {scout-version}*. If existing code has to be migrated, instructions are provided here.

== Obtaining the Latest Version

=== Scout Runtime for Java

Scout Runtime artifacts for Java are distributed using Maven Central:

* {maven-central-link} on _Maven Central_
* {mvnrepository-link} on _mvnrepository.com_

Usage example in the parent POM of your Scout application:

[source,xml]
[subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.eclipse.scout.rt</groupId>
    <artifactId>org.eclipse.scout.rt</artifactId>
    <version>{maven-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

=== Scout Runtime for JavaScript

Scout Runtime artifacts for JavaScript are distributed using npm:

* https://www.npmjs.com/package/@eclipse-scout/core[Scout Core Runtime]
* https://www.npmjs.com/search?q=%40eclipse-scout[All official Scout JavaScript packages]

Usage example in your package.json:

[source,json]
[subs="verbatim,attributes"]
----
{
  "name": "my-module",
  "version": "1.0.0",
  "devDependencies": {
    "@eclipse-scout/cli": "{node-version}",
    "@eclipse-scout/releng": "^26.2.0"
  },
  "dependencies": {
    "@eclipse-scout/core": "{node-version}",
    "jquery": "3.7.1"
  }
}
----

The pre-built Scout JavaScript assets are also available using a CDN (e.g. to be directly included in a html document):
https://www.jsdelivr.com/package/npm/@eclipse-scout/core?path=dist

=== IDE Tooling (Scout SDK)

Scout officially supports https://www.jetbrains.com/idea/[IntelliJ IDEA] and {scout-sdk-download-link}.

==== IntelliJ IDEA

You can download the Scout plugin for IntelliJ IDEA from the https://plugins.jetbrains.com/plugin/13393-eclipse-scout/[JetBrains Plugin Repository] or you can use the plugins client built into IntelliJ IDEA.
Please refer to the https://www.jetbrains.com/help/idea/managing-plugins.html[IntelliJ Help] on how to install and manage plugins.

==== Eclipse

You can download the complete Eclipse IDE with Scout SDK included here: +
{scout-sdk-download-link}

To install the Scout SDK into your existing Eclipse IDE, use this P2 update site: +
{scout-sdk-update-site}

// ----------------------------------------------------------------------------

== REST operations: Add Consumes annotation

It is recommended that all REST operations which consume a request entity body message have a `Consumes` annotation set to restrict invalid input.
Therefore, a test has been added which fails if there are such operations which do not have a `Consumes` annotation.
The `AbstractRestResourceAnnotationTest` has to be extended in your modules to run this test.

== REST resources: Explicit `@Path` annotation required

It is recommended that all REST resource classes explicitly declare a `@Path` annotation.

According to the Jakarta RESTful Web Services specification, JAX-RS annotations — including `@Path` — are not inherited from superclasses or interfaces.
While Jersey, the implementation we use, does attempt to locate a `@Path` annotation on parent classes, this behavior is not defined by the specification and should not be relied upon.

To ensure compliance, a test has been introduced that fails if any REST resource is missing a `@Path` annotation.
To activate this validation for your module, extend the `AbstractRestResourceAnnotationTest` class accordingly.

== Removal of autoPrefixWildcardForTextSearch on Desktop

The methods `isAutoPrefixWildcardForTextSearch` and `setAutoPrefixWildcardForTextSearch` on `IDesktop` have been removed.
They have not been used since years and were never supported in Scout JS.

If you need a prefix wildcard, add it to your search texts manually where required.

== Removal of old Maven-Master properties

The Maven Build no longer uses npm to run scripts. Npm is now only used to install pnpm and @eclipse-scout/releng. Then, pnpm is used to run build and test scripts.
Accordingly, the following Maven-Master properties have been removed and can be deleted without replacement:

* `master_npm_version`
* `master_webpack_options`

== Removal of Deprecated Code

The following Java code was deprecated since at least one release and has been removed:

* `ITileGrid.PROP_ASYNC_LOAD_JOBNAME_PREFIX`: Use `ITileGrid.ASYNC_LOAD_JOBNAME_PREFIX` instead.
* `ITileGrid.PROP_ASYNC_LOAD_IDENTIFIER_PREFIX`: Use `ITileGrid.ASYNC_LOAD_IDENTIFIER_PREFIX` instead.
* `ITileGrid.PROP_WINDOW_IDENTIFIER_PREFIX`: Use `ITileGrid.WINDOW_IDENTIFIER_PREFIX` instead.
* `BasicCache`: The constructors without `labelSupplier` have been removed. Use the ones including `labelSupplier`. A label supplier can be retrieved using `CacheBuilder.getLabelSupplier()`.
* `EncryptionKey`: The constructor without `compatibilityHeader` has been removed.
* `FileUtility.extractArchive` has been removed. It used a dangerous special handling for zip directories with the same name as the target directory. Use `FileUtility.extractZip` instead. If top-level directories exist, they should be removed manually as required.
* Config property `scout.rest.api.exposed.enforce` has been removed without replacement. If the feature is not required, remove the `ApiExposedFilter` from your filter chain.
* `TrivialAccessController.TrivialAuthConfig.getPathInfoFilter` has been removed. Use `TrivialAccessController.TrivialAuthConfig.getExclusionFilter` instead.
* The package `org.eclipse.scout.rt.server.commons.servlet.filter.gzip` and all containing classes have been removed. The HTTP request compression is now automatically handled by Jetty instead of this custom implementation.
* Accordingly, the compression flags on `UrlHints` and `UrlHintsHelper` have been removed. So compression can no longer be enabled or disabled on the fly. Old cookie values are still valid but the compression flag (`Z`) will be ignored now.

The following TypeScript code was deprecated since at least one release and has been removed:

* `CodeType.codes(rootOnly?: boolean)` was deleted. Use the more flexible `CodeType.codes(options?: CodeTypeCodesOptions)`. It provides an option `rootOnly` amongst others.
* `Page.getOutline()` function was replaced with `Page.outline` property.
* `Page._pageParam()` function was removed as it was never used.
* `PageWithTable.createChildPage()` function was replaced with `PageWithTable._createChildPage()`.
* `Form._withBusyHandling()` was renamed to `Form.withBusyHandling()`.
* `Column.isVisible()` function was replaced with `Column.visible` property.
* `Table.removeAllRows()` was deleted. Use `Table._removeAllRows()` to only remove DOM elements, otherwise use `Table.deleteAllRows()` (recommended).
* `Table.groupColumn()` was deleted. Use `Table.group()` instead.
* `Table.removeColumnGrouping()` was deleted. Use `Table.removeGroupColumn()` instead.
* `Table.removeAllColumnGroupings()` was deleted. Use `Table.removeGroupColumn()` instead.
* `Table.isHierarchical()` was deleted. Use `Table.hierarchical` property instead.
* `Table.getVisibleRows()` was deleted. Use `Table.visibleRows` property instead.
* `TableRow.getTable()` was deleted. Use `TableRow.table` property instead.
* `TileGrid.tilesWithoutPlaceholders()` has been deleted. Use `TileGrid.tiles` instead.
* `TreerNode.getTree()` has been deleted. Use `TreeNode.tree` property instead.
* `objects.isPlainObject()` has been deleted. Use `objects.isObject()` or `objects.isPojo()` instead.
* `Widget.isVisible()` has been deleted. Use `Widget.visible` property instead.
* `Widget.getFocusableElement()` has been deleted. Use `Widget.get$Focusable()` instead.
* `widgets.createUniqueId()` has been deleted. Use `ObjectIdProvider.get().createUiSeqId()` instead.
* `ObjectFactory.createUniqueId` has been removed. Use `ObjectIdProvider.get().createUiSeqId()` decorator instead.
* `ObjectFactoryOptions.ensureUniqueId` has been removed. Use `@objectFactoryHints({ensureId: true})` decorator on the affected class instead.

NOTE: In case you still use JavaScript code (instead of TypeScript), these API changes will not be verified using the TypeScript compiler!
Then you have to go through your JavaScript code manually to find all usages.

The following Less mixins have been removed as they are no longer necessary:

* `#scout.animation`: Use `animation` property directly. So instead of e.g. `#scout.animation(show-axis-select 0.5s ease-in-out 1);` use `animation: show-axis-select 0.5s ease-in-out 1;`.
* `#scout.animation-duration`: Use `animation-duration` property directly. So instead of e.g. `#scout.animation-duration(0.5s);` use `animation-duration: 0.5s;`.
* `#scout.animation-name`: Use `animation-name` property directly. So instead of e.g. `#scout.animation-name(slideout-right);` use `animation-name: slideout-right;`.
* `#scout.animation-delay`: Use `animation-delay` property directly. So instead of e.g. `#scout.animation-delay(400ms);` use `animation-delay: 400ms;`.
* `#scout.animation-fill-mode`: Use `animation-fill-mode` property directly. So instead of e.g. `#scout.animation-fill-mode(forwards);` use `animation-fill-mode: forwards;`.
* `#scout.animation-timing-function`: Use `animation-timing-function` property directly. So instead of e.g. `#scout.animation-timing-function(linear);` use `animation-timing-function: linear;`.
* `#scout.animation-iteration-count`: Use `animation-iteration-count` property directly. So instead of e.g. `#scout.animation-iteration-count(1);` use `animation-iteration-count: 1;`.
* `#scout.transform`: Use `transform` property directly. So instead of e.g. `#scout.transform(rotatex(180deg));` use `transform: rotatex(180deg);`.
* `#scout.transform-origin`: Use `transform-origin` property directly. So instead of e.g. `#scout.transform-origin(top);` use `transform-origin: top;`.
* `#scout.cursor-grab`: Use `cursor` property directly. So instead of e.g. `#scout.cursor-grab();` use `cursor: grab;`.
* `#scout.cursor-grabbing`: Use `cursor` property directly. So instead of e.g. `#scout.cursor-grabbing();` use `cursor: grabbing;`.
* KeyFrames for the following animations have been deleted as they were no longer used. If the KeyFrames are still necessary, copy them to your own code from a previous release:
** `fadeout-grow`
** `fadein-grow-blur`
** `rotation-reverse`
** `pulse-opacity`
** `rotate-x`

== AbstractRestLookupCall moved to shared module

`AbstractRestLookupCall` was moved from the client to the shared module:
`org.eclipse.scout.rt.client.services.lookup.AbstractRestLookupCall` -> `org.eclipse.scout.rt.shared.services.lookup.AbstractRestLookupCall`.

== SmtpConnectionPool: Connection error/idle handling

For the `org.eclipse.scout.rt.mail.smtp.SmtpConnectionPool` in the past idle timeouts could be defined in seconds.
However, connections were only checked once per minute, hence idle timeouts less than one minute were not respected.
This check interval has been decreased from one minute to 20 seconds (default value), it is now configurable by config property `scout.smtp.pool.closeIdleConnectionsJobSchedule`.
Also the default idle timeout has been decreased from one minute to 20 seconds (existing config property `scout.smtp.pool.maxIdleTime`).

Also the connection error handling has been changed, connection error codes 421 and 451 are now also treated as failed connection (according to RFC 5312 3.8 connection failures and at least error codes 451 should be treated the same way).

[#tree-scout-js-api-of-visitnodes-changed]
== Tree (Scout JS): API of VisitNodes Changed

Returning `true` in a visitor used for `Tree.visitNodes` now stops visiting completely instead of just skipping the subtree, see also xref:release-notes.adoc#tree-scout-js-findnode-added-and-visitnodes-improved[Release Notes].

Please check your JavaScript / TypeScript code for occurrences of `visitNodes` and if the visitor explicitly returns `true`, replace it with `TreeVisitResult.SKIP_SUBTREE`.

[source,typescript,opts=novalidate]
.Old
----
tree.visitNodes(node => {
  return true;
});
----

[source,typescript,opts=novalidate]
.New
----
tree.visitNodes(node => {
  return TreeVisitResult.SKIP_SUBTREE;
});
----

== Trust manager and remote files

`org.eclipse.scout.rt.server.commons.GlobalTrustManager.getTrustedCertificatesInRemoteFiles()` has been removed. As a result, all trusted certificates now have to be provided locally.

The following service operations have also been removed:

* `org.eclipse.scout.rt.client.services.common.file.IFileService.syncRemoteFiles(String, FilenameFilter)`
* `org.eclipse.scout.rt.client.services.common.file.IFileService.syncRemoteFilesToPath(String, String, FilenameFilter)`
* `org.eclipse.scout.rt.shared.services.common.file.IRemoteFileService.getRemoteFiles(String, FilenameFilter, RemoteFile[])`

== ICacheBuilder.withMaxConcurrentResolve: Allow multiple resolve operations for one thread

The `BoundedResolveCacheWrapper` (used implicitly by `ICacheBuilder.withMaxConcurrentResolve`) has been changed to allow multiple resolve operations for one thread (default is now reentrant) to avoid a potential deadlock cause.
That is, one thread will only be counted once towards the limit.

However, this is just one potential deadlock cause, deadlocks may still occur if the resolve operation also relies on external semaphores.

To restore the previous behavior the `BoundedResolveCacheWrapper` may be added directly as custom wrapper with the second constructor allowing to disable this reentrant behavior.
