FROM tomcat:jre8
MAINTAINER BSI-Business-Systems-Integration-AG

ADD org.eclipse.scout.widgets.ui.html.app.dev-9.0.0.024_Simrel_2019_09_RC1.war /usr/local/tomcat/webapps/widgets.war

CMD ["catalina.sh", "run"]
