FROM tomcat:jre8
MAINTAINER BSI-Business-Systems-Integration-AG

ADD org.eclipse.scout.widgets.ui.html.app.dev-7.0.300.004_Oxygen_3_RC3.war /usr/local/tomcat/webapps/widgets.war

CMD ["catalina.sh", "run"]