/*******************************************************************************
 * Copyright (c) 2015 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.html
 * 
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 ******************************************************************************/
package org.eclipsescout.demo.widgets.shared.ui.template.formfield;

import java.util.Date;
import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractFileDetailsBoxData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  public AbstractFileDetailsBoxData() {
  }

  public Modified getModified() {
    return getFieldByClass(Modified.class);
  }

  public Name getName() {
    return getFieldByClass(Name.class);
  }

  public ReadOnly getReadOnly() {
    return getFieldByClass(ReadOnly.class);
  }

  public Size getSize() {
    return getFieldByClass(Size.class);
  }

  public static class Modified extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;

    public Modified() {
    }
  }

  public static class Name extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Name() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class ReadOnly extends AbstractValueFieldData<Boolean> {

    private static final long serialVersionUID = 1L;

    public ReadOnly() {
    }
  }

  public static class Size extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;

    public Size() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_VALUE, Long.MAX_VALUE);
      ruleMap.put(ValidationRule.MIN_VALUE, Long.MIN_VALUE);
    }
  }
}