include::common:partial$_initSubDoc.adoc[]

//-----------------------------------------------------------------------------
//Asciidoctor input file: "One Day Tutorial"
//
//WARNING: this file is a text module, it should be embedded in a master asciidoctor document.
//-----------------------------------------------------------------------------

[[cha-large_example]]
In this tutorial we will create the "`Contacts`" Scout application.
The goal of this application is to learn about the most prominent features of the Eclipse Scout framework using a fully functional application.

The application is kept small enough to complete this tutorial within less than a day.
An extended version of "`Contacts`" is available as a Scout sample application on link:https://github.com/bsi-software/org.eclipse.scout.docs/tree/{git-branch}/code/contacts[Github].

For this tutorial you can use IntelliJ or Eclipse IDE with installed Scout SDK plugins.
If you have successfully completed the http://eclipsescout.github.io/{scout-version}/helloscout.html[Hello Scout Tutorial] you should have a running Eclipse Scout installation.
If not, then you should do the Hello Scout Tutorial now.

The "`One Day Tutorial`" is organized as follows.
In the first section, the finished "`Contacts`" application is explained from the user perspective.
The remaining sections focus on the individual steps to implement the "`Contacts`" tutorial application.

//--- tutorial intro --------------------------------------------------------//

include::partial$_TutorialIntro.adoc[]

//--- tutorial steps --------------------------------------------------------//

[[sec-contacts_initial_project]]
== Setting up the Initial Project

include::partial$_TutorialStep1.adoc[]

[[sec-contacts_pages]]
== Adding the Person and Organization Page

include::partial$_TutorialStep2.adoc[]

[[sec-contacts_jdbc]]
== Creating and Accessing the Database

include::partial$_TutorialStep3.adoc[]

[[sec-contacts_forms]]
== Adding a Form to Create/Edit Persons

include::partial$_TutorialStep4.adoc[]

[[sec-contacts_fields]]
== Form Field Validation and Template Fields

include::partial$_TutorialStep5.adoc[]

[[sec-contacts_form_add_company]]
== Adding the Company Form

include::partial$_TutorialStep6.adoc[]

[[sec-contacts_link_organization_person]]
== Linking Organizations and Persons

include::partial$_TutorialStep7.adoc[]

[[sec-source_control]]
== Git configuration

If you want to add the created application to a Git repository there might some configurations be helpful. If there are no plans to use Git, this chapter can be skipped.

E.g. it is best practice to exclude some files from adding to a Git repository. These exclusions can be configured by creating a file named `.gitignore` in the root folder of the repository (see the https://git-scm.com/docs/gitignore[Git Documentation] for details).
Here is a sample file that might be used as starting point:

....
# Git
*.orig

# Maven
target/
.surefire-*
.flattened-pom.xml

# Node
node_modules/
test-results/

# Do not check in any log files
*.log
....
