= Hello Scout JS Full Stack
include::common:partial$_header.adoc[]

== Introduction

In this tutorial we will create a Scout JS application consisting of a JavaScript frontend connected using REST to a Java backend that stores the data in a database.

NOTE: If you don't know what Scout JS is yet, please read the xref:getstarted:getstarted.adoc[Get Started Guide] first.

We will create the application using IntelliJ.
The generated application can display persons loaded from a database.
These persons can be edited or deleted and new persons can be added.

== Prerequisites

This section guides you through the installation of the tools required to start the `Hello Scout JS Full Stack` application.

=== Node.js

include::common:partial$InstallNode.adoc[]

[#intellij]
=== IntelliJ

include::common:partial$InstallIntelliJ.adoc[]

== Create the Project

include::common:partial$CreateNewJsProjectIntellij.adoc[]

== What's Next?
To learn more about Scout JS, we recommend having a look at the other Scout JS Hello World tutorials and the xref:technical-guide:technical-guide.adoc[Technical Guide].

To see more example code of Scout JS, you should have a look at the {jswidgets}[Scout JS Widgets] application
and its {jswidgets-code}[source code].

In case you should get stuck somewhere and need help, contact us on the http://www.eclipse.org/forums/eclipse.scout[Scout Forum] or on https://stackoverflow.com/tags/eclipse-scout[Stack Overflow].


