/*******************************************************************************
 * Copyright (c) 2015 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 ******************************************************************************/
package org.eclipse.scout.contacts.shared.contact;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "org.eclipse.scout.contacts.client.contact.ContactsTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ContactsTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  public ContactsTablePageData() {
  }

  @Override
  public ContactsTableRowData addRow() {
    return (ContactsTableRowData) super.addRow();
  }

  @Override
  public ContactsTableRowData addRow(int rowState) {
    return (ContactsTableRowData) super.addRow(rowState);
  }

  @Override
  public ContactsTableRowData createRow() {
    return new ContactsTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return ContactsTableRowData.class;
  }

  @Override
  public ContactsTableRowData[] getRows() {
    return (ContactsTableRowData[]) super.getRows();
  }

  @Override
  public ContactsTableRowData rowAt(int index) {
    return (ContactsTableRowData) super.rowAt(index);
  }

  public void setRows(ContactsTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class ContactsTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String contactId = "contactId";
    public static final String firstName = "firstName";
    public static final String lastName = "lastName";
    public static final String city = "city";
    public static final String country = "country";
    public static final String phone = "phone";
    public static final String mobile = "mobile";
    public static final String email = "email";
    public static final String company = "company";
    private String m_contactId;
    private String m_firstName;
    private String m_lastName;
    private String m_city;
    private String m_country;
    private String m_phone;
    private String m_mobile;
    private String m_email;
    private String m_company;

    public ContactsTableRowData() {
    }

    public String getContactId() {
      return m_contactId;
    }

    public void setContactId(String contactId) {
      m_contactId = contactId;
    }

    public String getFirstName() {
      return m_firstName;
    }

    public void setFirstName(String firstName) {
      m_firstName = firstName;
    }

    public String getLastName() {
      return m_lastName;
    }

    public void setLastName(String lastName) {
      m_lastName = lastName;
    }

    public String getCity() {
      return m_city;
    }

    public void setCity(String city) {
      m_city = city;
    }

    public String getCountry() {
      return m_country;
    }

    public void setCountry(String country) {
      m_country = country;
    }

    public String getPhone() {
      return m_phone;
    }

    public void setPhone(String phone) {
      m_phone = phone;
    }

    public String getMobile() {
      return m_mobile;
    }

    public void setMobile(String mobile) {
      m_mobile = mobile;
    }

    public String getEmail() {
      return m_email;
    }

    public void setEmail(String email) {
      m_email = email;
    }

    public String getCompany() {
      return m_company;
    }

    public void setCompany(String company) {
      m_company = company;
    }
  }
}
