/*
 * Copyright (c) 2010, 2023 BSI Business Systems Integration AG
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.scout.contacts.events.shared.person;

import java.io.Serializable;

import jakarta.annotation.Generated;

import org.eclipse.scout.contacts.shared.person.PersonTablePageData.PersonTableRowData;
import org.eclipse.scout.rt.platform.extension.Extends;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Extends(PersonTableRowData.class)
@Generated(value = "org.eclipse.scout.contacts.events.client.person.PersonTablePageExtension", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PersonTablePageDataExtension implements Serializable {
  private static final long serialVersionUID = 1L;
  public static final String events = "events";
  private Long m_events;

  public Long getEvents() {
    return m_events;
  }

  public void setEvents(Long newEvents) {
    m_events = newEvents;
  }
}
