= Hello Scout Classic
// comment prevents empty line after formatting, needed for toc
include::common:partial$_header.adoc[]

== Introduction

In this tutorial we will create your first Scout Classic application.

NOTE: If you don't know what Scout Classic is yet, please read the https://eclipsescout.github.io/{doc-short-version}/getstarted.html[Get Started Guide] first.

We will create the application using Eclipse or IntelliJ.
The generated application will consist of a client and server part and simply display a text sent from the server.

== Prerequisites

include::common:partial$DownloadScout.adoc[]

== Create a Scout Project

include::common:partial$CreateNewProject.adoc[]

== What's Next?

Congratulations! You have successfully created your first Scout Classic application.

To gain experience working with Scout, we recommend going through the https://eclipsescout.github.io/{doc-short-version}/one-day-tutorial.html[One Day Tutorial].

If you are interested in Scout's concepts, architecture and features you probably want to have a look at the https://eclipsescout.github.io/{doc-short-version}/technical-guide.html[Technical Guide].

In case you should get stuck somewhere and need help, contact us on the http://www.eclipse.org/forums/eclipse.scout[Scout Forum] or on https://stackoverflow.com/tags/eclipse-scout[Stack Overflow].

We wish you all the best on your journey with Scout.

:_footer-link-path: build/helloscout/src/docs/{docname}.adoc
include::common:partial$_footer.adoc[]
